function [data,msg] = fetch_ws1_ec_avg(template)

%connect to the database
conn = database('metdat', '', '', 'Vendor', 'MICROSOFT SQL SERVER', 'Server', 'Stewartia', 'PortNumber', 1433, 'AuthType', 'Windows');

if exist('template','var') ~= 1
   template = 'LNDB_Ws1_2';
end

% qry = ['SELECT 	hjaws1ec_avg_arch1.TmStamp'...
%     ' ,	hjaws1ec_avg_arch1.RecNum'...
%     ' ,	hjaws1ec_avg_arch1.CO2mmol_Avg'...
%     ' ,	hjaws1ec_avg_arch1.H2Ommol_Avg'...
%     ' ,	hjaws1ec_avg_arch1.press_li7500_Avg'...
%     ' ,	hjaws1ec_avg_arch1.Ts_Avg'...
%     ' ,	hjaws1ec_avg_arch1.Ts_csat_Avg'...
%     ' ,	hjaws1ec_avg_arch1.Ux_Avg'...
%     ' ,	hjaws1ec_avg_arch1.Ux_csat_Avg'...
%     ' ,	hjaws1ec_avg_arch1.Uy_Avg'...
%     ' ,	hjaws1ec_avg_arch1.Uy_csat_Avg'...
%     ' ,	hjaws1ec_avg_arch1.Uz_Avg'...
%     ' ,	hjaws1ec_avg_arch1.Uz_csat_Avg'...
%     ' FROM 	metdat.dbo.hjaws1ec_avg_arch1'...
%     ' ORDER BY TmStamp ASC '];

qry = ['SELECT hjaws1ec_avg.TmStamp'...
    ' ,	hjaws1ec_avg.RecNum'...
    ' ,	hjaws1ec_avg.agc_li7500_top_Max'...
    ' ,	hjaws1ec_avg.Albedo_Avg'...
    ' ,	hjaws1ec_avg.Batt_Volt_Min'...
    ' ,	hjaws1ec_avg.CO2mmol_top_Avg'...
    ' ,	hjaws1ec_avg.counter_Max'...
    ' ,	hjaws1ec_avg.diag_li7500_top_Max'...
    ' ,	hjaws1ec_avg.diag_sub_Max'...
    ' ,	hjaws1ec_avg.DnTot_Avg'...
    ' ,	hjaws1ec_avg.H2Ommol_top_Avg'...
    ' ,	hjaws1ec_avg.IR01DnCo_Avg'...
    ' ,	hjaws1ec_avg.IR01UpCo_Avg'...
    ' ,	hjaws1ec_avg.NetRl_Avg'...
    ' ,	hjaws1ec_avg.NetRs_Avg'...
    ' ,	hjaws1ec_avg.NetTot_Avg'...
    ' ,	hjaws1ec_avg.NR01TC_Avg'...
    ' ,	hjaws1ec_avg.NR01TK_Avg'...
    ' ,	hjaws1ec_avg.Panel_T_Avg'...
    ' ,	hjaws1ec_avg.press_li7500_top_Avg'...
    ' ,	hjaws1ec_avg.SR01Dn_Avg'...
    ' ,	hjaws1ec_avg.SR01Up_Avg'...
    ' ,	hjaws1ec_avg.Ts_sub_Avg'...
    ' ,	hjaws1ec_avg.Ts_sub_Std'...
    ' ,	hjaws1ec_avg.Ts_top_Avg'...
    ' ,	hjaws1ec_avg.Ts_top_Std'...
    ' ,	hjaws1ec_avg.UpTot_Avg'...
    ' ,	hjaws1ec_avg.Ux_sub_Avg'...
    ' ,	hjaws1ec_avg.Ux_sub_Std'...
    ' ,	hjaws1ec_avg.Ux_top_Avg'...
    ' ,	hjaws1ec_avg.Ux_top_Std'...
    ' ,	hjaws1ec_avg.Uy_sub_Avg'...
    ' ,	hjaws1ec_avg.Uy_sub_Std'...
    ' ,	hjaws1ec_avg.Uy_top_Avg'...
    ' ,	hjaws1ec_avg.Uy_top_Std'...
    ' ,	hjaws1ec_avg.Uz_sub_Avg'...
    ' ,	hjaws1ec_avg.Uz_sub_Std'...
    ' ,	hjaws1ec_avg.Uz_top_Avg'...
    ' ,	hjaws1ec_avg.Uz_top_Std'...
    ' ,	hjaws1ec_avg.WDir_mean_sub'...
    ' ,	hjaws1ec_avg.WDir_mean_top'...
    ' ,	hjaws1ec_avg.WDir_std_sub'...
    ' ,	hjaws1ec_avg.WDir_std_top'...
    ' ,	hjaws1ec_avg.WSpd_mean_sub'...
    ' ,	hjaws1ec_avg.WSpd_mean_top'...
    ' FROM 	metdat.dbo.hjaws1ec_avg'...
    ' WHERE year(TmStamp) = 2014'...
    ' ORDER BY TmStamp ASC '];

% %% Query for real-time data updates only
% qry = ['SELECT hjaws1ec_avg.TmStamp'...
%     ' ,	hjaws1ec_avg.RecNum'...
%     ' ,	hjaws1ec_avg.agc_li7500_top_Max'...
%     ' ,	hjaws1ec_avg.Albedo_Avg'...
%     ' ,	hjaws1ec_avg.Batt_Volt_Min'...
%     ' ,	hjaws1ec_avg.CO2mmol_top_Avg'...
%     ' ,	hjaws1ec_avg.counter_Max'...
%     ' ,	hjaws1ec_avg.diag_li7500_top_Max'...
%     ' ,	hjaws1ec_avg.diag_sub_Max'...
%     ' ,	hjaws1ec_avg.DnTot_Avg'...
%     ' ,	hjaws1ec_avg.H2Ommol_top_Avg'...
%     ' ,	hjaws1ec_avg.IR01DnCo_Avg'...
%     ' ,	hjaws1ec_avg.IR01UpCo_Avg'...
%     ' ,	hjaws1ec_avg.NetRl_Avg'...
%     ' ,	hjaws1ec_avg.NetRs_Avg'...
%     ' ,	hjaws1ec_avg.NetTot_Avg'...
%     ' ,	hjaws1ec_avg.NR01TC_Avg'...
%     ' ,	hjaws1ec_avg.NR01TK_Avg'...
%     ' ,	hjaws1ec_avg.Panel_T_Avg'...
%     ' ,	hjaws1ec_avg.press_li7500_top_Avg'...
%     ' ,	hjaws1ec_avg.SR01Dn_Avg'...
%     ' ,	hjaws1ec_avg.SR01Up_Avg'...
%     ' ,	hjaws1ec_avg.Ts_sub_Avg'...
%     ' ,	hjaws1ec_avg.Ts_sub_Std'...
%     ' ,	hjaws1ec_avg.Ts_top_Avg'...
%     ' ,	hjaws1ec_avg.Ts_top_Std'...
%     ' ,	hjaws1ec_avg.UpTot_Avg'...
%     ' ,	hjaws1ec_avg.Ux_sub_Avg'...
%     ' ,	hjaws1ec_avg.Ux_sub_Std'...
%     ' ,	hjaws1ec_avg.Ux_top_Avg'...
%     ' ,	hjaws1ec_avg.Ux_top_Std'...
%     ' ,	hjaws1ec_avg.Uy_sub_Avg'...
%     ' ,	hjaws1ec_avg.Uy_sub_Std'...
%     ' ,	hjaws1ec_avg.Uy_top_Avg'...
%     ' ,	hjaws1ec_avg.Uy_top_Std'...
%     ' ,	hjaws1ec_avg.Uz_sub_Avg'...
%     ' ,	hjaws1ec_avg.Uz_sub_Std'...
%     ' ,	hjaws1ec_avg.Uz_top_Avg'...
%     ' ,	hjaws1ec_avg.Uz_top_Std'...
%     ' ,	hjaws1ec_avg.WDir_mean_sub'...
%     ' ,	hjaws1ec_avg.WDir_mean_top'...
%     ' ,	hjaws1ec_avg.WDir_std_sub'...
%     ' ,	hjaws1ec_avg.WDir_std_top'...
%     ' ,	hjaws1ec_avg.WSpd_mean_sub'...
%     ' ,	hjaws1ec_avg.WSpd_mean_top'...
%     ' FROM 	metdat.dbo.hjaws1ec_avg'...
%     ' WHERE   TmStamp >= DATEADD(day, -21, GETDATE())'...
%     ' ORDER BY TmStamp ASC '];

[data,msg] = sql2gceds(conn, ...
                        qry, ...
                        template, ...
                        1, ...
                        0, ...
                        1);

% %close database connection
 close(conn);


