function [data,msg] = fetch_loma_203_107(template)

%connect to the database
conn = database('metdat', '', '', 'Vendor', 'MICROSOFT SQL SERVER', 'Server', 'Stewartia', 'PortNumber', 1433, 'AuthType', 'Windows');

if exist('template','var') ~= 1
   template = '';
end

qry = ['SELECT LOMA_203_107.TmStamp'...
    ' ,	LOMA_203_107.RecNum'...
    ' ,	LOMA_203_107.SITE_ID'...
    ' ,	LOMA_203_107.AIR_TEMP_AVG'...
    ' ,	LOMA_203_107.LOOKOUT_W_AVG'...
    ' ,	LOMA_203_107.MACK_AVG'...
    ' ,	LOMA_203_107.AIR_TEMP_MAX'...
    ' ,	LOMA_203_107.AIR_TEMP_Hr_Min_MAX'...
    ' ,	LOMA_203_107.LOOKOUT_W_MAX'...
    ' ,	LOMA_203_107.LOOKOUT_W_Hr_Min_MAX'...
    ' ,	LOMA_203_107.MACK_MAX'...
    ' ,	LOMA_203_107.MACK_Hr_Min_MAX'...
    ' ,	LOMA_203_107.AIR_TEMP_MIN'...
    ' ,	LOMA_203_107.AIR_TEMP_Hr_Min_MIN'...
    ' ,	LOMA_203_107.LOOKOUT_W_MIN'...
    ' ,	LOMA_203_107.LOOKOUT_W_Hr_Min_MIN'...
    ' ,	LOMA_203_107.MACK_MIN'...
    ' ,	LOMA_203_107.MACK_Hr_Min_MIN'...
    ' FROM 	metdat.dbo.LOMA_203_107 '...
    ' WHERE SITE_ID = 203' ...
    ' AND year(TmStamp) = 2014'...
    ' AND DATEPART(hh, TmStamp) = 00'...
    ' ORDER BY TmStamp ASC '];

[data,msg] = sql2gceds(conn, ...
                        qry, ...
                        template, ...
                        1, ...
                        0, ...
                        1);

% %close database connection
 close(conn);



