function [data,msg] = fetch_varmet_301_105(template)

%connect to the database
conn = database('metdat', '', '', 'Vendor', 'MICROSOFT SQL SERVER', 'Server', 'Stewartia', 'PortNumber', 1433, 'AuthType', 'Windows');

if exist('template','var') ~= 1
    template = '';
end

qry = ['SELECT VARA_301_105.TmStamp'...
    ' ,	VARA_301_105.RecNum'...
    ' ,	VARA_301_105.LOGGERID'...
    ' ,	VARA_301_105.PROGID'...
    ' ,	VARA_301_105.OR_TEMP'...
    ' ,	VARA_301_105.PRECIP'...
    ' ,	VARA_301_105.QUALITY'...
    ' ,	VARA_301_105.SNOWDEPTH'...
    ' ,	VARA_301_105.SWE_AVG'...
    ' FROM 	metdat.dbo.VARA_301_105'...
    ' WHERE year(TmStamp) = 2015'...
    ' AND LOGGERID = 301' ...
    ' ORDER BY TmStamp ASC '];

%% Query for real-time data updates only
% qry = ['SELECT VARA_301_105.TmStamp'...
%     ' ,	VARA_301_105.RecNum'...
%     ' ,	VARA_301_105.LOGGERID'...
%     ' ,	VARA_301_105.PROGID'...
%     ' ,	VARA_301_105.OR_TEMP'...
%     ' ,	VARA_301_105.PRECIP'...
%     ' ,	VARA_301_105.QUALITY'...
%     ' ,	VARA_301_105.SNOWDEPTH'...
%     ' ,	VARA_301_105.SWE_AVG'...
%     '   FROM metdat.dbo.VARA_301_105'...
%     '   WHERE   TmStamp >= DATEADD(day, -21, GETDATE())'...
%     '   AND LOGGERID = 301' ...
%     '   ORDER BY TmStamp ASC '];

[data,msg] = sql2gceds(conn, ...
                        qry, ...
                        template, ...
                        1, ...
                        0, ...
                        1);

% %close database connection
 close(conn);


