function [data,msg] = fetch_loup_204_103(template)

%connect to the database
conn = database('metdat', '', '', 'Vendor', 'MICROSOFT SQL SERVER', 'Server', 'Stewartia', 'PortNumber', 1433, 'AuthType', 'Windows');

if exist('template','var') ~= 1
   template = '';
end

qry = ['SELECT 	LOUP_204_103.TmStamp'...
    ' ,	LOUP_204_103.RecNum'...
    ' ,	LOUP_204_103.SITE_ID'...
    ' ,	LOUP_204_103.AIR_TEMP_AVG'...
    ' ,	LOUP_204_103.WATER_C_AVG'...
    ' FROM 	metdat.dbo.LOUP_204_103 '...
    ' WHERE SITE_ID = 204' ...
    ' AND year(TmStamp) = 2014'...
    ' ORDER BY TmStamp ASC '];

[data,msg] = sql2gceds(conn, ...
                        qry, ...
                        template, ...
                        1, ...
                        0, ...
                        1);

% %close database connection
 close(conn);



