function [data,msg] = fetch_mcup_205_103(template)

%connect to the database
conn = database('metdat', '', '', 'Vendor', 'MICROSOFT SQL SERVER', 'Server', 'Stewartia', 'PortNumber', 1433, 'AuthType', 'Windows');

if exist('template','var') ~= 1
   template = '';
end

qry = ['SELECT 	MCUP_205_103.TmStamp'...
    ' ,	MCUP_205_103.RecNum'...
    ' ,	MCUP_205_103.SITE_ID'...
    ' ,	MCUP_205_103.AIR_TEMP_AVG'...
    ' ,	MCUP_205_103.WATER_C_AVG'...
    ' FROM 	metdat.dbo.MCUP_205_103 '...
    ' WHERE SITE_ID = 205' ...
    ' AND year(TmStamp) = 2014'...
    ' ORDER BY TmStamp ASC '];

[data,msg] = sql2gceds(conn, ...
                        qry, ...
                        template, ...
                        1, ...
                        0, ...
                        1);

% %close database connection
 close(conn);



