function [data,msg] = fetch_hagg_01_TmpCnd_MP1(template)

%connect to the database
conn = database('metdat', '', '', 'Vendor', 'MICROSOFT SQL SERVER', 'Server', 'Stewartia', 'PortNumber', 1433, 'AuthType', 'Windows');

if exist('template','var') ~= 1
   template = '';
end

% qry = ['SELECT Hagg_01_TmpCnd_MP1.TmStamp'...
%     ' ,	Hagg_01_TmpCnd_MP1.RecNum'...
%     ' ,	Hagg_01_TmpCnd_MP1.T_STR'...
%     ' ,	Hagg_01_TmpCnd_MP1.T_F2'...
%     ' ,	Hagg_01_TmpCnd_MP1.T_F3'...
%     ' ,	Hagg_01_TmpCnd_MP1.T_D4'...
%     ' ,	Hagg_01_TmpCnd_MP1.T_D5'...
%     ' ,	Hagg_01_TmpCnd_MP1.T_C6'...
%     ' ,	Hagg_01_TmpCnd_MP1.T_F5'...
%     ' ,	Hagg_01_TmpCnd_MP1.T_E2'...
%     ' ,	Hagg_01_TmpCnd_MP1.T_E3'...
%     ' ,	Hagg_01_TmpCnd_MP1.T_E5'...
%     ' ,	Hagg_01_TmpCnd_MP1.T_E4'...
%     ' ,	Hagg_01_TmpCnd_MP1.T_DE4'...
%     ' ,	Hagg_01_TmpCnd_MP1.T_E6'...
%     ' ,	Hagg_01_TmpCnd_MP1.T_F4'...
%     ' ,	Hagg_01_TmpCnd_MP1.T_NaN'...
%     ' ,	Hagg_01_TmpCnd_MP1.T_D6'...
%     ' ,	Hagg_01_TmpCnd_MP1.EC_STR'...
%     ' ,	Hagg_01_TmpCnd_MP1.EC_F2'...
%     ' ,	Hagg_01_TmpCnd_MP1.EC_F3'...
%     ' ,	Hagg_01_TmpCnd_MP1.EC_D4'...
%     ' ,	Hagg_01_TmpCnd_MP1.EC_D5'...
%     ' ,	Hagg_01_TmpCnd_MP1.EC_C6'...
%     ' ,	Hagg_01_TmpCnd_MP1.EC_F5'...
%     ' ,	Hagg_01_TmpCnd_MP1.EC_E2'...
%     ' ,	Hagg_01_TmpCnd_MP1.EC_E3'...
%     ' ,	Hagg_01_TmpCnd_MP1.EC_E5'...
%     ' ,	Hagg_01_TmpCnd_MP1.EC_E4'...
%     ' ,	Hagg_01_TmpCnd_MP1.EC_DE4'...
%     ' ,	Hagg_01_TmpCnd_MP1.EC_E6'...
%     ' ,	Hagg_01_TmpCnd_MP1.EC_F4'...
%     ' ,	Hagg_01_TmpCnd_MP1.EC_NaN'...
%     ' ,	Hagg_01_TmpCnd_MP1.EC_D6'...
%     ' FROM 	metdat.dbo.Hagg_01_TmpCnd_MP1'...
%     ' WHERE year(TmStamp) = 2015'...
%     ' ORDER BY TmStamp ASC '];

qry = ['SELECT 	Hagg_01_TmpCnd_MP1.TmStamp'...
    ' ,	Hagg_01_TmpCnd_MP1.RecNum'...
    ' ,	Hagg_01_TmpCnd_MP1.T_STR'...
    ' ,	Hagg_01_TmpCnd_MP1.T_F2'...
    ' ,	Hagg_01_TmpCnd_MP1.T_F3'...
    ' ,	Hagg_01_TmpCnd_MP1.T_D4'...
    ' ,	Hagg_01_TmpCnd_MP1.T_D5'...
    ' ,	Hagg_01_TmpCnd_MP1.T_C6'...
    ' ,	Hagg_01_TmpCnd_MP1.T_F5'...
    ' ,	Hagg_01_TmpCnd_MP1.T_E2'...
    ' ,	Hagg_01_TmpCnd_MP1.T_E3'...
    ' ,	Hagg_01_TmpCnd_MP1.T_E5'...
    ' ,	Hagg_01_TmpCnd_MP1.T_E4'...
    ' ,	Hagg_01_TmpCnd_MP1.T_DE4'...
    ' ,	Hagg_01_TmpCnd_MP1.T_E6'...
    ' ,	Hagg_01_TmpCnd_MP1.T_F4'...
    ' ,	Hagg_01_TmpCnd_MP1.T_NaN'...
    ' ,	Hagg_01_TmpCnd_MP1.T_D6'...
    ' ,	Hagg_01_TmpCnd_MP1.EC_STR'...
    ' ,	Hagg_01_TmpCnd_MP1.EC_F2'...
    ' ,	Hagg_01_TmpCnd_MP1.EC_F3'...
    ' ,	Hagg_01_TmpCnd_MP1.EC_D4'...
    ' ,	Hagg_01_TmpCnd_MP1.EC_D5'...
    ' ,	Hagg_01_TmpCnd_MP1.EC_C6'...
    ' ,	Hagg_01_TmpCnd_MP1.EC_F5'...
    ' ,	Hagg_01_TmpCnd_MP1.EC_E2'...
    ' ,	Hagg_01_TmpCnd_MP1.EC_E3'...
    ' ,	Hagg_01_TmpCnd_MP1.EC_E5'...
    ' ,	Hagg_01_TmpCnd_MP1.EC_E4'...
    ' ,	Hagg_01_TmpCnd_MP1.EC_DE4'...
    ' ,	Hagg_01_TmpCnd_MP1.EC_E6'...
    ' ,	Hagg_01_TmpCnd_MP1.EC_F4'...
    ' ,	Hagg_01_TmpCnd_MP1.EC_NaN'...
    ' ,	Hagg_01_TmpCnd_MP1.EC_D6'...
    ' FROM 	metdat.dbo.Hagg_01_TmpCnd_MP1'...
   ' WHERE   TmStamp >= DATEADD(day, -21, GETDATE())'...
   ' ORDER BY TmStamp ASC '];

[data,msg] = sql2gceds(conn, ...
                        qry, ...
                        template, ...
                        1, ...
                        0, ...
                        1);

% %close database connection
 close(conn);



