function [data,msg] = fetch_varmet_301_115(template)

%connect to the database
conn = database('metdat', '', '', 'Vendor', 'MICROSOFT SQL SERVER', 'Server', 'Stewartia', 'PortNumber', 1433, 'AuthType', 'Windows');

if exist('template','var') ~= 1
   template = '';
end

qry = ['SELECT VARA_301_115.TmStamp'...
    ' ,	VARA_301_115.RecNum'...
    ' ,	VARA_301_115.LOGGERID'...
    ' ,	VARA_301_115.PROGID'...
    ' ,	VARA_301_115.AIR_450_AVG'...
    ' FROM 	metdat.dbo.VARA_301_115'...
    ' WHERE year(TmStamp) = 2015'...
    ' AND LOGGERID = 301' ...
    ' ORDER BY TmStamp ASC '];

%% Query for real-time data updates only
% qry = ['SELECT VARA_301_115.TmStamp'...
%     ' ,	VARA_301_115.RecNum'...
%     ' ,	VARA_301_115.LOGGERID'...
%     ' ,	VARA_301_115.PROGID'...
%     ' ,	VARA_301_115.AIR_450_AVG'...
%     ' FROM 	metdat.dbo.VARA_301_115'...
%     ' WHERE TmStamp >= DATEADD(day, -21, GETDATE())'...
%     ' AND LOGGERID = 301' ...
%     ' ORDER BY TmStamp ASC '];

[data,msg] = sql2gceds(conn, ...
                        qry, ...
                        template, ...
                        1, ...
                        0, ...
                        1);

% %close database connection
 close(conn);


