function [data,msg] = fetch_lolo_201_107(template)

%connect to the database
conn = database('metdat', '', '', 'Vendor', 'MICROSOFT SQL SERVER', 'Server', 'Stewartia', 'PortNumber', 1433, 'AuthType', 'Windows');

if exist('template','var') ~= 1
   template = '';
end
%

qry = ['SELECT 	LOLO_201_107.TmStamp'...
    ' ,	LOLO_201_107.RecNum'...
    ' ,	LOLO_201_107.SITE_ID'...
    ' ,	LOLO_201_107.AIR_TEMP_AVG'...
    ' ,	LOLO_201_107.WATER_C_AVG'...
    ' ,	LOLO_201_107.AIR_TEMP_MAX'...
    ' ,	LOLO_201_107.AIR_TEMP_Hr_Min_MAX'...
    ' ,	LOLO_201_107.WATER_C_MAX'...
    ' ,	LOLO_201_107.WATER_C_Hr_Min_MAX'...
    ' ,	LOLO_201_107.AIR_TEMP_MIN'...
    ' ,	LOLO_201_107.AIR_TEMP_Hr_Min_MIN'...
    ' ,	LOLO_201_107.WATER_C_MIN'...
    ' ,	LOLO_201_107.WATER_C_Hr_Min_MIN'...
    ' FROM metdat.dbo.LOLO_201_107 '...
    ' WHERE SITE_ID = 201' ...
    ' AND year(TmStamp) = 2014'...
    ' AND DATEPART(hh, TmStamp) = 00'...
    ' ORDER BY TmStamp ASC '];

[data,msg] = sql2gceds(conn, ...
                        qry, ...
                        template, ...
                        1, ...
                        0, ...
                        1);

% %close database connection
 close(conn);



