function [data,msg] = fetch_refstand_04_hrly(template)

%connect to the database
conn = database('metdat', '', '', 'Vendor', 'MICROSOFT SQL SERVER', 'Server', 'Stewartia', 'PortNumber', 1433, 'AuthType', 'Windows');

if exist('template','var') ~= 1
   template = '';
end

qry = ['SELECT RS04_115.TmStamp'...
    ' ,	RS04_115.RecNum'...
    ' ,	RS04_115.SITE_ID'...
    ' ,	RS04_115.AIR_TEMP_AVG'...
    ' FROM 	metdat.dbo.RS04_115'...
    ' WHERE SITE_ID = 4' ...
    ' ORDER BY TmStamp ASC'];

[data,msg] = sql2gceds(conn, ...
                        qry, ...
                        template, ...
                        1, ...
                        0, ...
                        1);

% %close database connection
 close(conn);



