function [data,msg] = fetch_phrsc_Table2(template)

%connect to the database
conn = database('metdat', '', '', 'Vendor', 'MICROSOFT SQL SERVER', 'Server', 'Stewartia', 'PortNumber', 1433, 'AuthType', 'Windows');

if exist('template','var') ~= 1
   template = '';
end

qry = ['SELECT PHRSC_Table2.TmStamp'...
    ' ,	PHRSC_Table2.RecNum'...
    ' ,	PHRSC_Table2.RMY_ASP_Avg'...
    ' ,	PHRSC_Table2.RMY_ASP_Max'...
    ' ,	PHRSC_Table2.RMY_ASP_Min'...
    ' ,	PHRSC_Table2.Cotton_Avg'...
    ' ,	PHRSC_Table2.Cotton_Max'...
    ' ,	PHRSC_Table2.Cotton_Min'...
    ' ,	PHRSC_Table2.Gill_Sh_Avg'...
    ' ,	PHRSC_Table2.Gill_Sh_Max'...
    ' ,	PHRSC_Table2.Gill_Sh_Min'...
    ' ,	PHRSC_Table2.HJA_Sh_Avg'...
    ' ,	PHRSC_Table2.HJA_Sh_Max'...
    ' ,	PHRSC_Table2.HJA_Sh_Min'...
    ' ,	PHRSC_Table2.Gill_Lg_Avg'...
    ' ,	PHRSC_Table2.Gill_Lg_Max'...
    ' ,	PHRSC_Table2.Gill_Lg_Min'...
    ' ,	PHRSC_Table2.HJA_Lg_Avg'...
    ' ,	PHRSC_Table2.HJA_Lg_Max'...
    ' ,	PHRSC_Table2.HJA_Lg_Min'...
    ' ,	PHRSC_Table2.Gill_AF_Avg'...
    ' ,	PHRSC_Table2.Gill_AF_Max'...
    ' ,	PHRSC_Table2.Gill_AF_Min'...
    ' ,	PHRSC_Table2.CM3_Up_Avg'...
    ' ,	PHRSC_Table2.CM3_Up_Max'...
    ' ,	PHRSC_Table2.CM3_Dn_Avg'...
    ' ,	PHRSC_Table2.CM3_Dn_Max'...
    ' ,	PHRSC_Table2.WindSp_Avg'...
    ' ,	PHRSC_Table2.WindSp_Max'...
    ' ,	PHRSC_Table2.WindDir'...
    '   FROM metdat.dbo.PHRSC_Table2'...
    '   WHERE year(TmStamp) = 2015'...
    '   ORDER BY TmStamp ASC '];

% qry = ['SELECT 	PHRSC_Table2.TmStamp'...
%     ' ,	PHRSC_Table2.RecNum'...
%     ' ,	PHRSC_Table2.RMY_ASP_Avg'...
%     ' ,	PHRSC_Table2.RMY_ASP_Max'...
%     ' ,	PHRSC_Table2.RMY_ASP_Min'...
%     ' ,	PHRSC_Table2.Cotton_Avg'...
%     ' ,	PHRSC_Table2.Cotton_Max'...
%     ' ,	PHRSC_Table2.Cotton_Min'...
%     ' ,	PHRSC_Table2.Gill_Sh_Avg'...
%     ' ,	PHRSC_Table2.Gill_Sh_Max'...
%     ' ,	PHRSC_Table2.Gill_Sh_Min'...
%     ' ,	PHRSC_Table2.HJA_Sh_Avg'...
%     ' ,	PHRSC_Table2.HJA_Sh_Max'...
%     ' ,	PHRSC_Table2.HJA_Sh_Min'...
%     ' ,	PHRSC_Table2.Gill_Lg_Avg'...
%     ' ,	PHRSC_Table2.Gill_Lg_Max'...
%     ' ,	PHRSC_Table2.Gill_Lg_Min'...
%     ' ,	PHRSC_Table2.HJA_Lg_Avg'...
%     ' ,	PHRSC_Table2.HJA_Lg_Max'...
%     ' ,	PHRSC_Table2.HJA_Lg_Min'...
%     ' ,	PHRSC_Table2.Gill_AF_Avg'...
%     ' ,	PHRSC_Table2.Gill_AF_Max'...
%     ' ,	PHRSC_Table2.Gill_AF_Min'...
%     ' ,	PHRSC_Table2.CM3_Up_Avg'...
%     ' ,	PHRSC_Table2.CM3_Up_Max'...
%     ' ,	PHRSC_Table2.CM3_Dn_Avg'...
%     ' ,	PHRSC_Table2.CM3_Dn_Max'...
%     ' ,	PHRSC_Table2.WindSp_Avg'...
%     ' ,	PHRSC_Table2.WindSp_Max'...
%     ' ,	PHRSC_Table2.WindDir'...
%     '     FROM metdat.dbo.PHRSC_Table2'...
%     '     WHERE TmStamp >= DATEADD(day, -31, GETDATE())'...
%     '     ORDER BY TmStamp ASC '];

[data,msg] = sql2gceds(conn, ...
                        qry, ...
                        template, ...
                        1, ...
                        0, ...
                        1);

% %close database connection
 close(conn);


