function [data,msg] = fetch_refstand_86_hrly(template)

%connect to the database
conn = database('metdat', '', '', 'Vendor', 'MICROSOFT SQL SERVER', 'Server', 'Stewartia', 'PortNumber', 1433, 'AuthType', 'Windows');

if exist('template','var') ~= 1
   template = '';
end

qry = ['SELECT RS86_115.TmStamp'...
    ' ,	RS86_115.RecNum'...
    ' ,	RS86_115.SITE_ID'...
    ' ,	RS86_115.AIR_TEMP_AVG'...
    ' ,	RS86_115.REL_HUM_AVG'...
    ' FROM 	metdat.dbo.RS86_115 '...
    ' WHERE SITE_ID = 86' ...
    ' ORDER BY TmStamp ASC'];

[data,msg] = sql2gceds(conn, ...
                        qry, ...
                        template, ...
                        1, ...
                        0, ...
                        1);

% %close database connection
 close(conn);



