function [data,msg] = fetch_refstand_89_6hr(template)

%connect to the database
conn = database('metdat', '', '', 'Vendor', 'MICROSOFT SQL SERVER', 'Server', 'Stewartia', 'PortNumber', 1433, 'AuthType', 'Windows');

if exist('template','var') ~= 1
   template = '';
end

qry = ['SELECT RS89_110.TmStamp'...
    ' ,	RS89_110.RecNum'...
    ' ,	RS89_110.SITE_ID'...
    ' ,	RS89_110.SOILT_10_AVG'...
    ' ,	RS89_110.SOILT_20_AVG'...
    ' ,	RS89_110.SOILT_30_AVG'...
    ' FROM 	metdat.dbo.RS89_110 '...
    ' WHERE SITE_ID = 89' ...
    ' ORDER BY TmStamp ASC'];

[data,msg] = sql2gceds(conn, ...
                        qry, ...
                        template, ...
                        1, ...
                        0, ...
                        1);

% %close database connection
 close(conn);



