function [data,msg] = fetch_ws1_hyd_avg(template)

%connect to the database
conn = database('metdat', '', '', 'Vendor', 'MICROSOFT SQL SERVER', 'Server', 'Stewartia', 'PortNumber', 1433, 'AuthType', 'Windows');

if exist('template','var') ~= 1
   template = 'LNDB_Ws1_1';
end

% qry = ['SELECT hjaws1met_CR510_124.TmStamp'...
%     ' ,	hjaws1met_CR510_124.RecNum'...
%     ' ,	hjaws1met_CR510_124.logger_V_AVG'...
%     ' ,	hjaws1met_CR510_124.panel_T_AVG'...
%     ' ,	hjaws1met_CR510_124.Ts_9_clea_AVG'...
%     ' ,	hjaws1met_CR510_124.Ts_9_shad_AVG'...
%     ' ,	hjaws1met_CR510_124.Twater_10_AVG'...
%     ' FROM 	metdat.dbo.hjaws1met_CR510_124'...
%     ' WHERE year(TmStamp) = 2013'...
%     ' ORDER BY TmStamp ASC '];

%% Query for real-time data updates only
qry = ['SELECT hjaws1met_CR510_124.TmStamp'...
    ' ,	hjaws1met_CR510_124.RecNum'...
    ' ,	hjaws1met_CR510_124.logger_V_AVG'...
    ' ,	hjaws1met_CR510_124.panel_T_AVG'...
    ' ,	hjaws1met_CR510_124.Ts_9_clea_AVG'...
    ' ,	hjaws1met_CR510_124.Ts_9_shad_AVG'...
    ' ,	hjaws1met_CR510_124.Twater_10_AVG'...
    ' FROM 	metdat.dbo.hjaws1met_CR510_124'...
    ' WHERE   TmStamp >= DATEADD(day, -21, GETDATE())'...     
    ' ORDER BY TmStamp ASC '];

[data,msg] = sql2gceds(conn, ...
                        qry, ...
                        template, ...
                        1, ...
                        0, ...
                        1);

% %close database connection
 close(conn);


