function [data,msg] = fetch_vanmet_232_b_105(template)

%connect to the database
conn = database('metdat', '', '', 'Vendor', 'MICROSOFT SQL SERVER', 'Server', 'Stewartia', 'PortNumber', 1433, 'AuthType', 'Windows');

if exist('template','var') ~= 1
   template = '';
end

qry = ['SELECT VAN_232_snc_avg.TmStamp'...
    ' ,	VAN_232_snc_avg.RecNum'...
    ' ,	VAN_232_snc_avg.LOGGERID'...
    ' ,	VAN_232_snc_avg.PROGID'...
    ' ,	VAN_232_snc_avg.SPD_mean'...
    ' ,	VAN_232_snc_avg.DIR_mean'...
    ' ,	VAN_232_snc_avg.DIR_std'...
    ' ,	VAN_232_snc_avg.SPD_Gust_max'...
    ' ,	VAN_232_snc_avg.Ux_Avg'...
    ' ,	VAN_232_snc_avg.Uy_Avg'...
    ' ,	VAN_232_snc_avg.Ux_Std'...
    ' ,	VAN_232_snc_avg.Uy_Std'...
    ' , VAN_232_snc_avg.Ts_Avg'...
    ' ,	VAN_232_snc_avg.Ts_Std'...
    ' FROM 	metdat.dbo.VAN_232_snc_avg'...
    ' WHERE year(TmStamp) = 2015'...
    ' ORDER BY TmStamp ASC '];

% qry = ['SELECT VAN_232_snc_avg.TmStamp'...
%     ' ,	VAN_232_snc_avg.RecNum'...
%     ' ,	VAN_232_snc_avg.LOGGERID'...
%     ' ,	VAN_232_snc_avg.PROGID'...
%     ' ,	VAN_232_snc_avg.SPD_mean'...
%     ' ,	VAN_232_snc_avg.DIR_mean'...
%     ' ,	VAN_232_snc_avg.DIR_std'...
%     ' ,	VAN_232_snc_avg.SPD_Gust_max'...
%     ' ,	VAN_232_snc_avg.Ux_Avg'...
%     ' ,	VAN_232_snc_avg.Uy_Avg'...
%     ' ,	VAN_232_snc_avg.Ux_Std'...
%     ' ,	VAN_232_snc_avg.Uy_Std'...
%     ' , VAN_232_snc_avg.Ts_Avg'...
%     ' ,	VAN_232_snc_avg.Ts_Std'...
%     ' FROM 	metdat.dbo.VAN_232_snc_avg'...
%     ' WHERE   TmStamp >= DATEADD(day, -21, GETDATE())'...
%     ' AND LOGGERID = 232' ...
%     ' ORDER BY TmStamp ASC '];

[data,msg] = sql2gceds(conn, ...
                        qry, ...
                        template, ...
                        1, ...
                        0, ...
                        1);

% %close database connection
 close(conn);

