function [data,msg] = fetch_mcup_205_107(template)

%connect to the database
conn = database('metdat', '', '', 'Vendor', 'MICROSOFT SQL SERVER', 'Server', 'Stewartia', 'PortNumber', 1433, 'AuthType', 'Windows');

if exist('template','var') ~= 1
   template = '';
end

qry = ['SELECT 	MCUP_205_107.TmStamp'...
    ' ,	MCUP_205_107.RecNum'...
    ' ,	MCUP_205_107.SITE_ID'...
    ' ,	MCUP_205_107.AIR_TEMP_AVG'...
    ' ,	MCUP_205_107.WATER_C_AVG'...
    ' ,	MCUP_205_107.AIR_TEMP_MAX'...
    ' ,	MCUP_205_107.AIR_TEMP_Hr_Min_MAX'...
    ' ,	MCUP_205_107.WATER_C_MAX'...
    ' ,	MCUP_205_107.WATER_C_Hr_Min_MAX'...
    ' ,	MCUP_205_107.AIR_TEMP_MIN'...
    ' ,	MCUP_205_107.AIR_TEMP_Hr_Min_MIN'...
    ' ,	MCUP_205_107.WATER_C_MIN'...
    ' ,	MCUP_205_107.WATER_C_Hr_Min_MIN'...
    ' FROM 	metdat.dbo.MCUP_205_107 '...
    ' WHERE SITE_ID = 205' ...
    ' AND year(TmStamp) = 2014'...
    ' AND DATEPART(hh, TmStamp) = 00'...
    ' ORDER BY TmStamp ASC '];

[data,msg] = sql2gceds(conn, ...
                        qry, ...
                        template, ...
                        1, ...
                        0, ...
                        1);

% %close database connection
 close(conn);



