function [data,msg] = fetch_primet_229_b_105(template)

%connect to the database
conn = database('metdat', '', '', 'Vendor', 'MICROSOFT SQL SERVER', 'Server', 'Stewartia', 'PortNumber', 1433, 'AuthType', 'Windows');

if exist('template','var') ~= 1
   template = '';
end

qry = ['SELECT PRIM_229_snc_avg.TmStamp'...
    ' ,	PRIM_229_snc_avg.RecNum'...
    ' ,	PRIM_229_snc_avg.LOGGERID'...
    ' ,	PRIM_229_snc_avg.PROGID'...
    ' ,	PRIM_229_snc_avg.Dir_mean'...
    ' ,	PRIM_229_snc_avg.Dir_std'...
    ' ,	PRIM_229_snc_avg.Spd_Gust_max'...
    ' ,	PRIM_229_snc_avg.Spd_mean'...
    ' ,	PRIM_229_snc_avg.Ux_Avg'...
    ' ,	PRIM_229_snc_avg.Ux_Std'...
    ' ,	PRIM_229_snc_avg.Uy_Avg'...
    ' ,	PRIM_229_snc_avg.Uy_Std'...
    ' , PRIM_229_snc_avg.Ts_Avg'...
    ' ,	PRIM_229_snc_avg.Ts_Std'...
    ' ,	PRIM_229_snc_avg.N_samples'...
    ' ,	PRIM_229_snc_avg.N_samples_good'...
    ' FROM 	metdat.dbo.PRIM_229_snc_avg'...
    ' WHERE year(TmStamp) = 2015' ...
    ' AND LOGGERID = 229' ...
    ' ORDER BY TmStamp ASC'];

% qry = ['SELECT PRIM_229_snc_avg.TmStamp'...
%     ' ,	PRIM_229_snc_avg.RecNum'...
%     ' ,	PRIM_229_snc_avg.LOGGERID'...
%     ' ,	PRIM_229_snc_avg.PROGID'...
%     ' ,	PRIM_229_snc_avg.Dir_mean'...
%     ' ,	PRIM_229_snc_avg.Dir_std'...
%     ' ,	PRIM_229_snc_avg.Spd_Gust_max'...
%     ' ,	PRIM_229_snc_avg.Spd_mean'...
%     ' ,	PRIM_229_snc_avg.Ux_Avg'...
%     ' ,	PRIM_229_snc_avg.Ux_Std'...
%     ' ,	PRIM_229_snc_avg.Uy_Avg'...
%     ' ,	PRIM_229_snc_avg.Uy_Std'...
%     ' , PRIM_229_snc_avg.Ts_Avg'...
%     ' ,	PRIM_229_snc_avg.Ts_Std'...
%     ' ,	PRIM_229_snc_avg.N_samples'...
%     ' ,	PRIM_229_snc_avg.N_samples_good'...
%     ' FROM 	metdat.dbo.PRIM_229_snc_avg'...
%     ' WHERE   TmStamp >= DATEADD(day, -21, GETDATE())'...
%     ' AND LOGGERID = 229' ...
%     ' ORDER BY TmStamp ASC '];

[data,msg] = sql2gceds(conn, ...
                        qry, ...
                        template, ...
                        1, ...
                        0, ...
                        1);

% %close database connection
 close(conn);



