function [data,msg] = fetch_cs2met_clrg_Table1(template)

%connect to the database
conn = database('metdat', '', '', 'Vendor', 'MICROSOFT SQL SERVER', 'Server', 'Stewartia', 'PortNumber', 1433, 'AuthType', 'Windows');

if exist('template','var') ~= 1
   template = '';
end

qry = ['SELECT CS2MET_CLRG_Table1.TmStamp'...
    ' ,	CS2MET_CLRG_Table1.RecNum'...
    ' ,	CS2MET_CLRG_Table1.GageMinV'...
    ' ,	CS2MET_CLRG_Table1.ActTemp'...
    ' ,	CS2MET_CLRG_Table1.ActDepth'...
    ' ,	CS2MET_CLRG_Table1.ActDepthRA'...
    '   FROM metdat.dbo.CS2MET_CLRG_Table1'...
    '   WHERE year(TmStamp) = 2015'...
    '   ORDER BY TmStamp ASC '];

%% Query for real-time data updates only
% qry = ['SELECT 	CS2MET_CLRG_Table1.TmStamp'...
%     ' ,	CS2MET_CLRG_Table1.RecNum'...
%     ' ,	CS2MET_CLRG_Table1.GageMinV'...
%     ' ,	CS2MET_CLRG_Table1.ActTemp'...
%     ' ,	CS2MET_CLRG_Table1.ActDepth'...
%     ' ,	CS2MET_CLRG_Table1.ActDepthRA'...
%     '     FROM 	metdat.dbo.CS2MET_CLRG_Table1'...
%     '     WHERE   TmStamp >= DATEADD(day, -180, GETDATE())'...
%     '     ORDER BY TmStamp ASC '];

[data,msg] = sql2gceds(conn, ...
                        qry, ...
                        template, ...
                        1, ...
                        0, ...
                        1);

% %close database connection
 close(conn);


