function [data,msg] = fetch_ws1_ec_avg_arch1(template)

%connect to the database
conn = database('metdat', '', '', 'Vendor', 'MICROSOFT SQL SERVER', 'Server', 'Stewartia', 'PortNumber', 1433, 'AuthType', 'Windows');

if exist('template','var') ~= 1
   template = 'LNDB_Ws1_2';
end

qry = ['SELECT hjaws1ec_avg_arch1.TmStamp'...
    ' ,	hjaws1ec_avg_arch1.RecNum'...
    ' ,	hjaws1ec_avg_arch1.CO2mmol_Avg'...
    ' ,	hjaws1ec_avg_arch1.H2Ommol_Avg'...
    ' ,	hjaws1ec_avg_arch1.press_li7500_Avg'...
    ' ,	hjaws1ec_avg_arch1.Ts_Avg'...
    ' ,	hjaws1ec_avg_arch1.Ts_csat_Avg'...
    ' ,	hjaws1ec_avg_arch1.Ux_Avg'...
    ' ,	hjaws1ec_avg_arch1.Ux_csat_Avg'...
    ' ,	hjaws1ec_avg_arch1.Uy_Avg'...
    ' ,	hjaws1ec_avg_arch1.Uy_csat_Avg'...
    ' ,	hjaws1ec_avg_arch1.Uz_Avg'...
    ' ,	hjaws1ec_avg_arch1.Uz_csat_Avg'...
    ' FROM 	metdat.dbo.hjaws1ec_avg_arch1'...
    ' ORDER BY TmStamp ASC '];

[data,msg] = sql2gceds(conn, ...
                        qry, ...
                        template, ...
                        1, ...
                        0, ...
                        1);

% %close database connection
 close(conn);


