function [data,msg] = fetch_hjaws1ec_avg_NR01(template)

%connect to the database
conn = database('metdat', '', '', 'Vendor', 'MICROSOFT SQL SERVER', 'Server', 'Stewartia', 'PortNumber', 1433, 'AuthType', 'Windows');

if exist('template','var') ~= 1
   template = 'LNDB_Ws1_EcMet_Avg_NR01';
end

% qry = ['SELECT hjaws1ec_avg_arch4.TmStamp'...
%     ' ,	hjaws1ec_avg_arch4.RecNum'...
%     ' ,	hjaws1ec_avg_arch4.SR01Up_Avg'...
%     ' ,	hjaws1ec_avg_arch4.SR01Dn_Avg'...
%     ' ,	hjaws1ec_avg_arch4.IR01UpCo_Avg'...
%     ' ,	hjaws1ec_avg_arch4.IR01DnCo_Avg'...
%     ' ,	hjaws1ec_avg_arch4.NR01TC_Avg'...
%     ' ,	hjaws1ec_avg_arch4.NetRs_Avg'...
%     ' ,	hjaws1ec_avg_arch4.NetRl_Avg'...
%     ' ,	hjaws1ec_avg_arch4.Albedo_Avg'...
%     ' ,	hjaws1ec_avg_arch4.UpTot_Avg'...
%     ' ,	hjaws1ec_avg_arch4.DnTot_Avg'...
%     ' ,	hjaws1ec_avg_arch4.NetTot_Avg'...
%     ' FROM 	metdat.dbo.hjaws1ec_avg_arch4'...
%     ' WHERE year(TmStamp) = 2013'...
%     ' ORDER BY TmStamp ASC '];

% qry = ['SELECT hjaws1ec_avg_arch5.TmStamp'...
%     ' ,	hjaws1ec_avg_arch5.RecNum'...
%     ' ,	hjaws1ec_avg_arch5.SR01Up_Avg'...
%     ' ,	hjaws1ec_avg_arch5.SR01Dn_Avg'...
%     ' ,	hjaws1ec_avg_arch5.IR01UpCo_Avg'...
%     ' ,	hjaws1ec_avg_arch5.IR01DnCo_Avg'...
%     ' ,	hjaws1ec_avg_arch5.NR01TC_Avg'...
%     ' ,	hjaws1ec_avg_arch5.NetRs_Avg'...
%     ' ,	hjaws1ec_avg_arch5.NetRl_Avg'...
%     ' ,	hjaws1ec_avg_arch5.Albedo_Avg'...
%     ' ,	hjaws1ec_avg_arch5.UpTot_Avg'...
%     ' ,	hjaws1ec_avg_arch5.DnTot_Avg'...
%     ' ,	hjaws1ec_avg_arch5.NetTot_Avg'...
%     ' FROM 	metdat.dbo.hjaws1ec_avg_arch5'...
%     ' WHERE year(TmStamp) = 2013'...
%     ' ORDER BY TmStamp ASC '];

% qry = ['SELECT hjaws1ec_avg_arch6.TmStamp'...
%     ' ,	hjaws1ec_avg_arch6.RecNum'...
%     ' ,	hjaws1ec_avg_arch6.SR01Up_Avg'...
%     ' ,	hjaws1ec_avg_arch6.SR01Dn_Avg'...
%     ' ,	hjaws1ec_avg_arch6.IR01UpCo_Avg'...
%     ' ,	hjaws1ec_avg_arch6.IR01DnCo_Avg'...
%     ' ,	hjaws1ec_avg_arch6.NR01TC_Avg'...
%     ' ,	hjaws1ec_avg_arch6.NetRs_Avg'...
%     ' ,	hjaws1ec_avg_arch6.NetRl_Avg'...
%     ' ,	hjaws1ec_avg_arch6.Albedo_Avg'...
%     ' ,	hjaws1ec_avg_arch6.UpTot_Avg'...
%     ' ,	hjaws1ec_avg_arch6.DnTot_Avg'...
%     ' ,	hjaws1ec_avg_arch6.NetTot_Avg'...
%     ' FROM 	metdat.dbo.hjaws1ec_avg_arch6'...
%     ' WHERE year(TmStamp) = 2013'...
%     ' ORDER BY TmStamp ASC '];
% 
% qry = ['SELECT hjaws1ec_avg_arch7.TmStamp'...
%     ' ,	hjaws1ec_avg_arch7.RecNum'...
%     ' ,	hjaws1ec_avg_arch7.SR01Up_Avg'...
%     ' ,	hjaws1ec_avg_arch7.SR01Dn_Avg'...
%     ' ,	hjaws1ec_avg_arch7.IR01UpCo_Avg'...
%     ' ,	hjaws1ec_avg_arch7.IR01DnCo_Avg'...
%     ' ,	hjaws1ec_avg_arch7.NR01TC_Avg'...
%     ' ,	hjaws1ec_avg_arch7.NetRs_Avg'...
%     ' ,	hjaws1ec_avg_arch7.NetRl_Avg'...
%     ' ,	hjaws1ec_avg_arch7.Albedo_Avg'...
%     ' ,	hjaws1ec_avg_arch7.UpTot_Avg'...
%     ' ,	hjaws1ec_avg_arch7.DnTot_Avg'...
%     ' ,	hjaws1ec_avg_arch7.NetTot_Avg'...
%     ' FROM 	metdat.dbo.hjaws1ec_avg_arch7'...
%     ' WHERE year(TmStamp) = 2013'...
%     ' ORDER BY TmStamp ASC '];
% 
% qry = ['SELECT hjaws1ec_avg_arch8.TmStamp'...
%     ' ,	hjaws1ec_avg_arch8.RecNum'...
%     ' ,	hjaws1ec_avg_arch8.SR01Up_Avg'...
%     ' ,	hjaws1ec_avg_arch8.SR01Dn_Avg'...
%     ' ,	hjaws1ec_avg_arch8.IR01UpCo_Avg'...
%     ' ,	hjaws1ec_avg_arch8.IR01DnCo_Avg'...
%     ' ,	hjaws1ec_avg_arch8.NR01TC_Avg'...
%     ' ,	hjaws1ec_avg_arch8.NetRs_Avg'...
%     ' ,	hjaws1ec_avg_arch8.NetRl_Avg'...
%     ' ,	hjaws1ec_avg_arch8.Albedo_Avg'...
%     ' ,	hjaws1ec_avg_arch8.UpTot_Avg'...
%     ' ,	hjaws1ec_avg_arch8.DnTot_Avg'...
%     ' ,	hjaws1ec_avg_arch8.NetTot_Avg'...
%     ' FROM 	metdat.dbo.hjaws1ec_avg_arch8'...
%     ' WHERE year(TmStamp) = 2013'...
%     ' ORDER BY TmStamp ASC '];
% 
% qry = ['SELECT hjaws1ec_avg_arch9.TmStamp'...
%     ' ,	hjaws1ec_avg_arch9.RecNum'...
%     ' ,	hjaws1ec_avg_arch9.SR01Up_Avg'...
%     ' ,	hjaws1ec_avg_arch9.SR01Dn_Avg'...
%     ' ,	hjaws1ec_avg_arch9.IR01UpCo_Avg'...
%     ' ,	hjaws1ec_avg_arch9.IR01DnCo_Avg'...
%     ' ,	hjaws1ec_avg_arch9.NR01TC_Avg'...
%     ' ,	hjaws1ec_avg_arch9.NetRs_Avg'...
%     ' ,	hjaws1ec_avg_arch9.NetRl_Avg'...
%     ' ,	hjaws1ec_avg_arch9.Albedo_Avg'...
%     ' ,	hjaws1ec_avg_arch9.UpTot_Avg'...
%     ' ,	hjaws1ec_avg_arch9.DnTot_Avg'...
%     ' ,	hjaws1ec_avg_arch9.NetTot_Avg'...
%     ' ,	hjaws1ec_avg_arch9.Baro_Pres_Avg'...
%     ' FROM 	metdat.dbo.hjaws1ec_avg_arch9'...
%     ' WHERE year(TmStamp) = 2013'...
%     ' ORDER BY TmStamp ASC '];
 
qry = ['SELECT hjaws1ec_avg.TmStamp'...
    ' ,	hjaws1ec_avg.RecNum'...
    ' ,	hjaws1ec_avg.SR01Up_Avg'...
    ' ,	hjaws1ec_avg.SR01Dn_Avg'...
    ' ,	hjaws1ec_avg.IR01UpCo_Avg'...
    ' ,	hjaws1ec_avg.IR01DnCo_Avg'...
    ' ,	hjaws1ec_avg.NR01TC_Avg'...
    ' ,	hjaws1ec_avg.NetRs_Avg'...
    ' ,	hjaws1ec_avg.NetRl_Avg'...
    ' ,	hjaws1ec_avg.Albedo_Avg'...
    ' ,	hjaws1ec_avg.UpTot_Avg'...
    ' ,	hjaws1ec_avg.DnTot_Avg'...
    ' ,	hjaws1ec_avg.NetTot_Avg'...
    ' ,	hjaws1ec_avg.Baro_Pres_Avg'...
    ' FROM 	metdat.dbo.hjaws1ec_avg'...
    ' WHERE   TmStamp >= DATEADD(day, -14, GETDATE())'...
    ' ORDER BY TmStamp ASC '];

[data,msg] = sql2gceds(conn, ...
                        qry, ...
                        template, ...
                        1, ...
                        0, ...
                        1);

% %close database connection
 close(conn);


