function [data,msg] = fetch_hagg_01_TmpCnd_MP2(template)

%connect to the database
conn = database('metdat', '', '', 'Vendor', 'MICROSOFT SQL SERVER', 'Server', 'Stewartia', 'PortNumber', 1433, 'AuthType', 'Windows');

if exist('template','var') ~= 1
   template = '';
end

% qry = ['SELECT Hagg_01_TmpCnd_MP2.TmStamp'...
%     ' ,	Hagg_01_TmpCnd_MP2.RecNum'...
%     ' ,	Hagg_01_TmpCnd_MP2.T_G1'...
%     ' ,	Hagg_01_TmpCnd_MP2.T_H2'...
%     ' ,	Hagg_01_TmpCnd_MP2.T_G3'...
%     ' ,	Hagg_01_TmpCnd_MP2.T_G4'...
%     ' ,	Hagg_01_TmpCnd_MP2.T_H4'...
%     ' ,	Hagg_01_TmpCnd_MP2.T_H3'...
%     ' ,	Hagg_01_TmpCnd_MP2.T_H5'...
%     ' ,	Hagg_01_TmpCnd_MP2.T_H6'...
%     ' ,	Hagg_01_TmpCnd_MP2.T_F6'...
%     ' ,	Hagg_01_TmpCnd_MP2.T_E7'...
%     ' ,	Hagg_01_TmpCnd_MP2.T_G2'...
%     ' ,	Hagg_01_TmpCnd_MP2.T_I2'...
%     ' ,	Hagg_01_TmpCnd_MP2.T_I3'...
%     ' ,	Hagg_01_TmpCnd_MP2.T_I4'...
%     ' ,	Hagg_01_TmpCnd_MP2.T_G5'...
%     ' ,	Hagg_01_TmpCnd_MP2.T_G6'...
%     ' ,	Hagg_01_TmpCnd_MP2.EC_G1'...
%     ' ,	Hagg_01_TmpCnd_MP2.EC_H2'...
%     ' ,	Hagg_01_TmpCnd_MP2.EC_G3'...
%     ' ,	Hagg_01_TmpCnd_MP2.EC_G4'...
%     ' ,	Hagg_01_TmpCnd_MP2.EC_H4'...
%     ' ,	Hagg_01_TmpCnd_MP2.EC_H3'...
%     ' ,	Hagg_01_TmpCnd_MP2.EC_H5'...
%     ' ,	Hagg_01_TmpCnd_MP2.EC_H6'...
%     ' ,	Hagg_01_TmpCnd_MP2.EC_F6'...
%     ' ,	Hagg_01_TmpCnd_MP2.EC_E7'...
%     ' ,	Hagg_01_TmpCnd_MP2.EC_G2'...
%     ' ,	Hagg_01_TmpCnd_MP2.EC_I2'...
%     ' ,	Hagg_01_TmpCnd_MP2.EC_I3'...
%     ' ,	Hagg_01_TmpCnd_MP2.EC_I4'...
%     ' ,	Hagg_01_TmpCnd_MP2.EC_G5'...
%     ' ,	Hagg_01_TmpCnd_MP2.EC_G6'...
%     ' FROM 	metdat.dbo.Hagg_01_TmpCnd_MP2'...
%     ' WHERE year(TmStamp) = 2015'...
%     ' ORDER BY TmStamp ASC '];

qry = ['SELECT 	Hagg_01_TmpCnd_MP2.TmStamp'...
    ' ,	Hagg_01_TmpCnd_MP2.RecNum'...
    ' ,	Hagg_01_TmpCnd_MP2.T_G1'...
    ' ,	Hagg_01_TmpCnd_MP2.T_H2'...
    ' ,	Hagg_01_TmpCnd_MP2.T_G3'...
    ' ,	Hagg_01_TmpCnd_MP2.T_G4'...
    ' ,	Hagg_01_TmpCnd_MP2.T_H4'...
    ' ,	Hagg_01_TmpCnd_MP2.T_H3'...
    ' ,	Hagg_01_TmpCnd_MP2.T_H5'...
    ' ,	Hagg_01_TmpCnd_MP2.T_H6'...
    ' ,	Hagg_01_TmpCnd_MP2.T_F6'...
    ' ,	Hagg_01_TmpCnd_MP2.T_E7'...
    ' ,	Hagg_01_TmpCnd_MP2.T_G2'...
    ' ,	Hagg_01_TmpCnd_MP2.T_I2'...
    ' ,	Hagg_01_TmpCnd_MP2.T_I3'...
    ' ,	Hagg_01_TmpCnd_MP2.T_I4'...
    ' ,	Hagg_01_TmpCnd_MP2.T_G5'...
    ' ,	Hagg_01_TmpCnd_MP2.T_G6'...
    ' ,	Hagg_01_TmpCnd_MP2.EC_G1'...
    ' ,	Hagg_01_TmpCnd_MP2.EC_H2'...
    ' ,	Hagg_01_TmpCnd_MP2.EC_G3'...
    ' ,	Hagg_01_TmpCnd_MP2.EC_G4'...
    ' ,	Hagg_01_TmpCnd_MP2.EC_H4'...
    ' ,	Hagg_01_TmpCnd_MP2.EC_H3'...
    ' ,	Hagg_01_TmpCnd_MP2.EC_H5'...
    ' ,	Hagg_01_TmpCnd_MP2.EC_H6'...
    ' ,	Hagg_01_TmpCnd_MP2.EC_F6'...
    ' ,	Hagg_01_TmpCnd_MP2.EC_E7'...
    ' ,	Hagg_01_TmpCnd_MP2.EC_G2'...
    ' ,	Hagg_01_TmpCnd_MP2.EC_I2'...
    ' ,	Hagg_01_TmpCnd_MP2.EC_I3'...
    ' ,	Hagg_01_TmpCnd_MP2.EC_I4'...
    ' ,	Hagg_01_TmpCnd_MP2.EC_G5'...
    ' ,	Hagg_01_TmpCnd_MP2.EC_G6'...
    ' FROM 	metdat.dbo.Hagg_01_TmpCnd_MP2'...
   ' WHERE   TmStamp >= DATEADD(day, -21, GETDATE())'...
   ' ORDER BY TmStamp ASC '];

[data,msg] = sql2gceds(conn, ...
                        qry, ...
                        template, ...
                        1, ...
                        0, ...
                        1);

% %close database connection
 close(conn);



