function editnote(op,h)
%Dialog for adding or editing text annotations on figures. Can be called without arguments to
%create and place an annotation and used as the 'ButtonDownFcn' callback for editing text objects.
%
%syntax:  editnote(op,h)
%
%input:
%  op = operation (default = 'init' to initialize dialog)
%  h = handle of text object to edit (default = gcbo)
%
%output:
%  none
%
%(c)2002-2006 Wade M. Sheldon and the Georgia Coastal Ecosystems LTER Project
%
%This file is part of the GCE Data Toolbox for MATLAB(r) software library.
%
%The GCE Data Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The GCE Data Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The GCE Data Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%
%contact:
%  Wade Sheldon
%  GCE-LTER Project
%  Department of Marine Sciences
%  University of Georgia
%  Athens, GA 30602-3636
%  sheldon@uga.edu
%
%last modified: 09-May-2005

if exist('op','var') ~= 1
   op = 'init';
end

if strcmp(op,'init')
   
   h_dlg = findobj('Tag','dlgTextEdit');
   if ~isempty(h_dlg)
      close(h_dlg)
   end
   
   if exist('h','var') ~= 1
      h_cbo = gcbo;
   else
      h_cbo = h;
   end

   if ~isempty(h_cbo)
      objtype = get(h_cbo,'Type');
   else
      objtype = 'none';
   end
   
   tempflag = 0;  %init temp text flag
   
   if strcmp(lower(objtype),'text')
      
      ud = get(h_cbo,'UserData');
      if ischar(ud)
         if strcmp(ud,'temp')
            tempflag = 1;
            set(h_cbo,'UserData',[])  %clear temp flag
         end
      end
            
      flds = {'String','Position','FontName','FontUnits','FontSize','FontWeight','FontAngle','Color', ...
            'Rotation','HorizontalAlignment','VerticalAlignment','Interpreter'};
      properties = cell2struct(cell(length(flds),1),flds');
      for n = 1:length(flds)
         properties = setfield(properties,flds{n},get(h_cbo,flds{n}));
      end
      
      str = properties.String;
      pos = properties.Position;
      fontname = properties.FontName;
      fontunits = properties.FontUnits;
      fontsize = properties.FontSize;
      fontweight = properties.FontWeight;
      fontangle = properties.FontAngle;
      fontcolor = properties.Color;
      fontrotate = properties.Rotation;
      halign = properties.HorizontalAlignment;
      valign = properties.VerticalAlignment;
      interpreter = properties.Interpreter;
      
   else
      
      h_cbo = [];  %reset handle so new text object will be created
      properties = [];
      str = '';
      pos = [0 0 0];
      fontname = 'Helvetica';
      fontunits = 'points';
      fontsize = 10;
      fontweight = 'normal';
      fontangle = 'normal';
      fontcolor = [0 0 1];
      fontrotate = 0;
      halign = 'center';
      valign = 'middle';
      interpreter = 'none';
      
   end
   
   xpos = num2str(pos(1));
   ypos = num2str(pos(2));
   zpos = num2str(pos(3));
   
   switch halign
      case 'center'
         halign_val = 2;
      case 'right'
         halign_val = 3;
      otherwise
         halign_val = 1;
   end
   
   switch valign
      case 'middle'
         valign_val = 2;
      case 'bottom'
         valign_val = 3;
      case 'baseline'
         valign_val = 4;
      otherwise
         valign_val = 1;
   end
   
   if sum(fontcolor == [1 1 1]) < 3  %non-white text
      backcolor = [1 1 1];
   else
      backcolor = [.6 .6 .6];
   end
   
   if strcmp(interpreter,'tex')
      texval = 1;
   else
      texval = 0;
   end
   
   %get figure position
   if ~isempty(h_cbo)
      h_fig = parent_figure(h_cbo);
   else
      h_fig = gcf;
   end
   figpos = get(h_fig,'Position');
   
   res = get(0,'ScreenSize');
   bgcolor = [.9 .9 .9];
   
   h_dlg = figure('Units','pixels', ...
      'Visible','off', ...
      'Color',bgcolor, ...
      'KeyPressFcn','figure(gcf)', ...
      'MenuBar','none', ...
      'Name','Add/Edit Annotation', ...
      'NumberTitle','off', ...
      'Position',[max(10,figpos(1)-50),min(res(4)-250,figpos(2)+figpos(4)-100),540,210], ...
      'Tag','dlgTextEdit', ...
      'DefaultUiControlUnits','pixels', ...
      'CloseRequestFcn','editnote(''cancel'')', ...
      'UserData',gcf);
   
   h1 = uicontrol('Parent',h_dlg, ...
      'Style','frame', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',bgcolor, ...
      'Position',[1 1 540 210]);
   
   h1 = uicontrol('Parent',h_dlg, ...
      'Style','edit', ...
      'HorizontalAlignment','left', ...
      'BackgroundColor',backcolor, ...
      'ForegroundColor',fontcolor, ...
      'FontName',fontname, ...
      'FontUnits',fontunits, ...
      'FontSize',fontsize, ...
      'FontWeight',fontweight, ...
      'FontAngle',fontangle, ...
      'Max',5, ...
      'Min',1, ...
      'Position',[10 100 400 100], ...
      'String',str, ...
      'Callback','editnote(''update'')', ...
      'Tag','EditBox', ...
      'UserData',h_cbo);
   
   h1 = uicontrol('Parent',h_dlg, ...
      'Style','text', ...
      'BackgroundColor',bgcolor, ...
      'Position',[410 170 40 18], ...
      'String','X Pos', ...
      'Tag','lblX');
   
   h1 = uicontrol('Parent',h_dlg, ...
      'Style','edit', ...
      'BackgroundColor',[1 1 1], ...
      'Position',[450 170 80 22], ...
      'String',xpos, ...
      'Callback','editnote(''update'')', ...
      'Tag','xpos', ...
      'UserData',pos(1));
   
   h1 = uicontrol('Parent',h_dlg, ...
      'Style','text', ...
      'BackgroundColor',bgcolor, ...
      'Position',[410 140 40 18], ...
      'String','Y Pos', ...
      'Tag','lblY');
   
   h1 = uicontrol('Parent',h_dlg, ...
      'Style','edit', ...
      'BackgroundColor',[1 1 1], ...
      'Position',[450 140 80 22], ...
      'String',ypos, ...
      'Callback','editnote(''update'')', ...
      'Tag','ypos', ...
      'UserData',pos(2));
   
   h1 = uicontrol('Parent',h_dlg, ...
      'Style','text', ...
      'BackgroundColor',bgcolor, ...
      'Position',[410 110 40 18], ...
      'String','Z Pos', ...
      'Tag','lblZ');
   
   h1 = uicontrol('Parent',h_dlg, ...
      'Style','edit', ...
      'BackgroundColor',[1 1 1], ...
      'Position',[450 110 80 22], ...
      'String',zpos, ...
      'Callback','editnote(''update'')', ...
      'Tag','zpos', ...
      'UserData',pos(3));
   
   h1 = uicontrol('Parent',h_dlg, ...
      'Style','push', ...
      'Position',[450 80 80 25], ...
      'String','Use Mouse', ...
      'Callback','editnote(''mouse'')', ...
      'Tag','mouse');
   
   h1 = uicontrol('Parent',h_dlg, ...
      'Callback','editnote(''font'')', ...
      'Position',[10 70 60 25], ...
      'String','Text Font', ...
      'Tag','font');
   
   h1 = uicontrol('Parent',h_dlg, ...
      'Callback','editnote(''color'')', ...
      'Position',[75 70 60 25], ...
      'String','Text Color', ...
      'Tag','color');
   
   h1 = uicontrol('Parent',h_dlg, ...
      'Style','text', ...
      'BackgroundColor',bgcolor, ...
      'HorizontalAlignment','right', ...
      'Position',[142 71 55 18], ...
      'String','Horizontal', ...
      'Tag','lblHor');
   
   h1 = uicontrol('Parent',h_dlg, ...
      'Position',[202 69 95 24], ...
      'BackgroundColor',[1 1 1], ...
      'String',['Left-Aligned ';'Centered     ';'Right-Aligned'], ...
      'Style','popupmenu', ...
      'Callback','editnote(''update'')', ...
      'Tag','h_align', ...
      'Value',halign_val);
   
   h1 = uicontrol('Parent',h_dlg, ...
      'Style','text', ...
      'BackgroundColor',bgcolor, ...
      'HorizontalAlignment','right', ...
      'Position',[142 45 55 18], ...
      'String','Vertical', ...
      'Tag','lblVert');
   
   h1 = uicontrol('Parent',h_dlg, ...
      'Position',[202 43 95 24], ...
      'BackgroundColor',[1 1 1], ...
      'String',['Top     ';'Middle  ';'Bottom  ';'Baseline'], ...
      'Style','popupmenu', ...
      'Callback','editnote(''update'')', ...
      'Tag','v_align', ...
      'Value',valign_val);
   
   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'HorizontalAlignment','right', ...
      'Position',[310 75 30 15], ...
      'String','TeX', ...
      'Style','text', ...
      'Tag','lblTeX');
   
   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'Position',[355 73 12 19], ...
      'Style','checkbox', ...
      'Value',texval, ...
      'Callback','editnote(''update'')', ...
      'Tag','texval');
   
   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'HorizontalAlignment','right', ...
      'Position',[300 48 50 15], ...
      'String','Rotation', ...
      'Style','text', ...
      'Tag','lblRotation');
   
   h1 = uicontrol('Parent',h_dlg, ...
      'Position',[355 46 55 22], ...
      'Style','edit', ...
      'BackgroundColor',[1 1 1], ...
      'String',num2str(fontrotate), ...
      'Callback','editnote(''update'')', ...
      'Tag','rotate');
   
   h1 = uicontrol('Parent',h_dlg, ...
      'Callback','editnote(''cancel'')', ...
      'Position',[10 7 60 25], ...
      'String','Cancel', ...
      'UserData',properties, ...
      'Tag','cancel');
   
   h1 = uicontrol('Parent',h_dlg, ...
      'Callback','editnote(''delete'')', ...
      'Position',[75 7 60 25], ...
      'String','Delete', ...
      'UserData',tempflag, ...
      'Tag','delete');
   
   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'Style','checkbox', ...
      'String','Preview changes automatically', ...
      'Position',[200 7 200 20], ...
      'Value',1, ...
      'Callback','editnote(''auto'')', ...
      'Tag','auto');
   
   h1 = uicontrol('Parent',h_dlg, ...
      'Callback','editnote(''preview'')', ...
      'Position',[407 7 60 25], ...
      'String','Preview', ...
      'Tag','preview');
   
   h1 = uicontrol('Parent',h_dlg, ...
      'Callback','editnote(''eval'')', ...
      'Position',[472 7 60 25], ...
      'String','Accept', ...
      'UserData',1, ...
      'Tag','accept');
   
   set(h_dlg,'Visible','on')
   
else
   
   h_dlg = findobj('Tag','dlgTextEdit');
   h_fig = get(h_dlg,'UserData');
   h_edit = findobj(h_dlg,'Tag','EditBox');
   h_cbo = get(h_edit,'UserData');
   h_eval = findobj(h_dlg,'Tag','accept');
   preview = get(h_eval,'UserData');
   
   if strcmp(op,'cancel')
      
      properties = get(findobj(h_dlg,'Tag','cancel'),'UserData');
      tempflag = get(findobj(h_dlg,'Tag','delete'),'UserData');
      delete(h_dlg)
      figure(h_fig)
      
      %reset object position in case moved with the mouse
      if ~isempty(properties)
         if tempflag == 0
            flds = fieldnames(properties);
            for n = 1:length(flds)
               set(h_cbo,flds{n},getfield(properties,flds{n}))
            end
         else
            delete(h_cbo)  %delete placeholder text object on cancel
         end
      elseif ~isempty(h_cbo)
         delete(h_cbo)  %delete de novo text object on cancel
      end
      
      refresh(h_fig)
      
   elseif strcmp(op,'delete')  %delete object
      
      delete(h_dlg)
      figure(h_fig)
      if ~isempty(h_cbo)
         delete(h_cbo)
         refresh(h_fig)
      end
      
   elseif strcmp(op,'eval')  %accept changes and close dialog
      
      str = get(h_edit,'String');
      if ~isempty(str)
         set(h_eval,'UserData',1)  %force preview flag
         editnote('update')
      else
         if ~isempty(h_cbo)
            delete(h_cbo)
            refresh(h_fig)
         end
      end
      
      delete(h_dlg)
      figure(h_fig)
      
   elseif strcmp(op,'preview')
      
      last_preview = preview;  %buffer preview setting
      
      set(h_eval,'UserData',1)  %force preview flag
      editnote('update')
      set(h_eval,'UserData',last_preview)  %reset preview flag
            
   elseif strcmp(op,'auto')  %set preview flag according to checkbox value
      
      preview = get(findobj(h_dlg,'Tag','auto'),'Value');
      set(h_eval,'UserData',preview)
      
      if preview == 1
         editnote('update')  %update any pending changes
      end
      
   elseif strcmp(op,'font')
      
      uisetfont(h_edit,'Font Attributes');
      
      editnote('update')
      
   elseif strcmp(op,'color')
      
      uisetcolor(h_edit,'Font Color');
      fgclr = get(h_edit,'ForegroundColor');
      bgclr = get(h_edit,'BackgroundColor');
      
      if sum(fgclr == bgclr) == 3
         if sum(bgclr) == 3
            set(h_edit,'BackgroundColor',[.6 .6 .6])
         else
            set(h_edit,'BackgorundColor',[1 1 1])
         end
      end
      
      editnote('update')
      
   elseif strcmp(op,'mouse')
      
      figure(h_fig)
      refresh(h_fig)
      fcn = get(h_fig,'WindowButtonDownFcn');  %buffer mouse fcn
      set(h_fig,'WindowButtonDownFcn','')  %clear fcn
      
      [x,y,button] = ginput(1);
      
      set(h_fig,'WindowButtonDownFcn',fcn)  %restore fcn
      
      if button == 1
         h_x = findobj(h_dlg,'Tag','xpos');
         h_y = findobj(h_dlg,'Tag','ypos');
         set(h_x,'String',num2str(x));
         set(h_y,'String',num2str(y));
      end

      refresh(h_fig)
      figure(h_dlg)
      
      editnote('update')
      
   elseif strcmp(op,'update')  %apply all selections
      
      if preview == 1
         
         hopt = [{'left'},{'center'},{'right'}];
         vopt = [{'top'},{'middle'},{'bottom'},{'baseline'}];
         
         str = get(h_edit,'String');
         fontname = get(h_edit,'FontName');
         fontunits = get(h_edit,'FontUnits');
         fontsize = get(h_edit,'FontSize');
         fontweight = get(h_edit,'FontWeight');
         fontangle = get(h_edit,'FontAngle');
         fontcolor = get(h_edit,'ForegroundColor');
         
         h_rotate = findobj(h_dlg,'Tag','rotate');
         rotatestr = get(h_rotate,'String');
         fontrotate = 0;
         if ~isempty(rotatestr)
            fontrotate = str2num(rotatestr);
         end
         
         h_interp = findobj(h_dlg,'Tag','texval');
         texval = get(h_interp,'Value');
         if texval == 1
            interpreter = 'tex';
         else
            interpreter = 'none';
         end
         
         h_align = findobj(h_dlg,'Tag','h_align');
         halignstr = hopt{get(h_align,'Value')};
         
         v_align = findobj(h_dlg,'Tag','v_align');
         valignstr = vopt{get(v_align,'Value')};
         
         h_xpos = findobj(h_dlg,'Tag','xpos');
         xpos = str2num(get(h_xpos,'String'));
         if isempty(xpos)
            xpos = get(h_xpos,'UserData');
         end
         
         h_ypos = findobj(h_dlg,'Tag','ypos');
         ypos = str2num(get(h_ypos,'String'));
         if isempty(ypos)
            ypos = get(h_ypos,'UserData')
         end
         
         h_zpos = findobj(h_dlg,'Tag','zpos');
         zpos = str2num(get(h_zpos,'String'));
         if isempty(zpos)
            zpos = get(h_zpos,'UserData');
         end

         if ~isempty(h_cbo)
            set(h_cbo, ...
               'String',str, ...
               'Position',[xpos,ypos,zpos], ...
               'FontName',fontname, ...
               'FontUnits',fontunits, ...
               'FontSize',fontsize, ...
               'FontWeight',fontweight, ...
               'FontAngle',fontangle, ...
               'Color',fontcolor, ...
               'HorizontalAlignment',halignstr, ...
               'VerticalAlignment',valignstr, ...
               'Rotation',fontrotate, ...
               'Interpreter',interpreter)
         elseif xpos ~= 0 & ypos ~= 0  %create text object if valid position specified
            figure(h_fig)
            h_cbo = text(xpos,ypos,zpos,str);
            figure(h_dlg)
            set(h_cbo, ...
               'FontName',fontname, ...
               'FontUnits',fontunits, ...
               'FontSize',fontsize, ...
               'FontWeight',fontweight, ...
               'FontAngle',fontangle, ...
               'Color',fontcolor, ...
               'HorizontalAlignment',halignstr, ...
               'VerticalAlignment',valignstr, ...
               'Rotation',fontrotate, ...
               'Interpreter',interpreter, ...
               'ButtonDownFcn','editnote');
            set(h_edit,'UserData',h_cbo)
         end
         
      end
      
   end
   
end
