function addsites(polydata,h)
%Adds site boundary polygon data to a map plot for use with 'poly_mgr'
%
%syntax: addsites(polydata,h)
%
%input:
%  polydata = structure containing polygon data generated by 'poly_mgr'
%     (default = file 'gce_sites.ply')
%  h = handle of the map figure (default = gcf)
%
%
%(c)2004-2010 by Wade Sheldon
%
%This file is part of the GCE Data Toolbox for MATLAB(r) software library.
%
%The GCE Data Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The GCE Data Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The GCE Data Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%Department of Marine Sciences
%University of Georgia
%Athens, Georgia  30602-3636
%sheldon@uga.edu
%
%last modified: 16-Sep-2010

error = 0;

if exist('h') ~= 1
   h = gcf;
end

if exist('polydata') ~= 1
   polydata = [];
   if exist('gce_sites.ply','file') == 2
      vars = load('gce_sites.ply');
      if isfield(vars,'polydata')
         polydata = vars.polydata;
      end
   end
end

if isstruct(polydata) & ~isempty(polydata)

   h_poly = findobj(h,'Tag','mnuPolygons');

   if ~isempty(h_poly)
      set(h_poly,'UserData',polydata)
   end

end


