function labeledit(op,h)
%Text editing dialog box, to be used as a callback function associated with text objects.
%
%syntax:  labeledit(op,h)
%
%input:
%  op = operation (default = 'init' to initialize the dialog)
%  h = object handle (default = gcbo)
%
%output:
%  none
%
%(c)2002,2003,2004 Wade M. Sheldon and the Georgia Coastal Ecosystems LTER Project
%
%This file is part of the GCE Data Toolbox for MATLAB(r) software library.
%
%The GCE Data Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The GCE Data Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The GCE Data Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%
%contact:
%  Wade Sheldon
%  GCE-LTER Project
%  Department of Marine Sciences
%  University of Georgia
%  Athens, GA 30602-3636
%  sheldon@uga.edu
%
%last modified: 14-Nov-1999

if ~exist('op')
   op = 'init';
end

if strcmp(op,'init')

   h_dlg = findobj('Tag','dlgLabelEdit');
   if ~isempty(h_dlg)
      close(h_dlg)
   end

   if ~exist('h')
      h_cbo = gcbo;
   else
      h_cbo = h;
   end

   objtype = get(h_cbo,'Type');

   if strcmp(lower(objtype),'text')
      str = get(h_cbo,'String');
      pos = get(h_cbo,'Position');
      fontname = get(h_cbo,'FontName');
      fontunits = get(h_cbo,'FontUnits');
      fontsize = get(h_cbo,'FontSize');
      fontweight = get(h_cbo,'FontWeight');
      fontangle = get(h_cbo,'FontAngle');
      fontcolor = get(h_cbo,'Color');
      fontrotate = get(h_cbo,'Rotation');
      halign = get(h_cbo,'HorizontalAlignment');
      valign = get(h_cbo,'VerticalAlignment');
      interpreter = get(h_cbo,'Interpreter');
   else
      str = '';
      pos = [0 0 0];
      fontname = 'Helvetica';
      fontunits = 'points';
      fontsize = 10;
      fontweight = 'normal';
      fontangle = 'normal';
      fontcolor = [0 0 0];
      fontrotate = 0;
      halign = 'left';
      valign = 'middle';
      interpreter = 'none';
   end

   xpos = num2str(pos(1));
   ypos = num2str(pos(2));
   zpos = num2str(pos(3));

   switch halign
   case 'center'
      halign_val = 2;
   case 'right'
      halign_val = 3;
   otherwise
      halign_val = 1;
   end

   switch valign
   case 'middle'
      valign_val = 2;
   case 'bottom'
      valign_val = 3;
   case 'baseline'
      valign_val = 4;
   otherwise
      valign_val = 1;
   end

   if fontcolor ~= [1 1 1]
      backcolor = [1 1 1];
   else
      backcolor = [.6 .6 .6];
   end

   if strcmp(interpreter,'tex')
      texval = 1;
   else
      texval = 0;
   end

   res = get(0,'ScreenSize');
   bgcolor = [.8 .8 .8];

   h_dlg = figure('Units','pixels', ...
      'Visible','off', ...
      'Color',bgcolor, ...
      'KeyPressFcn','figure(gcf)', ...
      'MenuBar','none', ...
      'Name','Edit Text', ...
      'NumberTitle','off', ...
      'Position',[max(0,(res(3)-540).*0.5),max(50,(res(4)-200).*0.5),540,200], ...
      'Tag','dlgLabelEdit', ...
      'DefaultUiControlUnits','pixels', ...
      'UserData',gcf);

   h1 = uicontrol('Parent',h_dlg, ...
      'Style','edit', ...
      'HorizontalAlignment','left', ...
      'BackgroundColor',backcolor, ...
      'ForegroundColor',fontcolor, ...
      'FontName',fontname, ...
      'FontUnits',fontunits, ...
      'FontSize',fontsize, ...
      'FontWeight',fontweight, ...
      'FontAngle',fontangle, ...
      'Max',5, ...
      'Min',1, ...
      'Position',[10 90 400 100], ...
      'String',str, ...
      'Tag','EditBox', ...
      'UserData',h_cbo);

   h1 = uicontrol('Parent',h_dlg, ...
      'Style','text', ...
      'BackgroundColor',bgcolor, ...
      'Position',[410 160 40 18], ...
      'String','X Pos', ...
      'Tag','lblX');

   h1 = uicontrol('Parent',h_dlg, ...
      'Style','edit', ...
      'BackgroundColor',[1 1 1], ...
      'Position',[450 160 80 22], ...
      'String',xpos, ...
      'Tag','xpos', ...
      'UserData',pos(1));

   h1 = uicontrol('Parent',h_dlg, ...
      'Style','text', ...
      'BackgroundColor',bgcolor, ...
      'Position',[410 130 40 18], ...
      'String','Y Pos', ...
      'Tag','lblY');

   h1 = uicontrol('Parent',h_dlg, ...
      'Style','edit', ...
      'BackgroundColor',[1 1 1], ...
      'Position',[450 130 80 22], ...
      'String',ypos, ...
      'Tag','ypos', ...
      'UserData',pos(2));

   h1 = uicontrol('Parent',h_dlg, ...
      'Style','text', ...
      'BackgroundColor',bgcolor, ...
      'Position',[410 100 40 18], ...
      'String','Z Pos', ...
      'Tag','lblZ');

   h1 = uicontrol('Parent',h_dlg, ...
      'Style','edit', ...
      'BackgroundColor',[1 1 1], ...
      'Position',[450 100 80 22], ...
      'String',zpos, ...
      'Tag','zpos', ...
      'UserData',pos(3));

   h1 = uicontrol('Parent',h_dlg, ...
      'Style','push', ...
      'Position',[450 70 80 25], ...
      'String','Use Mouse', ...
      'Callback','labeledit(''mouse'')', ...
      'Tag','mouse');

   h1 = uicontrol('Parent',h_dlg, ...
      'Callback','labeledit(''font'')', ...
      'Position',[10 60 60 25], ...
      'String','Edit Font', ...
      'Tag','font');

   h1 = uicontrol('Parent',h_dlg, ...
      'Callback','labeledit(''color'')', ...
      'Position',[80 60 60 25], ...
      'String','Edit Color', ...
      'Tag','color');

   h1 = uicontrol('Parent',h_dlg, ...
      'Style','text', ...
      'BackgroundColor',bgcolor, ...
      'HorizontalAlignment','right', ...
      'Position',[142 61 55 18], ...
      'String','Horizontal', ...
      'Tag','lblHor');

   h1 = uicontrol('Parent',h_dlg, ...
      'Position',[202 59 95 24], ...
      'BackgroundColor',[1 1 1], ...
      'String',['Left-Aligned ';'Centered     ';'Right-Aligned'], ...
      'Style','popupmenu', ...
      'Tag','h_align', ...
      'Value',halign_val);

   h1 = uicontrol('Parent',h_dlg, ...
      'Style','text', ...
      'BackgroundColor',bgcolor, ...
      'HorizontalAlignment','right', ...
      'Position',[142 35 55 18], ...
      'String','Vertical', ...
      'Tag','lblVert');

   h1 = uicontrol('Parent',h_dlg, ...
      'Position',[202 33 95 24], ...
      'BackgroundColor',[1 1 1], ...
      'String',['Top     ';'Middle  ';'Bottom  ';'Baseline'], ...
      'Style','popupmenu', ...
      'Tag','v_align', ...
      'Value',valign_val);

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'HorizontalAlignment','right', ...
      'Position',[310 65 30 15], ...
      'String','TeX', ...
      'Style','text', ...
      'Tag','lblTeX');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'Position',[355 63 12 19], ...
      'Style','checkbox', ...
      'Value',texval, ...
      'Tag','texval');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'HorizontalAlignment','right', ...
      'Position',[300 38 50 15], ...
      'String','Rotation', ...
      'Style','text', ...
      'Tag','lblRotation');

   h1 = uicontrol('Parent',h_dlg, ...
      'Position',[355 36 55 22], ...
      'Style','edit', ...
      'BackgroundColor',[1 1 1], ...
      'String',num2str(fontrotate), ...
      'Tag','rotate');

   h1 = uicontrol('Parent',h_dlg, ...
      'Callback','labeledit(''cancel'')', ...
      'Position',[5 5 60 25], ...
      'String','Cancel', ...
      'Tag','cancel');

   h1 = uicontrol('Parent',h_dlg, ...
      'Callback','labeledit(''eval'')', ...
      'Position',[475 5 60 25], ...
      'String','Apply', ...
      'Tag','accept');

   set(h_dlg,'Visible','on')

else

   h_dialog = findobj('Tag','dlgLabelEdit');
   h_fig = get(h_dialog,'UserData');
   h_edit = findobj(h_dialog,'Tag','EditBox');

   if strcmp(op,'cancel')

      close(h_dialog)
      figure(h_fig)

   elseif strcmp(op,'font')

      uisetfont(h_edit,'Font Attributes');

   elseif strcmp(op,'color')

      uisetcolor(h_edit,'Font Color');

   elseif strcmp(op,'mouse')

      figure(h_fig)
      refresh(h_fig)
      [x,y,button] = ginput(1);
      refresh(h_fig)
      figure(h_dialog)

      if button == 1
         h_x = findobj(h_dialog,'Tag','xpos');
         h_y = findobj(h_dialog,'Tag','ypos');
         set(h_x,'String',num2str(x));
         set(h_y,'String',num2str(y));
         drawnow
      end

   elseif strcmp(op,'eval')

      hopt = [{'left'},{'center'},{'right'}];
      vopt = [{'top'},{'middle'},{'bottom'},{'baseline'}];

      str = get(h_edit,'String');
      fontname = get(h_edit,'FontName');
      fontunits = get(h_edit,'FontUnits');
      fontsize = get(h_edit,'FontSize');
      fontweight = get(h_edit,'FontWeight');
      fontangle = get(h_edit,'FontAngle');
      fontcolor = get(h_edit,'ForegroundColor');

      h_rotate = findobj(h_dialog,'Tag','rotate');
      rotatestr = get(h_rotate,'String');
      fontrotate = 0;
      if ~isempty(rotatestr)
         fontrotate = str2num(rotatestr);
      end

      h_interp = findobj(h_dialog,'Tag','texval');
      texval = get(h_interp,'Value');
      if texval == 1
         interpreter = 'tex';
      else
         interpreter = 'none';
      end

      h_align = findobj(h_dialog,'Tag','h_align');
      halignstr = hopt{get(h_align,'Value')};

      v_align = findobj(h_dialog,'Tag','v_align');
      valignstr = vopt{get(v_align,'Value')};

      h_xpos = findobj(h_dialog,'Tag','xpos');
      xpos = str2num(get(h_xpos,'String'));
      if isempty(xpos)
         xpos = get(h_xpos,'UserData');
      end

      h_ypos = findobj(h_dialog,'Tag','ypos');
      ypos = str2num(get(h_ypos,'String'));
      if isempty(ypos)
         ypos = get(h_ypos,'UserData')
      end

      h_zpos = findobj(h_dialog,'Tag','zpos');
      zpos = str2num(get(h_zpos,'String'));
      if isempty(zpos)
         zpos = get(h_zpos,'UserData');
      end

      h_cbo = get(h_edit,'UserData');

      set(h_cbo, ...
         'String',str, ...
         'Position',[xpos,ypos,zpos], ...
         'FontName',fontname, ...
         'FontUnits',fontunits, ...
         'FontSize',fontsize, ...
         'FontWeight',fontweight, ...
         'FontAngle',fontangle, ...
         'Color',fontcolor, ...
         'HorizontalAlignment',halignstr, ...
         'VerticalAlignment',valignstr, ...
         'Rotation',fontrotate, ...
         'Interpreter',interpreter);

      close(h_dialog)
      figure(h_fig)
      refresh(h_fig)

   end

end
