function mapaxis(op)
%Axis limits dialog box for map plots
%
%syntax: mapaxis
%
%
%(c)2002,2003,2004 Wade M. Sheldon and the Georgia Coastal Ecosystems LTER Project
%
%This file is part of the GCE Data Toolbox for MATLAB(r) software library.
%
%The GCE Data Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The GCE Data Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The GCE Data Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%
%contact:
%  Wade Sheldon
%  GCE-LTER Project
%  Department of Marine Sciences
%  University of Georgia
%  Athens, GA 30602-3636
%  sheldon@uga.edu
%
%last modified 22-Jun-2002

if nargin == 0

   %clear prior instances of dialog
   h_dlg = findobj('Tag','mapaxis');
   if ~isempty(h_dlg)
      close(h_dlg)
   end

   h = gcf;
   h_ax = gca;

   %get tick type
   if strcmp(get(h_ax,'Tag'),'mapplot')
      axistype = get(h_ax,'UserData');
   else  %use default
      axistype = 'degmin';
   end

   switch axistype
   case 'utm'
      ticktype = 1;
   case 'none'
      ticktype = 1;
   case 'decdeg'
      ticktype = 2;
   otherwise
      ticktype = 3;
   end

   %get x axis settings
   h_xlbl = get(h_ax,'XLabel');
   xlblstr = get(h_xlbl,'String');
   xlims = get(h_ax,'XLim');
   xtick = get(h_ax,'XTick');
   if length(xtick) < 2
      if ~isempty(xtick)
         xtick = [xtick xtick];
      else
         xtick = xlims;
      end
   end

   %get y axis settings
   h_ylbl = get(h_ax,'YLabel');
   ylblstr = get(h_ylbl,'String');
   ylims = get(h_ax,'YLim');
   ytick = get(h_ax,'YTick');
   if length(ytick) < 2
      if ~isempty(ytick)
         ytick = [ytick ytick];
      else
         ytick = ylims;
      end
   end

   %check for previously rotated y-ticks
   h_rotyticks = findobj(gca,'tag','yticklabelstring');
   if ~isempty(h_rotyticks)
      rotate = 1;
   else
      rotate = 0;
   end

   axlims = [xlims xtick(1) xtick(2)-xtick(1) ...
         ylims ytick(1) ytick(2)-ytick(1)];

   axlimstr = cell(1,8);
   if ticktype < 3
      for n = 1:length(axlims)
         axlimstr{n} = num2str(abs(axlims(n)));
      end
   else
      for n = 1:length(axlims)
         axlimstr{n} = char([int2str(fix(abs(axlims(n)))) '  ' ...
               num2str((abs(axlims(n))-fix(abs(axlims(n)))).*60)]);
      end
   end

   res = get(0,'ScreenSize');

   h_dlg = figure( ...
      'Visible','off', ...
      'Name','Axis Properties', ...
      'Units','pixels', ...
      'Position',[(res(3)-440).*0.5 (res(4)-160).*0.5 440 160], ...
      'DefaultUiControlUnits','pixels', ...
      'MenuBar','none', ...
      'ToolBar','none', ...
      'Resize','off', ...
      'NumberTitle','off', ...
      'Tag','mapaxis');

   colorspec = get(h_dlg,'Color');

   uicontrol(h_dlg, ...
      'Style','text', ...
      'Position',[10 130 80 18], ...
      'String','Tick Format', ...
      'HorizontalAlignment','center', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',colorspec);

   uicontrol(h_dlg, ...
      'Style','text', ...
      'Position',[90 95 80 18], ...
      'String','Min', ...
      'HorizontalAlignment','center', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',colorspec);

   uicontrol(h_dlg, ...
      'Style','text', ...
      'Position',[175 95 80 18], ...
      'String','Max', ...
      'HorizontalAlignment','center', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',colorspec);

   uicontrol(h_dlg, ...
      'Style','text', ...
      'Position',[260 95 80 18], ...
      'String','Start', ...
      'HorizontalAlignment','center', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',colorspec);

   uicontrol(h_dlg, ...
      'Style','text', ...
      'Position',[345 95 80 18], ...
      'String','Interval', ...
      'HorizontalAlignment','center', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',colorspec);

   uicontrol(h_dlg, ...
      'Style','text', ...
      'Position',[10 75 80 18], ...
      'String',xlblstr, ...
      'HorizontalAlignment','center', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',colorspec);

   uicontrol(h_dlg, ...
      'Style','text', ...
      'Position',[10 45 80 18], ...
      'String',ylblstr, ...
      'HorizontalAlignment','center', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',colorspec);

   h_ticktype = uicontrol(h_dlg, ...
      'Style','popup', ...
      'Position',[90 132 180 18], ...
      'String',['Decimal Degrees/UTM|Decimal Degrees (formatted)|' ...
         'Degrees, Minutes'], ...
      'Value',ticktype, ...
      'HorizontalAlignment','left', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',[1 1 1], ...
      'Tag','ticktype', ...
      'UserData',ticktype, ...
      'Callback','mapaxis(''tick'')');

   h_rot = uicontrol(h_dlg, ...
      'Style','checkbox', ...
      'Position',[280 130 130 18], ...
      'String','Rotate Y-axis Ticks?', ...
      'Value',rotate, ...
      'HorizontalAlignment','left', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',colorspec, ...
      'Tag','rotate');

   h_xmin = uicontrol(h_dlg, ...
      'Style','edit', ...
      'Position',[90 75 80 20], ...
      'String',char(axlimstr{1}), ...
      'HorizontalAlignment','left', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',[1 1 1], ...
      'Tag','x_min', ...
      'Callback','mapaxis(''edit_1'')');

   h_xmax = uicontrol(h_dlg, ...
      'Style','edit', ...
      'Position',[175 75 80 20], ...
      'String',char(axlimstr{2}), ...
      'HorizontalAlignment','left', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',[1 1 1], ...
      'Tag','x_max', ...
      'Callback','mapaxis(''edit_2'')');

   h_xstart = uicontrol(h_dlg, ...
      'Style','edit', ...
      'Position',[260 75 80 20], ...
      'String',char(axlimstr{3}), ...
      'HorizontalAlignment','left', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',[1 1 1], ...
      'Tag','x_start', ...
      'Callback','mapaxis(''edit_3'')');

   h_xint = uicontrol(h_dlg, ...
      'Style','edit', ...
      'Position',[345 75 80 20], ...
      'String',char(axlimstr{4}), ...
      'HorizontalAlignment','left', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',[1 1 1], ...
      'Tag','x_int', ...
      'Callback','mapaxis(''edit_4'')');

   h_ymin = uicontrol(h_dlg, ...
      'Style','edit', ...
      'Position',[90 45 80 20], ...
      'String',char(axlimstr{5}), ...
      'HorizontalAlignment','left', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',[1 1 1], ...
      'Tag','y_min', ...
      'Callback','mapaxis(''edit_5'')');

   h_ymax = uicontrol(h_dlg, ...
      'Style','edit', ...
      'Position',[175 45 80 20], ...
      'String',char(axlimstr{6}), ...
      'HorizontalAlignment','left', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',[1 1 1], ...
      'Tag','y_max', ...
      'Callback','mapaxis(''edit_6'')');

   h_ystart = uicontrol(h_dlg, ...
      'Style','edit', ...
      'Position',[260 45 80 20], ...
      'String',char(axlimstr{7}), ...
      'HorizontalAlignment','left', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',[1 1 1], ...
      'Tag','y_start', ...
      'Callback','mapaxis(''edit_7'')');

   h_yint = uicontrol(h_dlg, ...
      'Style','edit', ...
      'Position',[345 45 80 20], ...
      'String',char(axlimstr{8}), ...
      'HorizontalAlignment','left', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',[1 1 1], ...
      'Tag','y_int', ...
      'Callback','mapaxis(''edit_8'')');

   h_apply = uicontrol(h_dlg, ...
      'Style','pushbutton', ...
      'Position',[245 5 60 25], ...
      'String','Apply', ...
      'Tag','cmdApply', ...
      'UserData',axlims, ...
      'Callback','mapaxis(''eval'')');

   h_default = uicontrol(h_dlg, ...
      'Style','pushbutton', ...
      'Position',[310 5 60 25], ...
      'String','Default', ...
      'Tag','cmdDefault', ...
      'UserData',axlimstr, ...
      'Callback','mapaxis(''default'')');

   h_cancel = uicontrol(h_dlg, ...
      'Style','pushbutton', ...
      'Position',[375 5 60 25], ...
      'String','Cancel', ...
      'Tag','cmdCancel', ...
      'UserData',axlims, ...
      'Callback','mapaxis(''cancel'')');

   uih = struct('axistype',axistype, ...
      'ticktype',h_ticktype, ...
      'rotate',h_rot, ...
      'xmin',h_xmin, ...
      'xmax',h_xmax, ...
      'xstart',h_xstart, ...
      'xint',h_xint, ...
      'ymin',h_ymin, ...
      'ymax',h_ymax, ...
      'ystart',h_ystart, ...
      'yint',h_yint, ...
      'cancel',h_cancel, ...
      'default',h_default, ...
      'apply',h_apply);

   set(h_dlg, ...
      'UserData',[{h},{ticktype},{uih}], ...
      'Visible','on')

   drawnow

else

   h_dlg = findobj('Tag','mapaxis');

   data = get(h_dlg,'UserData');
   h_fig = data{1};
   ticktype = data{2};
   uih = data{3};

   if strcmp(op,'cancel')

      close(h_dlg)
      eval('figure(h_fig)','lasterr('''')')
      drawnow

   elseif strcmp(op,'default')

      axlimstr = get(uih.default,'UserData');

      h = [uih.xmin uih.xmax uih.xstart uih.xint ...
            uih.ymin uih.ymax uih.ystart uih.yint];

      set(uih.ticktype,'Value',ticktype)

      for n = 1:length(axlimstr)
         set(h(n),'String',axlimstr{n})
      end

   elseif strcmp(op,'tick')  %update edit boxes in response to popup changes

      newval = get(uih.ticktype,'Value');

      if newval ~= ticktype

         axlims = get(uih.apply,'UserData');

	      h = [uih.xmin ; uih.xmax ; uih.xstart ; uih.xint ; ...
   	         uih.ymin ; uih.ymax ; uih.ystart ; uih.yint];

		   axlimstr = cell(1,8);
		   if newval < 3
      		for n = 1:length(axlims)
		         axlimstr{n} = num2str(abs(axlims(n)));
      		end
		   else
      		for n = 1:length(axlims)
		         axlimstr{n} = char([int2str(fix(abs(axlims(n)))) '  ' ...
      		         num2str((abs(axlims(n))-fix(abs(axlims(n)))).*60)]);
		      end
		   end

         set(h,{'String'},axlimstr')
         set(h_dlg,'UserData',[{h_fig},{newval},{uih}])

      end

   elseif strcmp(op(1:4),'edit')

      editbox = str2num(op(length(op)));

      handles = [{'xmin'},{'xmax'},{'xstart'},{'xint'}, ...
            {'ymin'},{'ymax'},{'ystart'},{'yint'}];

      eval(['h = uih.' char(handles{editbox}) ';'])

      axlims = get(uih.apply,'UserData');

      error = 0;

      axlimstr = get(h,'String');

      if ticktype < 3  %decimal ticks

         val = str2num(axlimstr);

         if ~isempty(val)
            if editbox > 3
               axlims(editbox) = val;
            else
               if ticktype > 1
                  axlims(editbox) = -1 .* val;
               else
                  axlims(editbox) = val;
               end
            end
         else
            error = 1;
         end

      else  %delimited ticks

         del = [' ''"' setstr(176) setstr(186)];  %valid delimiters

         %initialize values
         rem = axlimstr;
         level = 0;
         val = 0;

         %parse fields
         while ~isempty(rem)
            [str,rem] = strtok(rem,del);
            if ~isempty(str)
	            val = val + abs(str2num(str)./(60.^(level)));
               level = level + 1;
            end
         end

         if val > 0 & level <= 4  %check for max of 3 iterations (d,m,s)
            if editbox > 3
               axlims(editbox) = val;
            else
               axlims(editbox) = -1 .* val;
            end
         else
            error = 1;
         end

      end

      if error == 0
         set(h, ...
            'ForegroundColor',[0 0 0], ...
            'BackgroundColor',[1 1 1])
         set(uih.apply, ...
            'UserData',axlims, ...
            'Enable','on')
      else
         set(h, ...
            'ForegroundColor',[1 1 1], ...
            'BackgroundColor',[1 0 0])
         set(uih.apply,'Enable','off')
      end

   elseif strcmp(op,'eval')

      initaxlims = get(uih.cancel,'UserData');
      axlims = get(uih.apply,'UserData');

      initticks = get(uih.ticktype,'UserData');

      rotate = get(uih.rotate,'Value');
      close(h_dlg)

      error = 0;
      eval('figure(h_fig)','error = 1;')

      drawnow

      if error == 0  %check for valid plot to update

	      h = findobj(gca,'Tag','yticklabelstring');
	      if ~isempty(h)
            old_rotate = 1;
      	else
         	old_rotate = 0;
	      end

         %update plot if values changed
         if sum(axlims ~= initaxlims) > 0 | ticktype ~= initticks | rotate ~= old_rotate

            h_ax = findobj(h_fig,'Tag','mapplot');
            if isempty(h_ax)
               h_ax = gca;
            end

            if ~strcmp(ticktype,'utm')
               [ax,ar] = gpsaxis([axlims(1) axlims(5) ; axlims(2) axlims(6)],2,0);
            end

            axis([axlims(1) axlims(2) axlims(5) axlims(6)])
            xticks = [axlims(3):axlims(4):axlims(2)];
            if isempty(xticks)
               xticks = axlims(3);
            end

            yticks = [axlims(7):axlims(8):axlims(6)];
            if isempty(yticks)
               yticks = axlims(7);
            end

            %check for prior text labels, delete
            h = findobj(gca,'Tag','yticklabelstring');
            if ~isempty(h)
               delete(h)
            end

            if ticktype < 3  %decimal degrees/utm format

               if ~strcmp(uih.axistype,'utm')
                  set(h_ax, ...
                     'XTick',xticks, ...
                     'XTickLabelMode','auto', ...
                     'YTick',yticks, ...
                     'YTickLabelMode','auto', ...
                     'PlotBoxAspectRatio',ar, ...
                     'UserData',uih.axistype)
               else
                  set(h_ax, ...
                     'XTick',xticks, ...
                     'XTickLabelMode','auto', ...
                     'YTick',yticks, ...
                     'YTickLabelMode','auto', ...
                     'UserData',uih.axistype)
               end

               if ticktype == 2
                  
                  xticklbls = get(h_ax,'XTickLabel');
                  prec = size(xticklbls,2)-4;
                  xticklabels = cell(size(xticklbls,1),1);
                  for n = 1:size(xticklbls,1)
                     xticklabels{n} = [sprintf(['%' int2str(prec+3) '.' ...
                              int2str(prec) 'f'],abs(xticks(n))) setstr(176)];
                  end
                  xticklabels = char(xticklabels);

                  yticklbls = get(h_ax,'YTickLabel');
                  prec = size(yticklbls,2)-3;
                  yticklabels = cell(size(yticklbls,1),1);
                  for n = 1:size(yticklbls,1)
                     yticklabels{n} = [sprintf(['%' int2str(prec+3) '.' ...
                              int2str(prec) 'f'],abs(yticks(n))) setstr(176)];
                  end
                  yticklabels = char(yticklabels);

                  set(h_ax, ...
                     'XTickLabel',xticklabels, ...
                     'YTickLabel',yticklabels)

               end

            else  %deg,min format

               xintstr = num2str(axlims(4).*60);
               xprec = length(xintstr) - max(find(xintstr=='.'));
               if isempty(xprec); xprec = 0; end

               yintstr = num2str(axlims(8).*60);
               yprec = length(yintstr) - max(find(yintstr=='.'));
               if isempty(yprec); yprec = 0; end

               fstrx = ['%0d°%' int2str(3+xprec) '.' int2str(xprec) 'f'''];
               fstry = ['%0d°%' int2str(3+yprec) '.' int2str(yprec) 'f'''];

               xticklabel = '';
               for n = 1:length(xticks)
                  str = sprintf(fstrx,fix(abs(xticks(n))), ...
                     (abs(xticks(n))-fix(abs(xticks(n)))).*60);
                  xticklabel = str2mat(xticklabel,str);
               end
               xticklabel = xticklabel(2:size(xticklabel,1),:);

               yticklabel = '';
               for n = 1:length(yticks)
                  str = sprintf(fstry,fix(abs(yticks(n))), ...
                     (abs(yticks(n))-fix(abs(yticks(n)))).*60);
                  yticklabel = str2mat(yticklabel,str);
               end
               yticklabel = yticklabel(2:size(yticklabel,1),:);

               set(h_ax, ...
                  'XTick',xticks, ...
                  'XTickLabel',xticklabel, ...
                  'XTickLabelMode','manual', ...
                  'YTick',yticks, ...
                  'YTickLabel',yticklabel, ...
                  'YTickLabelMode','manual', ...
                  'PlotBoxAspectRatio',ar, ...
                  'UserData',uih.axistype)

            end

            %rotate y ticks if specified
            if rotate == 1
               rotateyticks
            end

            mapmenu('refreshticks')
            mapbuttons('refreshticks')

            drawnow

         end

      end

   end

end
