function close_gdt(op)
%Closes all GCE Data Tools and optionally exits MATLAB
%
%syntax: close_gdt(op)
%
%inputs:
%  op = 'close' closes tools only (default)
%  op = 'quit' closes tools and exits Matlab
%
%(c)2002-2015 Wade M. Sheldon and the Georgia Coastal Ecosystems LTER Project
%
%This file is part of the GCE Data Toolbox for MATLAB(r) software library.
%
%The GCE Data Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The GCE Data Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The GCE Data Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%
%contact:
%  Wade Sheldon
%  GCE-LTER Project
%  Department of Marine Sciences
%  University of Georgia
%  Athens, GA 30602-3636
%  sheldon@uga.edu
%
%last modified: 01-May-2015

if exist('op','var') ~= 1
   op = 'close';
end

%define array of toolbox dialog tags
handles = { ...
   'dlgAboutGCE'; ...
   'dlgAggrDateTime'; ...
   'dlgAggrStats'; ...
   'dlgBatchImport'; ...
   'dlgBinnedStats'; ...
   'dlgCalcMissing'; ...
   'dlgClearFlags'; ...
   'dlgCopyFlags'; ...
   'dlgCorrectDrift'; ...
   'dlgDataGrid'; ...
   'dlgDatePlots'; ...
   'dlgDatePlotsHTML'; ...
   'dlgDatePlotsTemplate'; ...
   'dlgDSEditor'; ...
   'dlgDSTitle'; ...
   'dlgEditFilters'; ...
   'dlgEditMetadata'; ...
   'dlgEditMetaStyles'; ...
   'dlgEditPolygons'; ...
   'dlgEditTemplates'; ...
   'dlgExport'; ...
   'dlgExpMetabase'; ...
   'dlgExpClimdb'; ...
   'dlgExpEML'; ...
   'dlgFetchClimDB'; ...
   'dlgFetchDataTurbine'; ...
   'dlgFetchEMLData'; ...
   'dlgFetchGHCND'; ...
   'dlgFetchNCDC'; ...
   'dlgFetchUSGS'; ...
   'dlgFlagDefs'; ...
   'dlgGCERegistration'; ...
   'dlgInterpMissing'; ...
   'dlgJoinData'; ...
   'dlgMapData'; ...
   'dlgMovingDateStats'; ...
   'dlgMultiMerge'; ...
   'dlgNormalizeCols'; ...
   'dlgNumReplace'; ...
   'dlgPlotData'; ...
   'dlgPlotGroups'; ...
   'dlgPlotVertProfile'; ...
   'dlgPreviewFormat'; ...
   'dlgProgressBar'; ...
   'dlgQCFlags'; ...
   'dlgQueryBuilder'; ...
   'dlgSearchData'; ...
   'dlgSortColumns'; ...
   'dlgSplitSeries'; ...
   'dlgStatReport'; ...
   'dlgStatReport'; ...
   'dlgStringReplace'; ...
   'dlgUnitConversions'; ...
   'dlgViewDocs'; ...
   'dlgViewMeta'; ...
   'dlgViewText'; ...
   'dlgVisualQC'; ...
   'dlgImportFilter' ...
   };

switch op
   
   case 'quit'
      
      confirmdlg('init', ...
         ' Close all tools and exit Matlab? (changes will be lost) ', ...
         'close_gdt(''exit'')');
      
   case 'exit'
      
      for n = 1:length(handles)
         h = findobj('Tag',handles{n});
         if ~isempty(h)
            delete(h)
         end
      end
      
      exit
      
   otherwise
      
      for n = 1:length(handles)
         h = findobj('Tag',handles{n});
         if ~isempty(h)
            delete(h)
         end
      end
      
end
