function ui_aggrdatetime(op,s,h_cb,cb)
%GCE Data Toolbox date/time aggregated statistics dialog
%
%syntax:  ui_aggrdatetime(op,s)
%
%input:
%  op = operation ('init' to initialize dialog - default)
%  s = data structure
%
%output:
%  none
%
%(c)2002-2014 Wade M. Sheldon and the Georgia Coastal Ecosystems LTER Project
%
%This file is part of the GCE Data Toolbox for MATLAB(r) software library.
%
%The GCE Data Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The GCE Data Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The GCE Data Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%
%contact:
%  Wade Sheldon
%  GCE-LTER Project
%  Department of Marine Sciences
%  University of Georgia
%  Athens, GA 30602-3636
%  sheldon@uga.edu
%
%last modified: 17-Aug-2014

%validate op argument, checking for passing data structure as first argument
if nargin == 0
   op = 'init';
elseif isstruct(op)
   s = op;
   op = 'init';
end

if exist('s','var') ~= 1
   s = [];
end

if strcmp(op,'init')  %build gui

   if length(findobj) > 1
      h_dlg = findobj('Tag','dlgAggrDateTime');
   else
      h_dlg = [];
   end

   if ~isempty(h_dlg)  %set focus to existing dialog

      figure(h_dlg)
      drawnow

   else  %create new dialog

      if exist('h_cb','var') ~= 1
         h_cb = [];
      end

      if exist('cb','var') ~= 1
         cb = '';
      end

      %load or init option preferences structure
      prefs = [];
      if exist('ui_aggrdatetime.mat','file') == 2
         try
            vars = load('ui_aggrdatetime.mat','-mat');
         catch
            vars = struct('null','');
         end
         if isfield(vars,'prefs')
            prefs = vars.prefs;
         end
      end
      if ~isstruct(prefs)
         prefs = struct('StatOpt',1, ...
            'TimeMinMax',0, ...
            'CloseOpt',1);
      end
      
      res = get(0,'ScreenSize');
      bgcolor = [.95 .95 .95];
      figpos = [max(1,0.5.*(res(3)-585)) max(50,0.5.*(res(4)-655)) 585 655];

      h_dlg = figure('Visible','off', ...
         'Color',bgcolor, ...
         'KeyPressFcn','figure(gcf)', ...
         'MenuBar','none', ...
         'Name','Date/Time Interval Statistics', ...
         'NumberTitle','off', ...
         'Position',figpos, ...
         'Tag','dlgAggrDateTime', ...
         'ToolBar','none', ...
         'Resize','off', ...
         'DefaultuicontrolUnits','pixels');

      if mlversion >= 7
         set(h_dlg,'WindowStyle','normal')
         set(h_dlg,'DockControls','off')
      end

      uicontrol('Parent',h_dlg, ...
         'Style','frame', ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',bgcolor, ...
         'Position',[1 1 figpos(3) figpos(4)]);

      %create menus
      h_mnuFile = uimenu('Parent',h_dlg, ...
         'Label','File');

      h_mnuEdit = uimenu('Parent',h_dlg, ...
         'Label','Edit');

      h_mnuLoad = uimenu('Parent',h_mnuFile, ...
         'Label','Load', ...
         'Callback','ui_aggrdatetime(''load'')', ...
         'Tag','mnuLoad', ...
         'UserData',pwd);

      h_mnuClose = uimenu('Parent',h_mnuFile, ...
         'Label','Close', ...
         'Callback','ui_aggrdatetime(''cancel'')', ...
         'Separator','on', ...
         'Tag','mnuCancel');

      uimenu('Parent',h_mnuEdit, ...
         'Label','Reset Lists', ...
         'Callback','ui_aggrdatetime(''newdata'')', ...
         'Tag','mnuReset');

      %create controls
      uicontrol('Parent',h_dlg, ...
         'Style','frame', ...
         'BackgroundColor',[.9 .9 .9], ...
         'ForegroundColor',[0 0 0], ...
         'Position',[8 610 568 35]);

      uicontrol('Parent',h_dlg, ...
         'Style','frame', ...
         'BackgroundColor',[.9 .9 .9], ...
         'ForegroundColor',[0 0 0], ...
         'Position',[270 415 305 162]);

      uicontrol('Parent',h_dlg, ...
         'Style','frame', ...
         'BackgroundColor',[.9 .9 .9], ...
         'ForegroundColor',[0 0 0], ...
         'Position',[270 100 305 305]);

      uicontrol('Parent',h_dlg, ...
         'Style','frame', ...
         'BackgroundColor',[.9 .9 .9], ...
         'ForegroundColor',[0 0 0], ...
         'Position',[8 50 568 45]);

      uicontrol('Parent',h_dlg, ...
         'Position',[50 616 380 20], ...
         'BackgroundColor',[.9 .9 .9], ...
         'FontSize',10, ...
         'FontWeight','bold', ...
         'ForegroundColor',[0 0 0.7], ...
         'String','Date/Time Interval for Statistical Summaries:', ...
         'Style','text', ...
         'Tag','lblInterval');

      h_popInterval = uicontrol('Parent',h_dlg, ...
         'Style','popupmenu', ...
         'Position',[400 620 100 20], ...
         'FontSize',10, ...
         'BackgroundColor',[1 1 1], ...
         'ForegroundColor',[0 0 0], ...
         'String','<select>', ...
         'Value',1, ...
         'UserData',0, ...
         'Tag','popInterval', ...
         'Callback','ui_aggrdatetime(''buttons'')');

      uicontrol('Parent',h_dlg, ...
         'BackgroundColor',bgcolor, ...
         'FontSize',10, ...
         'FontWeight','bold', ...
         'ForegroundColor',[0 0 0.7], ...
         'ListboxTop',0, ...
         'Position',[8 580 245 18], ...
         'String','Available Columns', ...
         'Style','text', ...
         'Tag','lblAvailable');

      uicontrol('Parent',h_dlg, ...
         'BackgroundColor',bgcolor, ...
         'FontSize',10, ...
         'FontWeight','bold', ...
         'ForegroundColor',[0 0 0.7], ...
         'ListboxTop',0, ...
         'Position',[294 580 250 18], ...
         'String','Column Selections', ...
         'Style','text', ...
         'Tag','lblSelections');

      uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[.9 .9 .9], ...
         'FontSize',10, ...
         'FontWeight','bold', ...
         'ForegroundColor',[0 0 0.7], ...
         'ListboxTop',0, ...
         'Position',[330 550 215 18], ...
         'String','Group Records By (optional)', ...
         'Style','text', ...
         'Tag','lblAggregate');

      uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[.9 .9 .9], ...
         'FontSize',10, ...
         'FontWeight','bold', ...
         'ForegroundColor',[0 0 0.7], ...
         'ListboxTop',0, ...
         'Position',[330 380 215 18], ...
         'String','Calculate Statistics For', ...
         'Style','text', ...
         'Tag','lblAnalyze');

      h_listAvailable = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'FontSize',10, ...
         'HorizontalAlignment','left', ...
         'Position',[8 100 255 476], ...
         'String',' ', ...
         'Style','listbox', ...
         'Tag','listAvailable', ...
         'Value',1);

      h_listAggregate = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'FontSize',10, ...
         'HorizontalAlignment','left', ...
         'Position',[320 430 245 120], ...
         'String',' ', ...
         'Style','listbox', ...
         'Tag','listAggregate', ...
         'Value',1);

      h_listAnalyze = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'FontSize',10, ...
         'HorizontalAlignment','left', ...
         'Position',[320 260 245 120], ...
         'String',' ', ...
         'Style','listbox', ...
         'Tag','listAnalyze', ...
         'Value',1);

      h_cmdAddAggr = uicontrol('Parent',h_dlg, ...
         'Callback','ui_aggrdatetime(''aggr_add'')', ...
         'FontSize',10, ...
         'FontWeight','bold', ...
         'ListboxTop',0, ...
         'Position',[279 490 30 22], ...
         'String','>', ...
         'ToolTipString','Add selected column to the ''Aggregate By'' list', ...
         'Tag','cmdAddAggr');

      h_cmdRemAggr = uicontrol('Parent',h_dlg, ...
         'Callback','ui_aggrdatetime(''aggr_rem'')', ...
         'FontSize',10, ...
         'FontWeight','bold', ...
         'ListboxTop',0, ...
         'Position',[279 460 30 22], ...
         'String','<', ...
         'ToolTipString','Remove selected column from the ''Aggregate By'' list', ...
         'Tag','cmdRemAggr');

      h_cmdAddStat = uicontrol('Parent',h_dlg, ...
         'Callback','ui_aggrdatetime(''stat_add'')', ...
         'FontSize',10, ...
         'FontWeight','bold', ...
         'ListboxTop',0, ...
         'Position',[279 320 30 22], ...
         'String','>', ...
         'ToolTipString','Add selected column to the ''Calculate Statistics For'' list', ...
         'Tag','cmdAddStat');

      h_cmdRemStat = uicontrol('Parent',h_dlg, ...
         'Callback','ui_aggrdatetime(''stat_rem'')', ...
         'FontSize',10, ...
         'FontWeight','bold', ...
         'ListboxTop',0, ...
         'Position',[279 290 30 22], ...
         'String','<', ...
         'ToolTipString','Remove selected column from the ''Calculate Statistics For'' list', ...
         'Tag','cmdRemStat');

      h_chkFlags = uicontrol('Parent',h_dlg, ...
         'Position',[290 230 175 20], ...
         'Style','checkbox', ...
         'FontSize',10, ...
         'BackgroundColor',[.9 .9 .9], ...
         'String',' Remove values flagged', ...
         'Value',0, ...
         'Tag','chkFlags', ...
         'TooltipString','Option to remove values assigned the specified flag codes prior to analysis', ...
         'Callback','ui_aggrdatetime(''flags'')');

      h_editFlags = uicontrol('Parent',h_dlg, ...
         'Position',[465 230 55 20], ...
         'Style','edit', ...
         'FontSize',10, ...
         'BackgroundColor',[1 1 1], ...
         'ForegroundColor',[0 0 0], ...
         'String','<any>', ...
         'HorizontalAlignment','left', ...
         'Enable','off', ...
         'Tag','editFlags', ...
         'Callback','ui_aggrdatetime(''flags'')');

      h_cmdFlags = uicontrol('Parent',h_dlg, ...
         'Position',[526 228 40 22], ...
         'Style','pushbutton', ...
         'String','List', ...
         'Enable','off', ...
         'Callback','ui_aggrdatetime(''pickflags'')', ...
         'TooltipString','Choose flag codes from a list', ...
         'Tag','cmdFlags');

      %parse flag codes from metadata
      if gce_valid(s,'data')
         flagstr = lookupmeta(s.metadata,'Data','Codes');
      else
         flagstr = '';
      end
      if ~isempty(flagstr)
         if ~isempty(strfind(flagstr,'|'))
            flaglist = splitstr(flagstr,'|');
         elseif ~isempty(strfind(flagstr,','))
            flaglist = splitstr(flagstr,',');
         else
            flaglist = cellstr(flagstr);  %assume single entry
         end
         flagdefs = [];
         for n = 1:length(flaglist)
            tmp = splitstr(flaglist{n},'=');
            if iscell(tmp) && length(tmp) == 2
               if ~isempty(tmp{1})
                  flagcode = tmp{1};
               else
                  flagcode = '?';
               end
               flagdefs = [flagdefs ; {flagcode(1)} , tmp(2)];
            end
         end
      else
         flagdefs = {'Q','questionable value';'I','invalid value (out of range)';'E','estimated value'};
      end

      %look up 'I' and 'Q' flag code positions if defined for default rule settings
      Iflag1 = find(strcmp(flagdefs(:,1),'I'));
      if isempty(Iflag1)
         Iflag1 = 1;
      else
         Iflag1 = Iflag1(1);
      end
      Iflag2 = find(strcmp(flagdefs(:,1),'Q'));
      if isempty(Iflag2)
         Iflag2 = 1;
      else
         Iflag2 = Iflag2(1);
      end

      %define Q/C rule type array with cols for popupmenu label, criteria type, criteria units
      qcruletypes = {'if number missing >','missing','count'; ...
            'if percent missing >','missing','percent'; ...
            'if consecutive missing >','missing','consecutive'; ...
            'if number flagged >','flagged','count'; ...
            'if percent flagged >','flagged','percent'; ...
            'if consecutive flagged >','flagged','consecutive'};

      uicontrol('Parent',h_dlg, ...
         'Position',[280 198 50 20], ...
         'Style','text', ...
         'Fontsize',10, ...
         'HorizontalAlignment','right', ...
         'BackgroundColor',[.9 .9 .9], ...
         'ForegroundColor',[0 0 0], ...
         'String','Flag as ', ...
         'Tag','txtQC1');

      h_popQCFlag1 = uicontrol('Parent',h_dlg, ...
         'Position',[330 201 40 20], ...
         'Style','popupmenu', ...
         'FontSize',10, ...
         'BackgroundColor',[1 1 1], ...
         'ForegroundColor',[0 0 0], ...
         'String',flagdefs(:,1), ...
         'TooltipString','Select a flag to assign for this Q/C rule', ...
         'Value',Iflag1, ...
         'UserData',flagdefs(:,1), ...
         'Tag','popQCFlag1');

      h_popQCRule1 = uicontrol('Parent',h_dlg, ...
         'Position',[370 201 140 20], ...
         'Style','popupmenu', ...
         'Fontsize',10, ...
         'HorizontalAlignment','center', ...
         'BackgroundColor',[1 1 1], ...
         'ForegroundColor',[0 0 0], ...
         'String',qcruletypes(:,1), ...
         'TooltipString','Select the type of criteria to use for this Q/C rule', ...
         'Value',2, ...
         'Tag','popQCRule1');

      h_editQC1 = uicontrol('Parent',h_dlg, ...
         'Position',[512 198 55 22], ...
         'Style','edit', ...
         'FontSize',10, ...
         'BackgroundColor',[1 1 1], ...
         'HorizontalAlignment','left', ...
         'String','', ...
         'TooltipString','Enter numeric criteria for this Q/C rule (or clear box to omit rule)', ...
         'Callback','ui_aggrdatetime(''checknum'')', ...
         'Tag','editQC1');

      uicontrol('Parent',h_dlg, ...
         'Position',[280 168 50 20], ...
         'Style','text', ...
         'Fontsize',10, ...
         'HorizontalAlignment','right', ...
         'BackgroundColor',[.9 .9 .9], ...
         'ForegroundColor',[0 0 0], ...
         'String','Flag as ', ...
         'Tag','txtQC2');

      h_popQCFlag2 = uicontrol('Parent',h_dlg, ...
         'Position',[330 171 40 20], ...
         'Style','popupmenu', ...
         'FontSize',10, ...
         'BackgroundColor',[1 1 1], ...
         'ForegroundColor',[0 0 0], ...
         'String',flagdefs(:,1), ...
         'TooltipString','Select a flag to assign for this Q/C rule', ...
         'Value',Iflag2, ...
         'UserData',flagdefs(:,1), ...
         'Tag','popQCFlag2');

      h_popQCRule2 = uicontrol('Parent',h_dlg, ...
         'Position',[370 171 140 20], ...
         'Style','popupmenu', ...
         'Fontsize',10, ...
         'HorizontalAlignment','center', ...
         'BackgroundColor',[1 1 1], ...
         'ForegroundColor',[0 0 0], ...
         'String',qcruletypes(:,1), ...
         'TooltipString','Select the type of criteria to use for this Q/C rule', ...
         'Value',2, ...
         'Tag','popQCRule2');

      h_editQC2 = uicontrol('Parent',h_dlg, ...
         'Position',[512 168 55 22], ...
         'Style','edit', ...
         'FontSize',10, ...
         'BackgroundColor',[1 1 1], ...
         'HorizontalAlignment','left', ...
         'String','', ...
         'TooltipString','Enter numeric criteria for this Q/C rule (or clear box to omit rule)', ...
         'Callback','ui_aggrdatetime(''checknum'')', ...
         'Tag','editQC2');

      uicontrol('Parent',h_dlg, ...
         'Position',[280 138 50 20], ...
         'Style','text', ...
         'Fontsize',10, ...
         'HorizontalAlignment','right', ...
         'BackgroundColor',[.9 .9 .9], ...
         'ForegroundColor',[0 0 0], ...
         'String','Flag as ', ...
         'Tag','txtQC3');

      h_popQCFlag3 = uicontrol('Parent',h_dlg, ...
         'Position',[330 141 40 20], ...
         'Style','popupmenu', ...
         'FontSize',10, ...
         'BackgroundColor',[1 1 1], ...
         'ForegroundColor',[0 0 0], ...
         'String',flagdefs(:,1), ...
         'TooltipString','Select a flag to assign for this Q/C rule', ...
         'Value',Iflag1, ...
         'UserData',flagdefs(:,1), ...
         'Tag','popQCFlag3');

      h_popQCRule3 = uicontrol('Parent',h_dlg, ...
         'Position',[370 141 140 20], ...
         'Style','popupmenu', ...
         'Fontsize',10, ...
         'HorizontalAlignment','center', ...
         'BackgroundColor',[1 1 1], ...
         'ForegroundColor',[0 0 0], ...
         'String',qcruletypes(:,1), ...
         'TooltipString','Select the type of criteria to use for this Q/C rule', ...
         'Value',5, ...
         'Tag','popQCRule3');

      h_editQC3 = uicontrol('Parent',h_dlg, ...
         'Position',[512 138 55 22], ...
         'Style','edit', ...
         'FontSize',10, ...
         'BackgroundColor',[1 1 1], ...
         'HorizontalAlignment','left', ...
         'String','', ...
         'TooltipString','Enter numeric criteria for this Q/C rule (or clear box to omit rule)', ...
         'Callback','ui_aggrdatetime(''checknum'')', ...
         'Tag','editQC2');

      uicontrol('Parent',h_dlg, ...
         'Position',[280 108 50 20], ...
         'Style','text', ...
         'Fontsize',10, ...
         'HorizontalAlignment','right', ...
         'BackgroundColor',[.9 .9 .9], ...
         'ForegroundColor',[0 0 0], ...
         'String','Flag as ', ...
         'Tag','txtQC3');

      h_popQCFlag4 = uicontrol('Parent',h_dlg, ...
         'Position',[330 111 40 20], ...
         'Style','popupmenu', ...
         'FontSize',10, ...
         'BackgroundColor',[1 1 1], ...
         'ForegroundColor',[0 0 0], ...
         'String',flagdefs(:,1), ...
         'TooltipString','Select a flag to assign for this Q/C rule', ...
         'Value',Iflag2, ...
         'UserData',flagdefs(:,1), ...
         'Tag','popQCFlag3');

      h_popQCRule4 = uicontrol('Parent',h_dlg, ...
         'Position',[370 111 140 20], ...
         'Style','popupmenu', ...
         'Fontsize',10, ...
         'HorizontalAlignment','center', ...
         'BackgroundColor',[1 1 1], ...
         'ForegroundColor',[0 0 0], ...
         'String',qcruletypes(:,1), ...
         'TooltipString','Select the type of criteria to use for this Q/C rule', ...
         'Value',5, ...
         'Tag','popQCRule3');

      h_editQC4 = uicontrol('Parent',h_dlg, ...
         'Position',[512 108 55 22], ...
         'Style','edit', ...
         'FontSize',10, ...
         'BackgroundColor',[1 1 1], ...
         'HorizontalAlignment','left', ...
         'String','', ...
         'TooltipString','Enter numeric criteria for this Q/C rule (or clear box to omit rule)', ...
         'Callback','ui_aggrdatetime(''checknum'')', ...
         'Tag','editQC2');
      
      uicontrol('Parent',h_dlg, ...
         'Position',[12 60 80 20], ...
         'Style','text', ...
         'FontSize',10, ...
         'FontWeight','bold', ...
         'BackgroundColor',[.9 .9 .9], ...
         'String','Statistics:');
      
      %define array of stat options for aggr_stats
      statopt = { ...
         0,'Automatic (based on numeric and variable type)'; ...
         1,'Count'; ...
         7,'Count, Total'; ...
         2,'Count, Min, Max'; ...
         3,'Count, Min, Max, Total, Median'; ...
         4,'Count, Min, Max, Total, Mean/Vector Avg, StdDev, SE'; ...
         5,'Count, Min, Max, Mean/Vector Avg, StdDev, SE'; ...
         6,'Count, Mean/Vector Avg' ...
         };
      
      h_popStatOpt = uicontrol('Parent',h_dlg, ...
         'Position',[92 63 320 20], ...
         'Style','popupmenu', ...
         'FontSize',9, ...
         'BackgroundColor',[1 1 1], ...
         'String',statopt(:,2), ...
         'Value',prefs.StatOpt, ...
         'UserData',statopt(:,1));
      
      h_chkTimeMinMax = uicontrol('Parent',h_dlg, ...
         'Position',[430 61 105 20], ...
         'Style','checkbox', ...
         'FontSize',9, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'String','Time Min/Max', ...
         'Value',prefs.TimeMinMax, ...
         'TooltipString','Specifies whether Time_Min_... and Time_Max_... columns should be included with Min/Max');

      h_cmdCancel = uicontrol('Parent',h_dlg, ...
         'Callback','ui_aggrdatetime(''cancel'')', ...
         'FontSize',9, ...
         'Position',[15 10 60 25], ...
         'String','Cancel', ...
         'TooltipString','Cancel the operation and close the dialog window', ...
         'Tag','cmdCancel');

      h_chkClose = uicontrol('Parent',h_dlg, ...
         'Style','checkbox', ...
         'Position',[165 10 270 20], ...
         'BackgroundColor',bgcolor, ...
         'FontSize',10, ...
         'String','Close dialog after exporting the results', ...
         'Value',prefs.CloseOpt, ...
         'Tag','chkClose');

      h_cmdEval = uicontrol('Parent',h_dlg, ...
         'Callback','ui_aggrdatetime(''eval'')', ...
         'Enable','off', ...
         'FontSize',9, ...
         'ListboxTop',0, ...
         'Position',[510 10 60 25], ...
         'String','Proceed', ...
         'TooltipString','Perform the aggregated statistics and open the structure for editing', ...
         'Tag','cmdEval');

      uih = struct( ...
         'mnuLoad',h_mnuLoad, ...
         'mnuClose',h_mnuClose, ...
         'popInterval',h_popInterval, ...
         'listAvailable',h_listAvailable, ...
         'listAggregate',h_listAggregate, ...
         'listAnalyze',h_listAnalyze, ...
         'cmdAddAggr',h_cmdAddAggr, ...
         'cmdRemAggr',h_cmdRemAggr, ...
         'cmdAddStat',h_cmdAddStat, ...
         'cmdRemStat',h_cmdRemStat, ...
         'intervals',[], ...
         'dtcols',[], ...
         'chkFlags',h_chkFlags, ...
         'editFlags',h_editFlags, ...
         'cmdFlags',h_cmdFlags, ...
         'popQCFlag1',h_popQCFlag1, ...
         'popQCRule1',h_popQCRule1, ...
         'editQC1',h_editQC1, ...
         'popQCFlag2',h_popQCFlag2, ...
         'popQCRule2',h_popQCRule2, ...
         'editQC2',h_editQC2, ...
         'popQCFlag3',h_popQCFlag3, ...
         'popQCRule3',h_popQCRule3, ...
         'editQC3',h_editQC3, ...
         'popQCFlag4',h_popQCFlag4, ...
         'popQCRule4',h_popQCRule4, ...
         'editQC4',h_editQC4, ...
         'popStatOpt',h_popStatOpt, ...
         'chkTimeMinMax',h_chkTimeMinMax, ...
         'cmdEval',h_cmdEval, ...
         'cmdCancel',h_cmdCancel', ...
         'chkClose',h_chkClose, ...
         'qcruletypes',[], ...
         'flagdefs',[], ...
         's',s, ...
         'h_cb',h_cb, ...
         'cb',cb);

      %update array fields
      uih.qcruletypes = qcruletypes;
      uih.flagdefs = flagdefs;
      uih.intervals = {'year','Yearly';'month','Monthly';'day','Daily';'hour','Hourly'};

      set(h_dlg,'Visible','on','UserData',uih)
      drawnow

      if ~isempty(s)
         ui_aggrdatetime('newdata')
      end

   end

else  %handle callbacks

   h_dlg = [];

   if length(findobj) > 2
      h_dlg = gcf;
      if ~strcmp(get(h_dlg,'Tag'),'dlgAggrDateTime')
         h_dlg = [];
      end
   end

   if ~isempty(h_dlg)

      uih = get(h_dlg,'UserData');
      s = uih.s;

      switch op

         case 'cancel'  %close dialog

            delete(h_dlg)
            ui_aboutgce('reopen')  %check for last window

         case 'checknum'  %validate q/c criteria limit

            h_edit = gcbo;  %get handle of active editbox
            str = deblank(get(h_edit,'String'));  %get editbox contents

            if ~isempty(str)
               val = str2double(str);
               if isnan(val) || val < 0
                  set(h_edit,'String',get(h_edit,'UserData'))  %restore last good value
                  messagebox('init','Flagged value limit must be a positive integer - field reset', ...
                     '','Error',[.9 .9 .9])
               else
                  set(h_edit,'UserData',str)  %buffer new good value
               end
               drawnow
            else
               set(h_edit,'String','','UserData','')  %clear entry and stored last value
            end

         case 'newdata'  %update indices in response to new data load

            intervals = uih.intervals;

            if gce_valid(s,'data')

               %check for at least year and month columns and auto-generate dart parts if not found
               Idt = find(strcmp(s.variabletype,'datetime') & strcmp(s.datatype,'d') & ...
                  inlist(s.name,{'Year','Month','Day','Hour','Minute','Second'})');
               if length(Idt) < 2
                  s = add_datepartcols(s);
                  if ~isempty(s)
                     uih.s = s;  %update cached structure
                     Idt = find(strcmp(s.variabletype,'datetime') & strcmp(s.datatype,'d'));
                  end
               end

               if ~isempty(Idt)

                  Idtcols = zeros(1,size(intervals,1));
                  Iintervals = Idtcols;

                  for n = 1:size(intervals,1)
                     Iint = find(strcmpi(s.name(Idt),intervals{n,1}));
                     if ~isempty(Iint)
                        Iintervals(n) = 1;
                        Idtcols(n) = Idt(Iint(1));
                     end
                  end

                  Ibadint = find(Iintervals == 0);

                  if ~isempty(Ibadint)
                     Ibadint = Ibadint(1);
                     if Ibadint > 1
                        Idtcols = Idtcols(1:Ibadint-1);
                        intliststr = [{'<select>'} ; intervals(1:Ibadint-1,2)];
                        intlist = [0,(1:Ibadint-1)];
                     else
                        Idtcols = [];
                        intliststr = '<select>';
                        intlist = 0;
                     end
                  else
                     intliststr = [{'<select>'} ; intervals(:,2)];
                     intlist = [0,(1:size(intervals,1))];
                  end

                  if ~isempty(Idtcols)
                     uih.dtcols = Idtcols;
                     set(h_dlg,'UserData',uih)
                     set(uih.popInterval,'String',intliststr,'UserData',intlist,'Value',1)
                     cols = find(~strcmp(s.variabletype,'datetime'));
                     set(uih.listAvailable,'UserData',cols,'Value',1)  %store full index
                     set(uih.listAggregate,'UserData',[],'Value',1)  %clear aggregate index
                     set(uih.listAnalyze,'UserData',[],'Value',1)  %clear analyze index
                     ui_aggrdatetime('update')
                  else
                     uih.s = [];
                     set(h_dlg,'UserData',uih)
                     messagebox('init', ...
                        'The data structure does not contain suitable date/time columns for this function', ...
                        [], ...
                        'Error', ...
                        [.9 .9 .9]);
                  end

               else
                  uih.s = [];
                  set(h_dlg,'UserData',uih)
                  messagebox('init', ...
                     'The data structure does not contain suitable date/time columns for this function', ...
                     [], ...
                     'Error', ...
                     [.9 .9 .9]);
               end

            else
               uih.s = [];
               set(h_dlg,'UserData',uih)
               messagebox('init', ...
                  '  Invalid GCE Data Structure  ', ...
                  [], ...
                  'Error', ...
                  [.9 .9 .9]);
            end

         case 'update'  %update control states based on indices, selections

            if isstruct(s)

               %get list indices
               I_avail = get(uih.listAvailable,'UserData');
               I_aggr = get(uih.listAggregate,'UserData');
               I_analyze = get(uih.listAnalyze,'UserData');

               %get column attributes
               vars = s.name;
               units = s.units;
               cols = length(s.name);
               varstr = cell(1,cols);

               for n = 1:cols
                  varstr{n} = [vars{n},'  (',units{n},')'];
               end

               if ~isempty(I_avail)
                  s_avail = varstr(I_avail);
               else
                  s_avail = {''};
               end

               if ~isempty(I_aggr)
                  s_aggr = varstr(I_aggr);
               else
                  s_aggr = {''};
               end

               if ~isempty(I_analyze)
                  s_analyze = varstr(I_analyze);
               else
                  s_analyze = {''};
               end

               %cache list pointer arrays
               set(uih.listAvailable, ...
                  'String',s_avail, ...
                  'Value',max(1,min(get(uih.listAvailable,'Value'),length(I_avail))))

               set(uih.listAggregate, ...
                  'String',s_aggr, ...
                  'Value',max(1,min(get(uih.listAggregate,'Value'),length(I_aggr))))

               set(uih.listAnalyze, ...
                  'String',s_analyze, ...
                  'Value',max(1,min(get(uih.listAnalyze,'Value'),length(I_analyze))))

               ui_aggrdatetime('buttons')

            end

         case 'buttons'  %toggle button states

            %toggle add/remove buttons according to list status
            interval_sel = get(uih.popInterval,'Value');
            I_avail = get(uih.listAvailable,'UserData');
            I_aggr = get(uih.listAggregate,'UserData');
            I_analyze = get(uih.listAnalyze,'UserData');

            if isempty(I_avail)
               set(uih.cmdAddAggr,'Enable','off')
               set(uih.cmdAddStat,'Enable','off')
            else
               set(uih.cmdAddAggr,'Enable','on')
               set(uih.cmdAddStat,'Enable','on')
            end

            if isempty(I_aggr)
               set(uih.cmdRemAggr,'Enable','off')
            else
               set(uih.cmdRemAggr,'Enable','on')
            end

            if isempty(I_analyze)
               set(uih.cmdRemStat,'Enable','off')
            else
               set(uih.cmdRemStat,'Enable','on')
            end

            %toggle proceed button according to list status
            if interval_sel > 1 && ~isempty(I_analyze)
               set(uih.cmdEval,'Enable','on')
            else
               set(uih.cmdEval,'Enable','off')
            end

            drawnow

         case 'eval'  %evaluate input, generate derived data structure

            %get parameters from dialog menus
            interval_val = get(uih.popInterval,'Value') - 1;
            interval = uih.intervals{interval_val,1};
            I_dtcols = uih.dtcols(1:interval_val);
            I_aggr = get(uih.listAggregate,'UserData');
            I_stat = get(uih.listAnalyze,'UserData');
            closeval = get(uih.chkClose,'Value');
                           
            %get statistics and time min/max options
            statopts = get(uih.popStatOpt,'UserData');
            statoptval = get(uih.popStatOpt,'Value');
            statopt = statopts{statoptval};
            tminmax = get(uih.chkTimeMinMax,'Value');

            %handle q/c flag removal options
            flagopt = get(uih.chkFlags,'Value');
            flagchars = deblank(get(uih.editFlags,'String'));
            if flagopt == 1 && strcmp(flagchars,'<any>') ~= 1
               %if remove flags checked and codes specified, use flag chars instead of integer option
               flagopt = flagchars;
            end

            %generate qcrules array
            qcrules = [];
            qcruletypes = uih.qcruletypes;
            qcflagdefs = uih.flagdefs;

            %process criteria 1
            crit = deblank(get(uih.editQC1,'String'));
            if ~isempty(crit)
               ruleval = get(uih.popQCRule1,'Value');
               flagval = get(uih.popQCFlag1,'Value');
               qcrules = [qcrules ; {qcruletypes{ruleval,2} crit qcruletypes{ruleval,3} qcflagdefs{flagval,1}}];
            end

            %process criteria 2
            crit = deblank(get(uih.editQC2,'String'));
            if ~isempty(crit)
               ruleval = get(uih.popQCRule2,'Value');
               flagval = get(uih.popQCFlag2,'Value');
               qcrules = [qcrules ; {qcruletypes{ruleval,2} crit qcruletypes{ruleval,3} qcflagdefs{flagval,1}}];
            end

            %process criteria 3
            crit = deblank(get(uih.editQC3,'String'));
            if ~isempty(crit)
               ruleval = get(uih.popQCRule3,'Value');
               flagval = get(uih.popQCFlag3,'Value');
               qcrules = [qcrules ; {qcruletypes{ruleval,2} crit qcruletypes{ruleval,3} qcflagdefs{flagval,1}}];
            end

            %process criteria 4
            crit = deblank(get(uih.editQC4,'String'));
            if ~isempty(crit)
               ruleval = get(uih.popQCRule4,'Value');
               flagval = get(uih.popQCFlag4,'Value');
               qcrules = [qcrules ; {qcruletypes{ruleval,2} crit qcruletypes{ruleval,3} qcflagdefs{flagval,1}}];
            end

            %update preferences
            prefs = struct('StatOpt',statoptval, ...
               'TimeMinMax',tminmax, ...
               'CloseOpt',closeval);
            
            %save dialog preferences
            pn = fileparts(which('ui_aggrdatetime.mat'));
            if isempty(pn)
               pn = [gce_homepath,filesep,'settings'];
            end
            if ~isdir(pn)
               pn = fileparts(which('ui_aggrdatetime'));
            end
            save([pn,filesep,'ui_aggrdatetime.mat'],'prefs')
            
            set(gcf,'Pointer','watch')
            drawnow

            %pass parms to aggregation function
            [s2,msg] = aggr_datetime(s,interval,I_dtcols,I_aggr,I_stat,statopt,flagopt,qcrules,0,tminmax);

            set(gcf,'Pointer','arrow')
            drawnow

            if ~isempty(s2)

               if closeval == 1
                  delete(h_dlg)
                  drawnow
               end

               %check for hooks to calling dialog
               if isempty(uih.h_cb) && isempty(uih.cb)
                  ui_editor('init',s2);  %send results to editor
               else
                  err = 0;
                  if ~isempty(uih.h_cb)
                     h_parent = parent_figure(uih.h_cb);
                     if ~isempty(h_parent)
                        set(uih.h_cb,'UserData',s2)
                     else
                        err = 1;
                     end
                  end
                  if err == 0 && ~isempty(uih.cb)
                     try
                        eval(uih.cb)
                     catch
                        err = 1;
                     end
                  end
                  if err == 1  %check for errors - open in new window
                     ui_editor('init',s2)
                     messagebox('init','Errors occurred returning data to the calling window', ...
                        '','Error',[.9 .9 .9])
                  end
               end

            else
               messagebox('init',['An error occurred: ',msg],'','Error',[.9 .9 .9]);
            end

         case 'load'  %load new data file

            %open load file dialog starting in last path
            curpath = pwd;
            lastpath = get(uih.mnuLoad,'UserData');
            if ~isempty(lastpath)
               cd(lastpath)
            end
            [fn,pn] = uigetfile('*.mat;*.MAT','Select a file containing a GCE Data Structure');
            cd(curpath)
            drawnow

            if fn ~= 0

               set(uih.mnuLoad,'UserData',pn)  %update cached path

               err = 0;
               vars = [];

               cd(pn)
               try
                  vars = load(fn,'-mat');
               catch
                  err = 1;
               end
               cd(curpath)

               if err == 0 && isstruct(vars)

                  vnames = fieldnames(vars);

                  if length(vnames) > 1
                     Isel = listdialog('liststring',vnames, ...
                        'selectionmode','single', ...
                        'promptstring','Select a variable from the list to load', ...
                        'name','Select Variable');
                  else
                     Isel = 1;
                  end

                  if ~isempty(Isel)

                     s = vars.(vnames{Isel});

                     uih.s = s;
                     set(h_dlg,'UserData',uih)

                     ui_aggrdatetime('newdata')

                  end

               else

                  messagebox('init', ...
                     ['''',fn,''' is not a valid Matlab data file'], ...
                     [], ...
                     'Error', ...
                     [.9 .9 .9]);

               end

            end

         case 'copysel'  %copy selected column to specified list, using stored handles to id source/target

            %get handles
            h_source = get(uih.cmdAddAggr,'UserData');
            h_target = get(uih.cmdRemAggr,'UserData');
            h_list = uih.listAvailable;

            if ~isempty(h_source) && ~isempty(h_target)

               %get indices
               I_target = get(h_target,'UserData');
               I_source = get(h_source,'UserData');
               I_sel = I_source(get(h_source,'Value'));

               %update indices
               I_target = [I_target,I_sel];
               I_source = I_source(I_source~=I_sel);

               %store indices
               set(h_target,'UserData',I_target)
               set(h_source,'UserData',I_source)

               %resort master list if adding rows back to list
               if h_target == h_list
                  Ilist = get(h_list,'UserData');
                  Ilist = sort(Ilist);
                  Isel = find(Ilist==I_target(end));
                  set(h_list,'UserData',sort(Ilist),'Value',Isel)
               else
                  set(h_target,'Value',length(I_target))
               end

               %update uicontrols
               ui_aggrdatetime('update');

            end

         case 'aggr_add'

            %assign handles
            set(uih.cmdAddAggr,'UserData',uih.listAvailable);  %source
            set(uih.cmdRemAggr,'UserData',uih.listAggregate);  %target

            %update listboxes
            ui_aggrdatetime('copysel')

         case 'aggr_rem'

            %assign handles
            set(uih.cmdAddAggr,'UserData',uih.listAggregate);  %source
            set(uih.cmdRemAggr,'UserData',uih.listAvailable);  %target

            %update listboxes
            ui_aggrdatetime('copysel')

         case 'stat_add'

            %assign handles
            set(uih.cmdAddAggr,'UserData',uih.listAvailable);  %source
            set(uih.cmdRemAggr,'UserData',uih.listAnalyze);  %target

            %update listboxes
            ui_aggrdatetime('copysel')

         case 'stat_rem'

            %assign handles
            set(uih.cmdAddAggr,'UserData',uih.listAnalyze);  %source
            set(uih.cmdRemAggr,'UserData',uih.listAvailable);  %target

            %update listboxes
            ui_aggrdatetime('copysel')

         case 'pickflags'  %open dialog to choose flags to remove prior to aggregation

            flagdefs = uih.flagdefs;

            if ~isempty(flagdefs)

               str = concatcellcols(flagdefs,' = ');
               Isel = listdialog('liststring',str, ...
                  'name','Choose Flags', ...
                  'promptstring','Choose Q/C Flags for Value Removal', ...
                  'selectionmode','multiple', ...
                  'initialvalue',1, ...
                  'listsize',[0 0 500 300]);

               %check for cancel
               if ~isempty(Isel)
                  flags = [flagdefs{Isel,1}];
                  set(uih.editFlags,'String',flags)
               end

            end

         case 'flags'  %validate flag selections on change

            flags = deblank(get(uih.editFlags,'String'));
            if isempty(flags)
               flags = '<any>';
            end

            flagopt = get(uih.chkFlags,'Value');
            if flagopt == 1
               enable = 'on';
            else
               enable = 'off';
            end

            set(uih.editFlags,'Enable',enable,'String',flags)
            set(uih.cmdFlags,'Enable',enable)
            drawnow

      end

   end

end