function ui_dateplots_template(op)
%GUI dialog for generating multiple date plots at various intervals from a time-series plot
%in PNG format, and generating a multi-column HTML file with optional hyperlinked thumbnails
%to preview images
%
%syntax:  ui_dateplots_template
%
%(c)2002-2009 Wade M. Sheldon and the Georgia Coastal Ecosystems LTER Project
%
%This file is part of the GCE Data Toolbox for MATLAB(r) software library.
%
%The GCE Data Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The GCE Data Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The GCE Data Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%
%contact:
%  Wade Sheldon
%  GCE-LTER Project
%  Department of Marine Sciences
%  University of Georgia
%  Athens, GA 30602-3636
%  sheldon@uga.edu
%
%last modified: 23-Jan-2009

if nargin == 0
   op = 'init';
end

if strcmp(op,'init') == 1

   if length(findobj) > 1
      h_fig = gcf;
      h_dlg = findobj('Tag','dlgDatePlotsTemplate');
      h_ed = findobj('tag','dlgDSEditor');
      if ~isempty(h_ed)
         pn = get(findobj(h_ed(end),'tag','mnuSave'),'UserData');
      else
         pn = pwd;
      end
   else
      f_fig = [];
      h_dlg = [];
      pn = pwd;
   end

   if ~isempty(h_dlg)
      delete(h_dlg)
   end

   if ~isempty(h_fig)

      bgcolor = [0.9 0.9 0.9];
      res = get(0,'screensize');
      figunits = get(h_fig,'Units');
      set(h_fig,'Units','pixels')
      figpos = get(h_fig,'Position');
      set(h_fig,'Units',figunits)
      figwidth = ceil(figpos(3));

      pagetitle = '';
      h_ax = findobj(h_fig,'Type','axes');
      for n = 1:length(h_ax)
         pagetitle = get(get(h_ax(n),'title'),'string');
         if size(pagetitle,1) > 1
            pagetitle = char(concatcellcols(trimstr(cellstr(pagetitle)'),' '));
            break
         end
      end

      intervals = {'day';'week';'month';'year';'decade'};

      h_dlg = figure('Visible','off', ...
         'Color',[0.95 0.95 0.95], ...
         'KeyPressFcn','figure(gcf)', ...
         'Resize','off', ...
         'MenuBar','none', ...
         'Name','Export Date Plots', ...
         'NumberTitle','off', ...
         'Position',[max(10,(res(3)-700).*0.5) max(30,(res(4)-440).*0.5) 700 440], ...
         'Tag','dlgDatePlotsTemplate', ...
         'ToolBar','none', ...
         'CloseRequestFcn','ui_dateplots_template(''cancel'')', ...
         'DefaultuicontrolUnits','pixels');

      if mlversion >= 7
         set(h_dlg,'WindowStyle','normal')
         set(h_dlg,'DockControls','off')
      end

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',bgcolor, ...
         'Position',[5 45 690 390], ...
         'Style','frame', ...
         'Tag','Frame1');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',bgcolor, ...
         'FontSize',10, ...
         'FontWeight','bold', ...
         'ForegroundColor',[0 0 0.8], ...
         'Position',[20 390 170 20], ...
         'String','HTML Template File', ...
         'Style','text', ...
         'Tag','StaticText1');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',bgcolor, ...
         'FontSize',10, ...
         'FontWeight','bold', ...
         'ForegroundColor',[0 0 0.8], ...
         'Position',[20 360 170 20], ...
         'String','Path for Writing Files', ...
         'Style','text', ...
         'Tag','StaticText1');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',bgcolor, ...
         'FontSize',10, ...
         'FontWeight','bold', ...
         'ForegroundColor',[0 0 0.8], ...
         'Position',[20 330 170 20], ...
         'String','Name For HTML File', ...
         'Style','text', ...
         'Tag','StaticText1');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',bgcolor, ...
         'FontSize',10, ...
         'FontWeight','bold', ...
         'ForegroundColor',[0 0 0.8], ...
         'Position',[20 300 170 20], ...
         'String','Name Prefix for Images', ...
         'Style','text', ...
         'Tag','StaticText1');

      h1 = uicontrol('Parent',h_dlg, ...
         'Style','text', ...
         'BackgroundColor',[0 0 0], ...
         'Position',[15 285 670 1]);

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',bgcolor, ...
         'FontSize',10, ...
         'FontWeight','bold', ...
         'ForegroundColor',[0 0 0.8], ...
         'Position',[25 240 114 20], ...
         'String','Date Interval', ...
         'Style','text', ...
         'Tag','StaticText1');

      h_editTemplate = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'FontSize',10, ...
         'HorizontalAlignment','left', ...
         'Position',[194 390 423 23], ...
         'Style','edit', ...
         'String',which('template_default.htm'), ...
         'Tag','editPath', ...
         'Callback','ui_dateplots_template(''template'')', ...
         'UserData',which('template_default.htm'));

      h_editPath = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'FontSize',10, ...
         'HorizontalAlignment','left', ...
         'Position',[194 360 423 23], ...
         'Style','edit', ...
         'String',pn, ...
         'Tag','editPath', ...
         'Callback','ui_dateplots_template(''path'')', ...
         'UserData',pn);

      h_editHTML = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'FontSize',10, ...
         'HorizontalAlignment','left', ...
         'Position',[195 330 245 23], ...
         'Style','edit', ...
         'String','index.htm', ...
         'Callback','ui_dateplots_template(''buttons'')', ...
         'Tag','editName');

      h_editName = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'FontSize',10, ...
         'HorizontalAlignment','left', ...
         'Position',[195 300 245 23], ...
         'Style','edit', ...
         'Callback','ui_dateplots_template(''buttons'')', ...
         'Tag','editName');

      h_popInterval = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'FontSize',10, ...
         'Position',[141 240 271 22], ...
         'String',{'Daily (1 day per plot)';'Weekly (1 week per plot)';'Monthly (1 month per plot)';'Annual (1 year per plot)';'Decadal (10 years per plot)'}, ...
         'Style','popupmenu', ...
         'Tag','popInterval', ...
         'Value',3);

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',bgcolor, ...
         'FontSize',10, ...
         'FontWeight','bold', ...
         'ForegroundColor',[0 0 0.8], ...
         'Position',[30 200 115 20], ...
         'String','Plots Per Row', ...
         'Style','text', ...
         'Tag','StaticText1');

      h_editCols = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'FontSize',10, ...
         'HorizontalAlignment','left', ...
         'Position',[145 200 60 23], ...
         'String','3', ...
         'Style','edit', ...
         'UserData',3, ...
         'Callback','ui_dateplots_template(''checknum'')', ...
         'Tag','editCols');

      h_editWidth = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'FontSize',10, ...
         'HorizontalAlignment','left', ...
         'Position',[470 200 60 23], ...
         'String',int2str(figwidth), ...
         'Style','edit', ...
         'UserData',figwidth, ...
         'Callback','ui_dateplots_template(''checknum'')', ...
         'Tag','editWidth');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',bgcolor, ...
         'FontSize',10, ...
         'FontWeight','bold', ...
         'ForegroundColor',[0 0 0.8], ...
         'Position',[300 200 160 20], ...
         'String','Image Width (pixels)', ...
         'Style','text', ...
         'Tag','StaticText1');

      h_chkThumbs = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',bgcolor, ...
         'ForegroundColor',[0 0 .8], ...
         'Style','checkbox', ...
         'FontSize',10, ...
         'FontWeight','bold', ...
         'Position',[40 160 220 23], ...
         'String','Generate Thumbnail Images', ...
         'Value',1, ...
         'Callback','ui_dateplots_template(''thumbs'')', ...
         'Tag','chkThumbs');

      h_lblThumbs = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',bgcolor, ...
         'FontSize',10, ...
         'FontWeight','bold', ...
         'ForegroundColor',[0 0 0.8], ...
         'Position',[280 160 190 20], ...
         'String','Thumbnail Width (pixels)', ...
         'Style','text', ...
         'Tag','lblThumbs');

      h_editThumbs = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'FontSize',10, ...
         'HorizontalAlignment','left', ...
         'Position',[470 160 60 23], ...
         'String',int2str(300), ...
         'Style','edit', ...
         'UserData',300, ...
         'Callback','ui_dateplots_template(''checknum'')', ...
         'Tag','editThumbs');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',bgcolor, ...
         'FontSize',10, ...
         'FontWeight','bold', ...
         'ForegroundColor',[0 0 0.8], ...
         'Position',[25 125 180 20], ...
         'HorizontalAlignment','left', ...
         'String','Web Page Caption Text', ...
         'Style','text', ...
         'Tag','StaticText1');

      h_editPageTitle = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'FontSize',10, ...
         'Min',1, ...
         'Max',3, ...
         'HorizontalAlignment','left', ...
         'Position',[25 55 655 70], ...
         'String',pagetitle, ...
         'Style','edit', ...
         'Tag','editPageTitle');

      h_chkClose = uicontrol('Parent',h_dlg, ...
         'Position',[190 10 320 20], ...
         'BackgroundColor',[0.95 0.95 0.95], ...
         'FontSize',10, ...
         'Style','checkbox', ...
         'String','Close dialog after generating plots and web page', ...
         'Value',1, ...
         'Tag','chkClose');

      h_cmdCancel = uicontrol('Parent',h_dlg, ...
         'Callback','ui_dateplots_template(''cancel'')', ...
         'FontSize',10, ...
         'Position',[10 10 75 25], ...
         'String','Cancel', ...
         'Tag','cmdCancel');

      h_cmdProceed = uicontrol('Parent',h_dlg, ...
         'Callback','ui_dateplots_template(''eval'')', ...
         'FontSize',10, ...
         'Position',[615 10 75 25], ...
         'String','Proceed', ...
         'Enable','off', ...
         'Tag','cmdProceed');

      h_cmdBrowseTemplate = uicontrol('Parent',h_dlg, ...
         'Callback','ui_dateplots_template(''browse_template'')', ...
         'FontSize',10, ...
         'Position',[619 390 65 25], ...
         'String','Browse', ...
         'Tag','cmdBrowseTemplate');

      h_cmdBrowse = uicontrol('Parent',h_dlg, ...
         'Callback','ui_dateplots_template(''browse'')', ...
         'FontSize',10, ...
         'Position',[619 360 65 25], ...
         'String','Browse', ...
         'Tag','cmdBrowse');

      uih = struct('editHTML',h_editHTML, ...
         'editName',h_editName, ...
         'editPath',h_editPath, ...
         'popInterval',h_popInterval, ...
         'editCols',h_editCols, ...
         'editWidth',h_editWidth, ...
         'lblThumbs',h_lblThumbs, ...
         'chkThumbs',h_chkThumbs, ...
         'editThumbs',h_editThumbs, ...
         'editTemplate',h_editTemplate, ...
         'editPageTitle',h_editPageTitle, ...
         'chkClose',h_chkClose, ...
         'cmdBrowseTemplate',h_cmdBrowseTemplate, ...
         'cmdBrowse',h_cmdBrowse, ...
         'cmdCancel',h_cmdCancel, ...
         'cmdProceed',h_cmdProceed, ...
         'h_fig',h_fig, ...
         'figwidth',figwidth, ...
         'intervals',{intervals});

      set(h_dlg,'UserData',uih,'Visible','on')
      drawnow

   end

else

   h_dlg = findobj('Tag','dlgDatePlotsTemplate');

   if ~isempty(h_dlg)

      uih = get(h_dlg(1),'UserData');

      switch op

         case 'cancel'

            delete(h_dlg)
            drawnow
            try
               figure(uih.h_fig)
            catch
               ui_aboutgce('reopen')  %check for last window
            end

         case 'eval'

            if ~isempty(h_dlg)

               uih = get(h_dlg(1),'UserData');

               template = deblank(get(uih.editTemplate,'String'));
               html = deblank(get(uih.editHTML,'String'));
               name = deblank(get(uih.editName,'String'));
               pn = deblank(get(uih.editPath,'String'));
               interval = uih.intervals{get(uih.popInterval,'Value')};
               wid = get(uih.editWidth,'UserData');
               thumbs = get(uih.chkThumbs,'Value');
               thumb_wid = get(uih.editThumbs,'UserData');
               cols = get(uih.editCols,'UserData');
               plotwidth = [thumb_wid,wid];
               pagetitle = deblank(get(uih.editPageTitle,'String'));
               closeopt = get(uih.chkClose,'Value');

               if ~isempty(template) & ~isempty(html) & ~isempty(name) & exist(pn) == 7

                  if closeopt == 1
                     delete(h_dlg)
                  end

                  msg = '';

                  try
                     figure(uih.h_fig)
                     drawnow
                  catch
                     msg = 'An error occurred accessing the original figure - operation cancelled';
                  end

                  if isempty(msg)

                     [pn_template,fn_template,fn_ext] = fileparts(template);  %parse path from file
                     fn_template = [fn_template,fn_ext];  %reassemble filename

                     msg = dateplot2template(fn_template,pn_template,cols,plotwidth,thumbs,interval,name,html,pn,uih.h_fig,pagetitle);
                     if ~isempty(msg)
                        messagebox('init',msg,'','Warning',[.9 .9 .9]);
                     elseif exist('syncpath','file') == 2 | exist('syncpath','file') == 6
                        syncpath(pn,'save')  %update path cache
                     end

                     if closeopt == 0
                        figure(h_dlg)
                     end

                  else
                     messagebox('init',msg,'','Error',[.9 .9 .9]);
                  end

               else
                  messagebox('init','Invalid base name for images files or invalid path','','Error',[.9 .9 .9]);
               end

            end

         case 'browse'

            pn = get(uih.editPath,'String');

            if exist('uigetdir','builtin') == 5
               pn = uigetdir(pn,'Select a directory to save the plot image files');
            else
               fn = [deblank(get(uih.editName,'String')),'_mmmyy',uih.fmtref{get(uih.popFormat,'Value'),2}];
               curpath = pwd;
               cd(pn)
               [pn,fn] = uiputfile(fn,'Select a directory to save the plot image files');
               cd(curpath)
            end

            if pn ~= 0
               if exist(pn) == 7
                  set(uih.editPath,'String',pn,'UserData',pn)
               end
            end

         case 'browse_template'

            template = deblank(get(uih.editTemplate,'String'));

            curpath = pwd;
            pn = curpath;
            if ~isempty(template)  %use last path if specified
               pn = fileparts(template);
               if exist(pn,'dir') ~= 7
                  pn = curpath;
               end
            end

            cd(pn)
            [fn,pn] = uigetfile('*.htm;*.html;*.asp;*.jsp;*.php','Select an HTML template to load');
            cd(curpath)

            if fn ~= 0
               template = [pn,fn];
               set(uih.editTemplate,'String',template,'UserData',template)
            end

            ui_dateplots_template('buttons')

         case 'template'

            template = deblank(get(uih.editTemplate,'String'));

            if exist(template,'file') ~= 2
               set(uih.editTemplate,'String',get(uih.editTemplate,'UserData'))
               messagebox('init','Invalid HTML file specified - value reset (use ''Browse'' to locate a valid file)', ...
                  '','Error',[.9 .9 .9]);
            else
               set(uih.editTemplate,'UserData',template)
            end

            ui_dateplots_template('buttons')

         case 'path'

            pn = deblank(get(uih.editPath,'String'));

            if exist(pn) == 7
               set(uih.editPath,'String',pn,'UserData',pn)
            else
               set(uih.editPath,'String',get(uih.editPath,'UserData'))
               drawnow
               messagebox('init','Invalid path -- selection reset to prior value','','Error',[.9 .9 .9])
            end

         case 'checknum'

            h_ui = gcbo;

            num = str2num(deblank(get(h_ui,'String')));
            if isempty(num)
               num = 0;
            else
               num = floor(num);
            end
            if num > 0
               set(h_ui,'String',int2str(num),'UserData',num)
            else
               set(h_ui,'String',num2str(get(h_ui,'UserData')))
               drawnow
               messagebox('init','Invalid setting -- value reset','','Error',[.9 .9 .9])
            end

         case 'thumbs'

            chk = get(uih.chkThumbs,'Value');
            if chk == 0
               vis = 'off';
            else
               vis = 'on';
            end
            set(uih.lblThumbs,'Visible',vis);
            set(uih.editThumbs,'Visible',vis);
            drawnow

         case 'buttons'

            template = deblank(get(uih.editTemplate,'String'));
            html = deblank(get(uih.editHTML,'String'));
            name = deblank(get(uih.editName,'String'));
            pn = deblank(get(uih.editPath,'String'));
            wid = str2num(deblank(get(uih.editWidth,'String')));

            if ~isempty(html) & ~isempty(name) & ~isempty(pn) & ~isempty(wid) & ~isempty(template)
               set(uih.cmdProceed,'Enable','on')
            else
               set(uih.cmdProceed,'Enable','off')
            end

      end

   end

end