function ui_gce_register(op,cb)
%GCE data download registration form dialog called by 'ui_search_data'
%
%syntax: ui_gce_register(op,cb)
%
%inputs:
%  op = operation ('init' to open dialog)
%  cb = callback to execute when the 'Register' button is pressed
%    (callback statement should reference the local variable 'registration'
%    to return a registration data structure)
%
%outputs:
%  none
%
%
%(c)2002-2011 Wade M. Sheldon and the Georgia Coastal Ecosystems LTER Project
%
%This file is part of the GCE Data Toolbox for MATLAB(r) software library.
%
%The GCE Data Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The GCE Data Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The GCE Data Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%
%contact:
%  Wade Sheldon
%  GCE-LTER Project
%  Department of Marine Sciences
%  University of Georgia
%  Athens, GA 30602-3636
%  sheldon@uga.edu
%
%last modified: 07-Sep-2011

if exist('op','var') ~= 1
   op = 'init';
end

if exist('cb','var') ~= 1
   cb = '';
end

if strcmp(op,'init')

   if length(findobj) > 1
      h_dlg = findobj('tag','dlgGCERegistration');
   else
      h_dlg = [];
   end

   if ~isempty(h_dlg)

      figure(h_dlg)

   else  %create dialog

      res = get(0,'ScreenSize');

      affil_list = {'','<please choose one>'; ...
            'GCE','GCE LTER'; ...
            'LTER','Other LTER Site'; ...
            'I-LTER','International LTER Site'; ...
            'Academic','Academic Research Program'; ...
            'EducationPS','Educational Program (post-secondary)'; ...
            'EducationK12','Educational Program (K-12)'; ...
            'Agency','Government Agency'; ...
            'Environmental','Environmental Advocacy Group'; ...
            'Other','Other'};

      username = '';
      useremail = '';
      useraffil = '';
      usernotify = 1;
      savereg = 0;

      %try to load user registration info
      if exist('gce_user_registration.mat') == 2
         v = load('gce_user_registration.mat');
         if isfield(v,'registration')
            username = v.registration.name;
            useremail = v.registration.email;
            useraffil = v.registration.affiliation;
            usernotify = v.registration.notify;
            savereg = 1;
         end
      else
         h_ui_search = findobj('Tag','dlgSearchData');
         if ~isempty(h_ui_search)
            uih = get(h_ui_search(1),'UserData');
            reg = uih.user_registration;
            if ~isempty(reg)
               username = reg.name;
               useremail = reg.email;
               useraffil = reg.affiliation;
               usernotify = reg.notify;
            end
         end
      end

      Iaffil = 1;
      if ~isempty(useraffil)
         Iaffil = find(strcmp(affil_list(:,1),useraffil));
         if isempty(Iaffil)
            Iaffil = 1;
         end
      end

      h_dlg = figure('Name','GCE Data Access Registration', ...
         'Visible','off', ...
         'Color',[0.9 0.9 0.9], ...
         'Position',[max(0,(res(3)-440).*0.5) max(20,(res(4)-330).*0.5) 440 330], ...
         'KeyPressFcn','figure(gcf)', ...
         'MenuBar','none', ...
         'NumberTitle','off', ...
         'Resize','off', ...
         'Tag','dlgGCERegistration', ...
         'ToolBar','none', ...
         'DefaultuicontrolUnits','pixels');

      if mlversion >= 7
         set(h_dlg,'WindowStyle','normal')
         set(h_dlg,'DockControls','off')
      end

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[.9 .9 .9], ...
         'Position',[1 1 439 329], ...
         'Style','frame', ...
         'Tag','Frame1');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'Position',[5 45 431 280], ...
         'Style','frame', ...
         'Tag','Frame1');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'FontSize',14, ...
         'ForegroundColor',[0 .6 0], ...
         'FontWeight','bold', ...
         'Position',[10 287 420 28], ...
         'String','GCE-LTER Data Access Registration', ...
         'Style','text', ...
         'Tag','StaticText1');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'FontSize',10, ...
         'Position',[30 249 110 20], ...
         'String','Full Name', ...
         'Style','text', ...
         'Tag','StaticText1');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'FontSize',10, ...
         'Position',[30 214 110 20], ...
         'String','Email Address', ...
         'Style','text', ...
         'Tag','StaticText1');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'FontSize',10, ...
         'Position',[30 178 110 20], ...
         'String','Affiliation', ...
         'Style','text', ...
         'Tag','StaticText1');

      h_editUserName = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'FontSize',9, ...
         'HorizontalAlignment','left', ...
         'Position',[140 247 250 24], ...
         'String',username, ...
         'Style','edit', ...
         'Tag','editUserName');

      h_editUserEmail = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'FontSize',9, ...
         'HorizontalAlignment','left', ...
         'Position',[140 213 250 24], ...
         'String',useremail, ...
         'Style','edit', ...
         'Tag','editUserEmail');

      h_popAffiliation = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'FontSize',9, ...
         'Position',[140 178 250 22], ...
         'String',affil_list(:,2), ...
         'Value',Iaffil, ...
         'Style','popupmenu', ...
         'Tag','popAffiliation');

      h_chkNotify = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'FontSize',10, ...
         'HorizontalAlignment','left', ...
         'Position',[70 136 320 22], ...
         'String','Nofify me if data sets I download are revised', ...
         'Style','checkbox', ...
         'Tag','chkNotify', ...
         'Value',usernotify);

      h_chkSave = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'FontSize',10, ...
         'HorizontalAlignment','left', ...
         'Position',[70 106 320 22], ...
         'String','Store my registration information on this computer', ...
         'Style','checkbox', ...
         'Tag','chkSave', ...
         'Value',savereg);

      h_cmdDataUse = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[.95 .95 .95], ...
         'FontSize',10, ...
         'Position',[80 60 280 25], ...
         'String','View GCE-LTER Data Use Agreement', ...
         'Style','pushbutton', ...
         'Tag','cmdDataUse', ...
         'Callback','ui_gce_register(''datause'')');

      h_cmdCancel = uicontrol('Parent',h_dlg, ...
         'Style','pushbutton', ...
         'Callback','ui_gce_register(''cancel'')', ...
         'FontSize',10, ...
         'Position',[10 10 90 28], ...
         'String','Cancel', ...
         'Tag','cmdCancel');

      h_cmdRegister = uicontrol('Parent',h_dlg, ...
         'Style','pushbutton', ...
         'Callback','ui_gce_register(''register'')', ...
         'FontSize',10, ...
         'Position',[340 10 90 28], ...
         'String','Register', ...
         'Tag','cmdRegister');

      uih = struct('editUserName',h_editUserName, ...
         'editUserEmail',h_editUserEmail, ...
         'popAffiliation',h_popAffiliation, ...
         'chkNotify',h_chkNotify, ...
         'chkSave',h_chkSave, ...
         'affil_list',{affil_list}, ...
         'cb',cb);

      set(h_dlg,'Visible','on','UserData',uih)
      drawnow

   end

else

   h_dlg = findobj('tag','dlgGCERegistration');

   if ~isempty(h_dlg)

      uih = get(h_dlg(1),'UserData');

      switch op

         case 'cancel'

            delete(h_dlg)
            ui_aboutgce('reopen')  %check for last window

         case 'datause'

            if exist('gce_datatools.mat') == 2
               v = load('gce_datatools.mat');
               if isfield(v,'gce_data_agreement')
                  ui_viewtext(v.gce_data_agreement,0,0,'GCE-LTER Data Use Agreement');
               end
            end

         case 'register'

            registration = [];

            %get uicontrol values
            name = deblank(get(uih.editUserName,'String'));
            email = deblank(get(uih.editUserEmail,'String'));
            affilopt = get(uih.popAffiliation,'Value');
            notify = get(uih.chkNotify,'Value');
            saveopt = get(uih.chkSave,'Value');

            %validate email address
            if ~isempty(email)
               if isempty(strfind(email,'@')) | isempty(strfind(email,'.'))
                  email = '';
               end
            end

            if ~isempty(name) & ~isempty(email) & affilopt > 1
               affil = uih.affil_list{affilopt,1};
               registration = struct('name',name, ...
                  'email',email, ...
                  'affiliation',affil, ...
                  'notify',notify);
               if saveopt == 1
                  pn = [gce_homepath,filesep,'userdata'];
                  save([pn,filesep,'gce_user_registration.mat'],'registration')
               elseif exist('gce_user_registration.mat') == 2  %clear prior entries if save option cleared
                  try
                     delete(which('gce_user_registration.mat'));
                  catch
                  end
               end
               close(h_dlg)
               if ~isempty(uih.cb)
                  err = 0;
                  eval(uih.cb,'err=1;')
                  if err == 1
                     messagebox('init','An error occurred executing the callback function', ...
                        '','Error',[.9 .9 .9])
                  end
               end

            else
               messagebox('init','Valid name, email address and affiliation are required for registration', ...
                  '','Error',[.9 .9 .9])
            end

      end

   end

end
