function ui_viewtext(str,wrap,indent,titlestr,figsize,font)
%Displays a string or cell array of strings in a scrolling list box viewer
%
%syntax:  ui_viewtext(text,wrap,indent,titlestr,figsize,font)
%
%input:
%  text = string or cell array of strings
%  wrap = column at which to wrap text (default = 0 {no wrap})
%  indent = number of characters to indent wrapped lines (default = 0)
%  titlestr = string to display as the dialog box title
%  figsize = figure size in pixels (2-element array of width, height; default = [750 600])
%  font = name of the font to use for text display (default = 'Courier New')
%
%(c)2002-2009 Wade M. Sheldon and the Georgia Coastal Ecosystems LTER Project
%
%This file is part of the GCE Data Toolbox for MATLAB(r) software library.
%
%The GCE Data Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The GCE Data Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The GCE Data Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%
%contact:
%  Wade Sheldon
%  GCE-LTER Project
%  Department of Marine Sciences
%  University of Georgia
%  Athens, GA 30602-3636
%  sheldon@uga.edu
%
%last modified: 23-Jan-2009

if exist('str','var') ~= 1
   str = {' '};
end

if exist('figsize','var') ~= 1
   figsize = [750 600];
elseif length(figsize) ~= 2
   figsize = [750 600];
end

if exist('titlestr','var') ~= 1
   titlestr = 'Text Viewer';
end

if exist('indent','var') ~= 1
   indent = 0;
end

if exist('wrap','var') ~= 1
   wrap = 0;
end

if exist('font','var') ~= 1
   if strcmp(computer,'PCWIN')
      font = 'Courier New';
   else
      font = 'Courier';
   end
end

res = get(0,'ScreenSize');

h_dlg = figure('visible','off', ...
   'Color',[.95 .95 .95], ...
   'Name',titlestr, ...
   'NumberTitle','off', ...
   'Menubar','none', ...
   'Toolbar','none', ...
   'KeyPressFcn','figure(gcf)', ...
   'Units','pixels', ...
   'Position',[max(0,0.5.*(res(3)-figsize(1))) max(50,0.5.*(res(4)-figsize(2))) figsize(1) figsize(2)], ...], ...
   'ResizeFcn',['h_list_temp=findobj(gcf,''Tag'',''listbox''); if ~isempty(h_list_temp); figpos_temp=get(gcf,''Position'');', ...
      'set(h_list_temp,''Position'',[1 1 figpos_temp(3) figpos_temp(4)-1]); end; clear h_list_temp figpos_temp'], ...
   'Tag','dlgViewText');

if mlversion >= 7
   set(h_dlg,'WindowStyle','normal')
   set(h_dlg,'DockControls','off')
end

h_mnuFile = uimenu('Parent',h_dlg, ...
   'Label','File', ...
   'Tag','mnuFile');

h_mnuEdit = uimenu('Parent',h_dlg, ...
   'Label','Edit', ...
   'Tag','mnuEdit');

h_mnuLoad = uimenu('Parent',h_mnuFile, ...
   'Label','Load Text File', ...
   'Callback','file2listbox', ...
   'Tag','mnuLoad');

h_mnuSave = uimenu('Parent',h_mnuFile, ...
   'Label','Save Text File', ...
   'Callback','listbox2file', ...
   'Tag','mnuSave');

h_mnuClose = uimenu('Parent',h_mnuFile, ...
   'Separator','on', ...
   'Label','Close Window', ...
   'Callback','delete(gcf)', ...
   'Tag','mnuClose');

h_mnuWrap = uimenu('Parent',h_mnuEdit, ...
   'Label','Word Wrap', ...
   'Tag','mnuWrap');

h_mnuWrap80 = uimenu('Parent',h_mnuWrap, ...
   'Label','80 characters', ...
   'Callback','h_list_temp=findobj(gcf,''Tag'',''listbox''); set(h_list_temp,''String'',wordwrap(get(h_list_temp,''UserData''),80,0)); clear h_list_temp', ...
   'Tag','mnuWrap80');

h_mnuWrap100 = uimenu('Parent',h_mnuWrap, ...
   'Label','100 characters', ...
   'Callback','h_list_temp=findobj(gcf,''Tag'',''listbox''); set(h_list_temp,''String'',wordwrap(get(h_list_temp,''UserData''),100,0)); clear h_list_temp', ...
   'Tag','mnuWrap100');

h_mnuWrap120 = uimenu('Parent',h_mnuWrap, ...
   'Label','120 characters', ...
   'Callback','h_list_temp=findobj(gcf,''Tag'',''listbox''); set(h_list_temp,''String'',wordwrap(get(h_list_temp,''UserData''),120,0)); clear h_list_temp', ...
   'Tag','mnuWrap120');

h_mnuWrap150 = uimenu('Parent',h_mnuWrap, ...
   'Label','150 characters', ...
   'Callback','h_list_temp=findobj(gcf,''Tag'',''listbox''); set(h_list_temp,''String'',wordwrap(get(h_list_temp,''UserData''),150,0)); clear h_list_temp', ...
   'Tag','mnuWrap150');

h_mnuWrapDefault = uimenu('Parent',h_mnuWrap, ...
   'Separator','on', ...
   'Label','None (reset)', ...
   'Callback','h_list_temp=findobj(gcf,''Tag'',''listbox''); set(h_list_temp,''String'',get(h_list_temp,''UserData'')); clear h_list_temp', ...
   'Tag','mnuWrapDefault');

h_list = uicontrol('Parent',h_dlg, ...
   'Units','pixels', ...
   'Style','listbox', ...
   'ListboxTop',1, ...
   'FontName',font, ...
   'FontSize',9, ...
   'BackgroundColor',[1 1 1], ...
   'String','', ...
   'Position',[1 1 figsize(1) figsize(2)-1], ...
   'Min',0, ...
   'Max',2, ...
   'Value',[], ...
   'Callback','set(gcbo,''Value'',1,''ListBoxTop'',get(gcbo,''ListBoxTop'')); set(gcbo,''Value'',[])', ...
   'Tag','listbox', ...
   'UserData',str);

set(h_dlg,'Visible','on','Pointer','watch')
drawnow

%format string as cell array
if ischar(str)
   str = cellstr(str);
end

%wrap text
if wrap > 0
   str = wordwrap(str,wrap,indent,'cell');
end

set(h_list,'String',str)
set(h_dlg,'Pointer','arrow')
drawnow
