function ui_viewdocs(op,fnc)
%Displays documentation for the GCE Data Toolbox in a scrolling text box with selectable sections
%
%syntax: ui_viewdocs(op,fnc)
%
%input:
%  op = operation ('init' to initialize dialog)
%  fnc = label of function to display help for (default = '')
%
%output:
%  none
%
%
%(c)2002-2009 Wade M. Sheldon and the Georgia Coastal Ecosystems LTER Project
%
%This file is part of the GCE Data Toolbox for MATLAB(r) software library.
%
%The GCE Data Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The GCE Data Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The GCE Data Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%
%contact:
%  Wade Sheldon
%  GCE-LTER Project
%  Department of Marine Sciences
%  University of Georgia
%  Athens, GA 30602-3636
%  sheldon@uga.edu
%
%last modified: 23-Jan-2009

if nargin == 0
   op = 'init';
end

if strcmp(op,'init') & exist('gce_datatools.mat') == 2

   v = load('gce_datatools.mat','-mat');
   if isfield(v,'docs')
      docs = v.docs;
      sections = {docs.section}';
      Isect = 1;
      if exist('fnc') == 1
         Isect = find(strcmp(fnc,{docs.function}));
         if ~isempty(Isect)
            Isect = Isect(1);
         end
      end
      str = docs(Isect).contents;
      [tmp,verstr] = strtok(v.toolboxversion);
   else
      fld = '';
      sections = '';
      Isect = 1;
      str = '';
      verstr = '';
   end

   res = get(0,'screensize');
   if strcmp(computer,'PCWIN')
      font = 'Courier New';
   else
      font = 'Courier';
   end

   h_fig = figure('Name','GCE Data Toolbox Documentation', ...
      'Position',[max(0,(res(3)-750)./2) max(30,(res(4)-654)./2) 762 654], ...
      'Color',[0.95 0.95 0.95], ...
      'KeyPressFcn','figure(gcf)', ...
      'MenuBar','none', ...
      'NumberTitle','off', ...
      'Tag','dlgViewDocs', ...
      'ToolBar','none', ...
      'Resize','off', ...
      'CloseRequestFcn','ui_viewdocs(''close'')', ...
      'DefaultuicontrolUnits','pixels');

   if mlversion >= 7
      set(h_fig,'WindowStyle','normal')
      set(h_fig,'DockControls','off')
   end

   h1 = uicontrol('Parent',h_fig, ...
      'Style','frame', ...
      'BackgroundColor',[0.95 0.95 0.95], ...
      'ForegroundColor',[0 0 0], ...
      'Position',[1 1 761 654], ...
      'Tag','Frame1');

   h1 = uicontrol('Parent',h_fig, ...
      'Style','text', ...
      'BackgroundColor',[0.95 0.95 0.95], ...
      'FontSize',12, ...
      'FontWeight','bold', ...
      'Position',[10 618 730 25], ...
      'String',['Documentation for the GCE Data Toolbox for Matlab',verstr], ...
      'Tag','StaticText1');

   h_popSection = uicontrol('Parent',h_fig, ...
      'Style','popupmenu', ...
      'Position',[10 582 350 22], ...
      'BackgroundColor',[1 1 1], ...
      'Callback','ui_viewdocs(''section'')', ...
      'FontName',font, ...
      'FontSize',9, ...
      'String',char(sections), ...
      'Tag','popSection', ...
      'Value',Isect);

   h_cmdBack = uicontrol('Parent',h_fig, ...
      'Callback','ui_viewdocs(''back'')', ...
      'FontSize',9, ...
      'FontWeight','bold', ...
      'Position',[370 582 70 22], ...
      'String','< Previous', ...
      'TooltipString','Open previous section of the documentation', ...
      'Tag','cmdBack');

   h_cmdForward = uicontrol('Parent',h_fig, ...
      'Callback','ui_viewdocs(''next'')', ...
      'FontSize',9, ...
      'FontWeight','bold', ...
      'Position',[442 582 70 22], ...
      'String','Next >', ...
      'TooltipString','Open next section of the documentation', ...
      'Tag','cmdForward');

   h_cmdExport = uicontrol('Parent',h_fig, ...
      'Callback','listbox2file', ...
      'FontSize',9, ...
      'FontWeight','bold', ...
      'Position',[682 582 70 22], ...
      'String','Export', ...
      'TooltipString','Export the current documentation section as a text file', ...
      'Tag','cmdExport');

   h_list = uicontrol('Parent',h_fig, ...
      'Style','listbox', ...
      'Position',[8 6 748 570], ...
      'BackgroundColor',[1 1 1], ...
      'FontName',font, ...
      'FontSize',9, ...
      'String',str, ...
      'Min',1, ...
      'Max',2, ...
      'Tag','list', ...
      'Value',1);

   uih = struct( ...
      'docs',{docs}, ...
      'sections',{sections}, ...
      'popsection',h_popSection, ...
      'previous',h_cmdBack, ...
      'next',h_cmdForward, ...
      'export',h_cmdExport, ...
      'list',h_list);

   set(h_fig,'userdata',uih)

else

   if length(findobj) > 0
      h_dlg = gcf;
      if strcmp(get(h_dlg,'tag'),'dlgViewDocs') ~= 1
         h_dlg = [];
      end
   else
      h_dlg = [];
   end

   if ~isempty(h_dlg)

      uih = get(h_dlg,'userdata');
      val = get(uih.popsection,'value');

      switch op

         case 'close'

            delete(h_dlg)
            drawnow
            ui_aboutgce('reopen')

         case 'back'

            if val > 1
               set(uih.popsection,'value',val-1)
               ui_viewdocs('section')
            end

         case 'next'

            if val < length(uih.sections)
               set(uih.popsection,'value',val+1)
               ui_viewdocs('section')
            end

         case 'section'

            str = uih.docs(val).contents;
            set(uih.list, ...
               'string',str, ...
               'listboxtop',1, ...
               'value',1)

      end

   end

end

