function s = newstruct(type,titlestr)
%Creates an empty GCE data or stat (statistical summary) structure, containing all default fields
%
%syntax:  s = newstruct(type,titlestr)
%
%input:
%  type = structure type (string; required):
%    'data' = GCE Data Structure (default)
%    'stat' = GCE Stat (statistical summary) structure
%  titlestr = data set title (string; optional)
%
%output:
%  s = empty structure of specified type
%
%
%(c)2002-2015 Wade M. Sheldon and the Georgia Coastal Ecosystems LTER Project
%
%This file is part of the GCE Data Toolbox for MATLAB(r) software library.
%
%The GCE Data Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The GCE Data Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The GCE Data Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%
%contact:
%  Wade Sheldon
%  GCE-LTER Project
%  Department of Marine Sciences
%  University of Georgia
%  Athens, GA 30602-3636
%  sheldon@uga.edu
%
%last modified: 23-Mar-2015

if exist('type','var') ~= 1
   type = 'data';
end

if exist('titlestr','var') ~= 1
   titlestr = '';
end

%check for structure type
if strcmp(type,'stat')

   %initialize statistical summary structure
   s = struct( ...
      'version','GCE Stat Structure 1.1 (29-Mar-2001)', ...
      'title',titlestr, ...
      'metadata',[], ...
      'history',[], ...
      'analysisdate',[], ...
      'flagoption',[], ...
      'name',[], ...
      'units',[], ...
      'description',[], ...
      'datatype',[], ...
      'variabletype',[], ...
      'numbertype',[], ...
      'precision',[], ...
      'criteria',[], ...
      'group',[], ...
      'groupvalue',[], ...
      'observations',[], ...
      'missing',[], ...
      'valid',[], ...
      'flagged',[], ...
      'min',[], ...
      'max',[], ...
      'total',[], ...
      'median',[], ...
      'mean',[], ...
      'stddev',[], ...
      'se',[]);

else  

   %initialize data structure
   s = struct( ...
      'version','GCE Data Structure 1.1 (29-Mar-2001)', ...
      'title','', ...
      'metadata',[], ...
      'datafile',[], ...
      'createdate',[], ...
      'editdate',[], ...
      'history',[], ...
      'name',[], ...
      'units',[], ...
      'description',[], ...
      'datatype',[], ...
      'variabletype',[], ...
      'numbertype',[], ...
      'precision',[], ...
      'values',[], ...
      'criteria',[], ...
      'flags',[]);

   %add initial history entry
   s.history = {datestr(now),'new GCE Data Structure 1.1 created (''newstruct'')'};
   
   %add creation date entry
   s.createdate = datestr(now);
   
   %add default metadata fields
   meta = meta_fields('FLED');   
   if ~isempty(meta)
      s.metadata = meta;
   end
   
   %add title without metadata update
   if ~isempty(titlestr)
      s = newtitle(s,titlestr,0);
   end
   
end