function h_menu = plotmenu(lbl,h_fig)
%Adds a menu item to a MATLAB figure containing commands for exporting figures in
%various vector and bitmap formats, toggling axis gridlines, and generating
%serial date plots are various intervals as images with or without accompanying HTML
%pages and thumbnail previews.
%
%syntax:  h_menu = plotmenu(label,h_fig)
%
%inputs:
%  lbl = menu label (default = 'Special')
%  h_fig = figure to modify (default = gcf)
%
%outputs:
%  h_menu = handle of the added menu item
%
%
%(c)2002-2015 Wade M. Sheldon and the Georgia Coastal Ecosystems LTER Project
%
%This file is part of the GCE Data Toolbox for MATLAB(r) software library.
%
%The GCE Data Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The GCE Data Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The GCE Data Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%
%contact:
%  Wade Sheldon
%  GCE-LTER Project
%  Department of Marine Sciences
%  University of Georgia
%  Athens, GA 30602-3636
%  sheldon@uga.edu
%
%last modified: 13-Apr-2015

%set default label if omitted
if exist('lbl','var') ~= 1
   lbl = 'Special';
end

%set default figure if omitted
if exist('h_fig','var') ~= 1
   h_fig = gcf;
end

%generate menu items
h_menu = uimenu('Parent',h_fig, ...
   'Label',lbl, ...
   'Tag','mnuGCETools');

h_export = uimenu('Parent',h_menu, ...
   'Label','Export Plot', ...
   'Tag','mnuExport');

if ispc  %generate Windows clipboard export menus
   h_clip = uimenu('Parent',h_export, ...
      'Label','Copy to Clipboard');
   uimenu('Parent',h_clip, ...
      'Label','Low Resolution (96dpi)', ...
      'Callback','print -noui -r96 -dmeta');
   uimenu('Parent',h_clip, ...
      'Label','Medium Resolution (150dpi)', ...
      'Callback','print -noui -r150 -dmeta');
   uimenu('Parent',h_clip, ...
      'Label','High Resolution (300dpi)', ...
      'Callback','print -noui -r300 -dmeta');
end

%check for graphics export function, add menu items
if exist('exportfig','file') == 2 || exist('exportfig','file') == 6

      h_ExpPS = uimenu('Parent',h_export, ...
         'Separator','on', ...
         'Label','Postscript file');

      h_ExpPNG = uimenu('Parent',h_export, ...
         'Label','PNG file');

      h_ExpJpeg = uimenu('Parent',h_export, ...
         'Label','JPeg file');

      h_ExpTiff = uimenu('Parent',h_export, ...
         'Label','TIFF file');

      uimenu('Parent',h_ExpPS, ...
         'Label','Postscript (color)', ...
         'Callback','exportfig(''psc'');');

      uimenu('Parent',h_ExpPS, ...
         'Label','Postscript (monochrome)', ...
         'Callback','exportfig(''psbw'');');

      uimenu('Parent',h_ExpPS, ...
         'Separator','on', ...
         'Label','EPS level 1 (color)', ...
         'Callback','exportfig(''epsc1'');');

      uimenu('Parent',h_ExpPS, ...
         'Label','EPS level 1 (monochrome)', ...
         'Callback','exportfig(''epsbw1'');');

      uimenu('Parent',h_ExpPS, ...
         'Separator','on', ...
         'Label','EPS level 2 (color)', ...
         'Callback','exportfig(''epsc2'');');

      uimenu('Parent',h_ExpPS, ...
         'Label','EPS level 2 (monochrome)', ...
         'Callback','exportfig(''epsbw2'');');

      uimenu('Parent',h_ExpPNG, ...
         'Label','Low Resolution (96dpi)', ...
         'Callback','exportfig(''pnglow'');');

      uimenu('Parent',h_ExpPNG, ...
         'Label','Medium Resolution (150dpi)', ...
         'Callback','exportfig(''pngmed'');');

      uimenu('Parent',h_ExpPNG, ...
         'Label','High Resolution (300dpi)', ...
         'Callback','exportfig(''pnghigh'');');

      uimenu('Parent',h_ExpPNG, ...
         'Label','Super High Resolution (600dpi)', ...
         'Callback','exportfig(''pngsuper'');');

      uimenu('Parent',h_ExpJpeg, ...
         'Label','Low Resolution (96 dpi)', ...
         'Callback','exportfig(''jpeglow'');');

      uimenu('Parent',h_ExpJpeg, ...
         'Label','Normal Resolution (150dpi)', ...
         'Callback','exportfig(''jpegmed'');');

      uimenu('Parent',h_ExpJpeg, ...
         'Label','High Resolution (300dpi)', ...
         'Callback','exportfig(''jpeghigh'');');

      uimenu('Parent',h_ExpJpeg, ...
         'Label','Super High Resolution (600dpi)', ...
         'Callback','exportfig(''jpegsuper'');');

      h_ExpTiffNoComp = uimenu('Parent',h_ExpTiff, ...
         'Label','No Compression');

      h_ExpTiffComp = uimenu('Parent',h_ExpTiff, ...
         'Label','LZW Compression');

      uimenu('Parent',h_ExpTiffNoComp, ...
         'Label','Low Resolution (96dpi)', ...
         'Callback','exportfig(''tifflnc'');');

      uimenu('Parent',h_ExpTiffNoComp, ...
         'Label','Medium Resolution (150dpi)', ...
         'Callback','exportfig(''tiffmnc'');');

      uimenu('Parent',h_ExpTiffNoComp, ...
         'Label','High Resolution (300dpi)', ...
         'Callback','exportfig(''tiffhnc'');');

      uimenu('Parent',h_ExpTiffNoComp, ...
         'Label','Super High Resolution (600dpi)', ...
         'Callback','exportfig(''tiffhnc'');');

      uimenu('Parent',h_ExpTiffComp, ...
         'Label','Low Resolution (96dpi)', ...
         'Callback','exportfig(''tifflc'');');

      uimenu('Parent',h_ExpTiffComp, ...
         'Label','Medium Resolution (150dpi)', ...
         'Callback','exportfig(''tiffmc'');');

      uimenu('Parent',h_ExpTiffComp, ...
         'Label','High Resolution (300dpi)', ...
         'Callback','exportfig(''tiffhc'');');

      uimenu('Parent',h_ExpTiffComp, ...
         'Label','Super High Resolution (600dpi)', ...
         'Callback','exportfig(''tiffhc'');');

      h_ExpFigML = uimenu('Parent',h_export, ...
         'Label','Matlab Plot File');

      uimenu('Parent',h_ExpFigML, ...
         'Label','Standard (exclude serializable objects)', ...
         'Callback','exportfig(''fig'');');

      uimenu('Parent',h_ExpFigML, ...
         'Label','Complete (include serializable objects)', ...
         'Callback','exportfig(''fig_all'');');

end

%check for GCE Data Toolbox data plot tools, add menu items
if exist('ui_dateplots','file') == 2 || exist('ui_dateplots','file') == 6
   uimenu('Parent',h_export, ...
      'Label','Generate Date Interval Plots', ...
      'Separator','on', ...
      'Callback','ui_dateplots(''init'')');
end
if exist('ui_dateplots_html','file') == 2 || exist('ui_dateplots_html','file') == 6
   uimenu('Parent',h_export, ...
      'Label','Generate Web Page of Date Interval Plots', ...
      'Callback','ui_dateplots_html(''init'')');

end
if exist('ui_dateplots_template','file') == 2 || exist('ui_dateplots_html','file') == 6
   uimenu('Parent',h_export, ...
      'Label','Add Date Interval Plots to an HTML Template', ...
      'Callback','ui_dateplots_template(''init'')');
end

h_Grid = uimenu('Parent',h_menu, ...
   'Label','Axis Grid Lines', ...
   'Separator','on', ...
   'Tag','mnuGrid');

h_Yaxis = uimenu('Parent',h_Grid, ...
   'Label','Y-axis Grid', ...
   'Tag','mnuYaxisGrid');

uimenu('Parent',h_Yaxis, ...
   'Label','Show', ...
   'Callback','set(gca,''YGrid'',''on''); drawnow', ...
   'Tag','mnuYaxisGridOn');

uimenu('Parent',h_Yaxis, ...
   'Label','Hide', ...
   'Callback','set(gca,''YGrid'',''off''); drawnow', ...
   'Tag','mnuYaxisGridOff');

h_Xaxis = uimenu('Parent',h_Grid, ...
   'Label','X-axis Grid', ...
   'Tag','mnuXaxisGrid');

uimenu('Parent',h_Xaxis, ...
   'Label','Show', ...
   'Callback','set(gca,''XGrid'',''on''); drawnow', ...
   'Tag','mnuXaxisGridOn');

uimenu('Parent',h_Xaxis, ...
   'Label','Hide', ...
   'Callback','set(gca,''XGrid'',''off''); drawnow', ...
   'Tag','mnuXaxisGridOff');

h_Both = uimenu('Parent',h_Grid, ...
   'Label','Both Axis Grids', ...
   'Tag','mnuBothGrids');

uimenu('Parent',h_Both, ...
   'Label','Show', ...
   'Callback','grid on; set(gca,''XGrid'',''on'',''YGrid'',''on''); drawnow', ...
   'Tag','mnuBothGridsOn');

uimenu('Parent',h_Both, ...
   'Label','Hide', ...
   'Callback','grid off; set(gca,''XGrid'',''off'',''YGrid'',''off''); drawnow', ...
   'Tag','mnuBothGridsOff');

h_Colors = uimenu('Parent',h_menu, ...
   'Label','Plot Colors', ...
   'Tag','mnuColors');

h_ColorsFBG = uimenu('Parent',h_Colors, ...
   'Label','Figure Background', ...
   'Tag','mnuColorsFBG');

h_ColorsBG = uimenu('Parent',h_Colors, ...
   'Label','Plot Background', ...
   'Tag','mnuColorsBG');

h_ColorsX = uimenu('Parent',h_Colors, ...
   'Label','X Axis/X Labels', ...
   'Tag','mnuColorsBG');

h_ColorsY = uimenu('Parent',h_Colors, ...
   'Label','Y Axis/Y Labels', ...
   'Tag','mnuColorsBG');

uimenu('Parent',h_Colors, ...
   'Separator','on', ...
   'Label','Default Colors', ...
   'Callback','set(gcf,''color'',[1 1 1]); set(gca,''color'',''none'',''xcolor'',[0 0 0],''ycolor'',[0 0 0])', ...
   'Tag','mnuColorsDefault');

uimenu('Parent',h_ColorsFBG, ...
   'Label','White', ...
   'Callback','set(gcf,''color'',[1 1 1]);', ...
   'Tag','mnuColorsFBGWhite');

uimenu('Parent',h_ColorsFBG, ...
   'Label','Gray', ...
   'Callback','set(gcf,''color'',[.9 .9 .9]);', ...
   'Tag','mnuColorsFBGGray');

uimenu('Parent',h_ColorsFBG, ...
   'Label','Blue', ...
   'Callback','set(gcf,''color'',[0 0 .8]);', ...
   'Tag','mnuColorsFBGBlue');

uimenu('Parent',h_ColorsFBG, ...
   'Separator','on', ...
   'Label','Custom', ...
   'Callback','uisetcolor(gcf);', ...
   'Tag','mnuColorsFBGColor');

uimenu('Parent',h_ColorsBG, ...
   'Label','White', ...
   'Callback','set(gca,''color'',[1 1 1]);', ...
   'Tag','mnuColorsBGWhite');

uimenu('Parent',h_ColorsBG, ...
   'Label','Gray', ...
   'Callback','set(gca,''color'',[.9 .9 .9]);', ...
   'Tag','mnuColorsBGWhite');

uimenu('Parent',h_ColorsBG, ...
   'Separator','on', ...
   'Label','Custom', ...
   'Callback','uisetcolor(gca);', ...
   'Tag','mnuColorsBGCustom');

uimenu('Parent',h_ColorsBG, ...
   'Separator','on', ...
   'Label','None', ...
   'Callback','set(gca,''color'',''none'');', ...
   'Tag','mnuColorsBGNone');

uimenu('Parent',h_ColorsX, ...
   'Label','Black', ...
   'Callback','set(gca,''xcolor'',[0 0 0]);', ...
   'Tag','mnuColorsXBlack');

uimenu('Parent',h_ColorsX, ...
   'Label','Blue', ...
   'Callback','set(gca,''xcolor'',[0 0 .8]);', ...
   'Tag','mnuColorsXBlue');

uimenu('Parent',h_ColorsX, ...
   'Label','White', ...
   'Callback','set(gca,''xcolor'',[1 1 1]);', ...
   'Tag','mnuColorsXWhite');

uimenu('Parent',h_ColorsX, ...
   'Label','Custom', ...
   'Separator','on', ...
   'Callback','c=uisetcolor(get(gca,''xcolor'')); if ~isempty(c); set(gca,''xcolor'',c); end; clear c', ...
   'Tag','mnuColorsXCustom');

uimenu('Parent',h_ColorsY, ...
   'Label','Black', ...
   'Callback','set(gca,''ycolor'',[0 0 0]);', ...
   'Tag','mnuColorsYBlack');

uimenu('Parent',h_ColorsY, ...
   'Label','Blue', ...
   'Callback','set(gca,''ycolor'',[0 0 .8]);', ...
   'Tag','mnuColorsYBlue');

uimenu('Parent',h_ColorsY, ...
   'Label','White', ...
   'Callback','set(gca,''ycolor'',[1 1 1]);', ...
   'Tag','mnuColorsYWhite');

uimenu('Parent',h_ColorsY, ...
   'Separator','on', ...
   'Label','Custom', ...
   'Callback','c=uisetcolor(get(gca,''ycolor'')); if ~isempty(c); set(gca,''ycolor'',c); end; clear c', ...
   'Tag','mnuColorsYCustom');

h_Legend = uimenu('Parent',h_menu, ...
   'Label','Legend', ...
   'Tag','mnuLegend');

h_LegendVis = uimenu('Parent',h_Legend, ...
   'Label','Visibility', ...
   'Tag','mnuLegendVis');

uimenu('Parent',h_LegendVis, ...
   'Label','Show/Active', ...
   'Callback',[ ...
      'h_legend=findobj(gcf,''Tag'',''legend'');' ...
      'if ~isempty(h_legend);' ...
      '  set(h_legend,''Visible'',''on'');' ...
      '  if mlversion < 8.4;' ...
      '    axes(h_legend);' ...
      '  end;' ...
      'end;' ...
      'clear h_legend' ...
      ], ...
   'Tag','mnuShowLegend');

uimenu('Parent',h_LegendVis, ...
   'Label','Hide', ...
   'Callback',[ ...
      'h_legend=findobj(gcf,''Tag'',''legend'');' ...
      'if ~isempty(h_legend);' ...
      '  set(h_legend,''Visible'',''off'');' ...
      'end;' ...
      'clear h_legend' ...
      ], ...
   'Tag','mnuShowLegend');

h_LegendBG = uimenu('Parent',h_Legend, ...
   'Label','Background', ...
   'Tag','mnuLegendBG');

h_LegendBorder = uimenu('Parent',h_Legend, ...
   'Label','Border', ...
   'Tag','mnuLegendBorder');

uimenu('Parent',h_LegendBG, ...
   'Label','Gray', ...
   'Callback',[ ...
      'h_legend=findobj(gcf,''Tag'',''legend'');' ...
      'if ~isempty(h_legend);' ...
      '  set(h_legend,''color'',[.9 .9 .9]);' ...
      'end;' ...
      'clear h_legend' ...
      ], ...
   'Tag','mnuLegendBGGray');

uimenu('Parent',h_LegendBG, ...
   'Label','White', ...
   'Callback',[ ...
      'h_legend=findobj(gcf,''Tag'',''legend'');' ...
      'if ~isempty(h_legend);' ...
      '  set(h_legend,''color'',[1 1 1]);' ...
      'end;' ...
      'clear h_legend' ...
      ], ...
   'Tag','mnuLegendBGNone');

uimenu('Parent',h_LegendBG, ...
   'Separator','on', ...
   'Label','Custom', ...
   'Callback',[ ...
      'h_legend=findobj(gcf,''Tag'',''legend'');' ...
      'if ~isempty(h_legend);' ...
      '  uisetcolor(h_legend);' ...
      'end;' ...
      'clear h_legend' ...
      ], ...
   'Tag','mnuLegendBGNone');

uimenu('Parent',h_LegendBG, ...
   'Separator','on', ...
   'Label','None', ...
   'Callback',[ ...
      'h_legend=findobj(gcf,''Tag'',''legend'');' ...
      'if ~isempty(h_legend);' ...
      '  if mlversion < 8.4;' ...
      '    set(h_legend,''color'',''none'',''box'',''off'',''xcolor'',get(gcf,''color''),''ycolor'',get(gcf,''color''));' ...
      '  else;' ...
      '    set(h_legend,''box'',''off'',''color'',get(gcf,''color''));' ...
      '  end;' ...
      'end;' ...
      'clear h_legend' ...
      ], ...
   'Tag','mnuLegendBGNone');

uimenu('Parent',h_LegendBorder, ...
   'Label','Black', ...
   'Callback',[ ...
      'h_legend=findobj(gcf,''Tag'',''legend'');' ...
      'if ~isempty(h_legend);' ...
      '  if mlversion < 8.4;' ...
      '    set(h_legend,''Visible'',''on'',''box'',''on'',''xcolor'',[0 0 0],''ycolor'',[0 0 0]);' ...
      '  else;' ...
      '    set(h_legend,''Visible'',''on'',''box'',''on'',''edgecolor'',[0 0 0]);' ...      
      '  end;' ...
      'end;' ...
      'clear h_legend' ...
      ], ...
   'Tag','mnuBorderBlack');

uimenu('Parent',h_LegendBorder, ...
   'Label','Blue', ...
   'Callback',[ ...
      'h_legend=findobj(gcf,''Tag'',''legend'');' ...
      'if ~isempty(h_legend);' ...
      '  if mlversion < 8.4;' ...
      '    set(h_legend,''Visible'',''on'',''box'',''on'',''xcolor'',[0 0 0.8],''ycolor'',[0 0 0.8]);' ...
      '  else;' ...
      '    set(h_legend,''Visible'',''on'',''box'',''on'',''edgecolor'',[0 0 0.8]);' ...      
      '  end;' ...
      'end;' ...
      'clear h_legend' ...
      ], ...
   'Tag','mnuBorderBlack');

uimenu('Parent',h_LegendBorder, ...
   'Label','Gray', ...
   'Callback',[ ...
      'h_legend=findobj(gcf,''Tag'',''legend'');' ...
      'if ~isempty(h_legend);' ...
      '  if mlversion < 8.4;' ...
      '    set(h_legend,''Visible'',''on'',''box'',''on'',''xcolor'',[0.9 0.9 0.9],''ycolor'',[0.9 0.9 0.9]);' ...
      '  else;' ...
      '    set(h_legend,''Visible'',''on'',''box'',''on'',''edgecolor'',[0.9 0.9 0.9]);' ...      
      '  end;' ...
      'end;' ...
      'clear h_legend' ...
      ], ...
   'Tag','mnuBorderGray');

uimenu('Parent',h_LegendBorder, ...
   'Label','White', ...
   'Callback',[ ...
      'h_legend=findobj(gcf,''Tag'',''legend'');' ...
      'if ~isempty(h_legend);' ...
      '  if mlversion < 8.4;' ...
      '    set(h_legend,''Visible'',''on'',''box'',''on'',''xcolor'',[1 1 1],''ycolor'',[1 1 1]);' ...
      '  else;' ...
      '    set(h_legend,''Visible'',''on'',''box'',''on'',''edgecolor'',[1 1 1]);' ...      
      '  end;' ...
      'end;' ...
      'clear h_legend' ...
      ], ...
   'Tag','mnuBorderWhite');

uimenu('Parent',h_LegendBorder, ...
   'Label','None', ...
   'Separator','on', ...
   'Callback',[ ...
      'h_legend=findobj(gcf,''Tag'',''legend'');' ...
      'if ~isempty(h_legend);' ...
      '  if mlversion < 8.4;' ...
      '    set(h_legend,''box'',''off'',''xcolor'',get(gcf,''color''),''ycolor'',get(gcf,''color''));' ...
      '  else;' ...
      '    set(h_legend,''box'',''off'',''color'',get(gcf,''color''));' ...
      '  end;' ...
      'end;' ...
      'clear h_legend' ...
      ], ...
   'Tag','mnuBorderNone');

h_mnuPointer = uimenu('Parent',h_menu, ...
   'Label','Pointer', ...
   'Tag','mnuPointer');

uimenu('Parent',h_mnuPointer, ...
   'Label','Arrow', ...
   'Tag','mnuPointerArrow', ...
   'Callback','set(gcf,''Pointer'',''arrow'');drawnow');

uimenu('Parent',h_mnuPointer, ...
   'Label','Crosshair', ...
   'Tag','mnuPointerCrosshair', ...
   'Callback','set(gcf,''Pointer'',''crosshair'');drawnow');

uimenu('Parent',h_mnuPointer, ...
   'Label','Full Crosshair', ...
   'Tag','mnuPointerFull', ...
   'Callback','set(gcf,''Pointer'',''fullcrosshair'');drawnow');

uimenu('Parent',h_mnuPointer, ...
   'Label','Circle', ...
   'Tag','mnuPointerCircle', ...
   'Callback','set(gcf,''Pointer'',''circle'');drawnow');

uimenu('Parent',h_mnuPointer, ...
   'Label','I-beam', ...
   'Tag','mnuPointerIBeam', ...
   'Callback','set(gcf,''Pointer'',''ibeam'');drawnow');

uimenu('Parent',h_mnuPointer, ...
   'Label','Fleur', ...
   'Tag','mnuPointerFleur', ...
   'Callback','set(gcf,''Pointer'',''fleur'');drawnow');

%check for addnote/editnote function, add menu item
if (exist('addnote','file') == 2 || exist('addnote','file') == 6) && (exist('editnote','file') == 2 || exist('editnote','file') == 6)
   uimenu('Parent',h_menu, ...
      'Label','Add Annotation', ...
      'Callback','addnote', ...
      'Separator','on', ...
      'Tag','mnuAddNote');
   sepval = 'off';
else
   sepval = 'on';
end

uimenu('Parent',h_menu, ...
   'Label','Resize Plots', ...
   'Tag','mnuResizePlots', ...
   'Separator',sepval, ...
   'Callback','plotresize(gcf)');

h_mnuMonthTicks = uimenu('Parent',h_menu, ...
   'Label','Monthly Ticks', ...
   'Tag','mnuMonthTicks');

uimenu('Parent',h_mnuMonthTicks, ...
   'Label','DD-MMM-YYYY format', ...
   'Callback','monthticks(1)');

uimenu('Parent',h_mnuMonthTicks, ...
   'Label','MM/DD/YYYY format', ...
   'Callback','monthticks(23)');

uimenu('Parent',h_mnuMonthTicks, ...
   'Label','MM/DD/YY format', ...
   'Callback','monthticks(2)');

uimenu('Parent',h_mnuMonthTicks, ...
   'Label','MMMYYYY format', ...
   'Callback','monthticks(28)');

uimenu('Parent',h_mnuMonthTicks, ...
   'Label','MMMYY format', ...
   'Callback','monthticks(12)');

uimenu('Parent',h_mnuMonthTicks, ...
   'Label','MMM format', ...
   'Callback','monthticks(3)');
