%% Process and post data 

%% Define function arguments
pn_source       = 'demo';
fn_source       = 'PHRSCTable1.dat';
template        = 'LNDB_phrsc_2';
sitecode        = 'PHRSC';
profile         = 'LNDB_HJA_PHRSC';  % Name of the profile used in the plotting templates
pn_dest_root    = 'C:\Users\kennedad\Dropbox\matlab\DEV_gce_datatools_380_gce_production\demo';
pn_dest_plot    = 'C:\Users\kennedad\Dropbox\matlab\DEV_gce_datatools_380_gce_production\demo';
html            = 1;
email           = 1;
pn_dest         = 'C:\Users\kennedad\Dropbox\matlab\gce_datatools_380_gce_production\demo\PHRSC';
pn_plots        = 'C:\Users\kennedad\Dropbox\matlab\gce_datatools_380_gce_production\demo\PHRSC';
c               = clock; % c = clock for real-time processing or yyyy for post processing
fn_dest         = sprintf('phrsc_%d.mat', c(1));
fn_gap          = sprintf('phrsc_%d_gap_times.txt', c(1));
reprocess       = 1;

%% call the harvester
data_harvester(pn_source, ...
    fn_source, ...
    template, ...
    sitecode, ...
    profile, ...
    pn_dest, ...
    pn_plots, ...
    html, ...
    email, ...
    fn_dest, ...
    fn_gap, ...
    reprocess)