%% Process and post data 

%% Define function arguments
source          = 'fetch_mcup_205_103';
load 'C:\Users\kennedad\Dropbox\matlab\gce_datatools_380_gce_production\userdata\FINAL STREAMNETWORK_QC4SIGMA_leap_ak.mat';    %added 20140924 to account for new qc stats file
qc_source       = data;
clear data
template        = 'LNDB_Streamt_2';
sitecode        = 'MCUP_205';
profile         = 'LNDB_HJA_MCUP_205_103';
pn_dest_root    = localpath('pn_dest_root');
pn_dest_plot    = localpath('pn_plots_root');
html            = localpath('html');
email           = localpath('email');
pn_dest         = strcat(pn_dest_root,'STREAMT\MCUP');
pn_plots        = strcat(pn_dest_root,'STREAMT\MCUP');
c               = 2014; % c = clock for real-time processing or yyyy for post processing
fn_dest         = sprintf('mcup_205_hrly.mat');
reprocess       = 1;

%% call the harvester
%data_harvester_sql(source,template,sitecode,profile,pn_dest,pn_plots,html,email,fn_dest);
streamt_data_harvester_sql(source, ...
    qc_source, ...
    template, ...
    sitecode, ...
    profile, ...
    pn_dest, ...
    pn_plots, ...
    html, ...
    email, ...
    fn_dest, ...
    reprocess);
