%begin detection limit notification columns
col = name2col(data,{'CM3_Up_Avg'});
if ~isempty(col)
    [data,msg] = add_calcexpr(data, ...
        '10', ...
        'CM3_Up_DTLM', ...
        'w m^-2', ...
        'Minimum detection limit for CM3 solar radiation sensor', ...
        col+1, ...
        1, ...
        '', ...
        'nominal' ...        
        );
end

col = name2col(data,{'CM3_Dn_Avg'});
if ~isempty(col)
    [data,msg] = add_calcexpr(data, ...
        '10', ...
        'CM3_Dn_DTLM', ...
        'w m^-2', ...
        'Minimum detection limit for CM3 solar radiation sensor', ...
        col+1, ...
        1, ...
        '', ...
        'nominal' ...        
        );
end

col = name2col(data,{'WINDSP_AVG'});
if ~isempty(col)
    [data,msg] = add_calcexpr(data, ...
        '1', ...
        'WINDSP_DTLM', ...
        'm ^s-1', ...
        'Minimum detection limit for propellor anemometer', ...
        col+1, ...
        1, ...
        '', ...
        'nominal' ...        
        );
end
